import { Post } from './types';

const STUDENT_TAGS = {
  Writing: ['✍️ Writing', '📄 Essay', '📚 Academic', '🇺🇸 English Learning', '🎓 Grad School', '📝 Vocabulary'],
  Coding: ['💻 Computer Science', '⌨️ Coding', '🐛 Debugging', '🛠️ Tools', '⚛️ React', '🐍 Python', '🕸️ Web Dev'],
  Campus: ['🏫 Campus Life', '🛠️ Practical', '🍱 Foodie', '🚌 Transport', '💤 Sleep', '🚽 Hidden Gems', '💸 Student Discount'],
  Misc: ['🎨 Art', '🧪 Science', '🔬 Lab', '🏀 Sports', '🌌 Physics', '🎭 Theater', '🏗️ Architecture', '🤯 Mind Blown']
};

export const ADDITIONAL_POSTS_4: Post[] = [
  // --- SECTION 1: ENGLISH WRITING & ACADEMIC (20 items) ---
  {
    id: '500',
    title: { en: 'Stop using "Very"! Use these words instead', zh: '写作干货：别再用 "Very" 了，试试这些高级词' },
    content: { en: 'Very happy -> Ecstatic. Very sad -> Despondent. Save this list.', zh: 'Very happy -> Ecstatic。Very sad -> Despondent。建议收藏背诵。' },
    author: 'VocabBuilder',
    tags: [...STUDENT_TAGS.Writing, '📝 Vocabulary', '✨ Tips'],
    likes: 3400,
    imageUrl: 'https://picsum.photos/400/300?random=500',
  },
  {
    id: '501',
    title: { en: 'Email template for asking for extension', zh: '作业写不完？求 Extension 的高情商邮件模版' },
    content: { en: 'Don\'t make excuses. Be professional and propose a new deadline.', zh: '不要找借口。保持专业，并主动提出新的 Deadline。' },
    author: 'ProfWhisperer',
    tags: [...STUDENT_TAGS.Writing, '📧 Email Etiquette', '🆘 Help', '🛠️ Practical'],
    likes: 5600,
    imageUrl: 'https://picsum.photos/400/300?random=501',
  },
  {
    id: '502',
    title: { en: 'Transition words to improve flow', zh: '让你的 Essay 丝般顺滑的连接词大全' },
    content: { en: 'However, Furthermore, Conversely, In light of this...', zh: '告别只会用 But 和 And。试试 However, Furthermore, Conversely...' },
    author: 'EssayDoctor',
    tags: [...STUDENT_TAGS.Writing, '📄 Essay', '📚 Study'],
    likes: 1200,
    imageUrl: 'https://picsum.photos/400/300?random=502',
  },
  {
    id: '503',
    title: { en: 'Paraphrasing tools review: Quillbot vs GPT', zh: '改写神器测评：Quillbot 还是 ChatGPT？' },
    content: { en: 'Which one is better at avoiding AI detection? Tested both.', zh: '哪个更能躲过 AI 检测？实测对比。' },
    author: 'CheatSheet',
    tags: [...STUDENT_TAGS.Writing, '🤖 AI Tools', '⚠️ Warning'],
    likes: 890,
    imageUrl: 'https://picsum.photos/400/300?random=503',
  },
  {
    id: '504',
    title: { en: 'Difference between i.e. and e.g.', zh: '一图看懂 i.e. 和 e.g. 的区别' },
    content: { en: 'i.e. = that is (clarification). e.g. = for example. Don\'t mix them up.', zh: 'i.e. 是“即”，e.g. 是“例如”。千万别混用，教授会扣分。' },
    author: 'GrammarPolice',
    tags: [...STUDENT_TAGS.Writing, '📝 Vocabulary', '❌ Common Mistakes'],
    likes: 450,
    imageUrl: 'https://picsum.photos/400/300?random=504',
  },
  {
    id: '505',
    title: { en: 'How to write a Literature Review', zh: '文献综述 (Literature Review) 到底该怎么写？' },
    content: { en: 'It\'s not just summarizing. You need to synthesize and find gaps.', zh: '不是简单的总结。你需要综合分析并找到研究缺口。' },
    author: 'PhDStudent',
    tags: [...STUDENT_TAGS.Writing, '🔬 Research', '🎓 Grad School'],
    likes: 2100,
    imageUrl: 'https://picsum.photos/400/300?random=505',
  },
  {
    id: '506',
    title: { en: 'My professor said my writing is "too flowerly"', zh: '教授说我的文章“太花哨”是什么意思？' },
    content: { en: 'Apparently academic writing needs to be concise. Cut the adjectives.', zh: '学术写作要简洁。删掉那些没用的形容词。' },
    author: 'SadWriter',
    tags: [...STUDENT_TAGS.Writing, '❓ Question', '😥 Sad'],
    likes: 120,
    imageUrl: 'https://picsum.photos/400/300?random=506',
  },
  {
    id: '507',
    title: { en: 'Citation tools: Zotero setup guide', zh: '参考文献救星：Zotero 保姆级安装教程' },
    content: { en: 'Stop typing bibliographies manually. This plugin saves lives.', zh: '别再手打参考文献了。这个插件能救命。' },
    author: 'TechSavvyStudent',
    tags: [...STUDENT_TAGS.Writing, '🛠️ Tools', '⚡ Productivity'],
    likes: 3300,
    imageUrl: 'https://picsum.photos/400/300?random=507',
  },
  {
    id: '508',
    title: { en: 'GRE Verbal: Memorizing 3000 words', zh: 'GRE 填空：如何两周背完三千词？' },
    content: { en: 'Using Anki and mnemonics. My brain hurts.', zh: '用 Anki 和记忆宫殿。脑子要炸了。' },
    author: 'GradSchoolHopeful',
    tags: [...STUDENT_TAGS.Writing, '📝 Test Prep', '🧠 Memory'],
    likes: 670,
    imageUrl: 'https://picsum.photos/400/300?random=508',
  },
  {
    id: '509',
    title: { en: 'Active Voice vs Passive Voice', zh: '主动语态 vs 被动语态：什么时候用哪个？' },
    content: { en: 'Science papers often prefer passive, but humanities like active.', zh: '理工科论文常用被动，但文科喜欢主动。' },
    author: 'WritingCenter',
    tags: [...STUDENT_TAGS.Writing, '📚 Academic', '💡 Tips'],
    likes: 240,
    imageUrl: 'https://picsum.photos/400/300?random=509',
  },
  {
    id: '510',
    title: { en: 'How to write a killer hook', zh: '如何写出吸引人的开头 (Hook)？' },
    content: { en: 'Start with a shocking fact or a question. Don\'t be boring.', zh: '用震惊的事实或提问开场。别写得太无聊。' },
    author: 'CreativeWriter',
    tags: [...STUDENT_TAGS.Writing, '✍️ Creative Writing'],
    likes: 510,
    imageUrl: 'https://picsum.photos/400/300?random=510',
  },
  {
    id: '511',
    title: { en: 'APA vs MLA format cheat sheet', zh: 'APA 和 MLA 格式速查表' },
    content: { en: 'Title page differences, margin rules. Print this out.', zh: '标题页区别，页边距规则。建议打印出来。' },
    author: 'FormatFreak',
    tags: [...STUDENT_TAGS.Writing, '🛠️ Practical', '📄 Essay'],
    likes: 880,
    imageUrl: 'https://picsum.photos/400/300?random=511',
  },
  {
    id: '512',
    title: { en: 'Grammarly Premium worth it?', zh: 'Grammarly 会员值得买吗？' },
    content: { en: 'The tone suggestions are nice, but it\'s expensive.', zh: '语气建议挺好用的，就是太贵了。' },
    author: 'BrokeStudent',
    tags: [...STUDENT_TAGS.Writing, '💸 Money', '❓ Question'],
    likes: 150,
    imageUrl: 'https://picsum.photos/400/300?random=512',
  },
  {
    id: '513',
    title: { en: 'Avoiding plagiarism 101', zh: '如何避免抄袭 (Plagiarism)？' },
    content: { en: 'Even if you paraphrase, you must cite the source!', zh: '即使改写了，也必须引用来源！Turnitin 很严格。' },
    author: 'AcademicIntegrity',
    tags: [...STUDENT_TAGS.Writing, '⚠️ Warning', '📚 Academic'],
    likes: 420,
    imageUrl: 'https://picsum.photos/400/300?random=513',
  },
  {
    id: '514',
    title: { en: 'Cold emailing professors for research', zh: '套磁攻略：怎么给教授发邮件找科研？' },
    content: { en: 'Read their recent papers first. Keep it short.', zh: '先读读他们最近的论文。邮件要简短。' },
    author: 'ResearchAsst',
    tags: [...STUDENT_TAGS.Writing, '🔬 Research', '📧 Email Etiquette'],
    likes: 1500,
    imageUrl: 'https://picsum.photos/400/300?random=514',
  },

  // --- SECTION 2: CODING & TECH DETAILS (20 items) ---
  {
    id: '520',
    title: { en: 'Centering a div: The ultimate guide', zh: 'CSS 永远的痛：如何垂直水平居中一个 Div' },
    content: { en: 'Flexbox, Grid, Absolute position... why is this so hard?', zh: 'Flexbox, Grid, 绝对定位... 为什么这么难？' },
    author: 'FrontendTears',
    tags: [...STUDENT_TAGS.Coding, '🎨 CSS', '😭 Crying'],
    likes: 2200,
    imageUrl: 'https://picsum.photos/400/300?random=520',
  },
  {
    id: '521',
    title: { en: 'Git commands you should know', zh: '除了 commit push，你还必须知道的 Git 指令' },
    content: { en: 'git cherry-pick, git stash, git rebase. Don\'t be scared.', zh: 'git cherry-pick, git stash, git rebase。别怕，炸不了。' },
    author: 'GitMaster',
    tags: [...STUDENT_TAGS.Coding, '🛠️ Tools', '💡 Tips'],
    likes: 1800,
    imageUrl: 'https://picsum.photos/400/300?random=521',
  },
  {
    id: '522',
    title: { en: 'Python list comprehension magic', zh: 'Python 列表推导式：一行代码装逼指南' },
    content: { en: 'Replace your for-loops with this one-liner. It\'s faster.', zh: '用这行代码代替你的 for 循环。更快更优雅。' },
    author: 'PyThon',
    tags: [...STUDENT_TAGS.Coding, '🐍 Python', '⚡ Efficiency'],
    likes: 920,
    imageUrl: 'https://picsum.photos/400/300?random=522',
  },
  {
    id: '523',
    title: { en: 'React useEffect dependency array explained', zh: 'React useEffect 依赖数组到底怎么填？' },
    content: { en: 'Infinite loops? Stale closures? Here is why.', zh: '死循环？闭包陷阱？原因都在这。' },
    author: 'ReactDev',
    tags: [...STUDENT_TAGS.Coding, '⚛️ React', '🐛 Debugging'],
    likes: 1100,
    imageUrl: 'https://picsum.photos/400/300?random=523',
  },
  {
    id: '524',
    title: { en: 'VS Code extensions for productivity', zh: '提升效率的 VS Code 插件推荐' },
    content: { en: 'Prettier, ESLint, GitLens. Install these now.', zh: 'Prettier, ESLint, GitLens。现在就装上。' },
    author: 'CodeNinja',
    tags: [...STUDENT_TAGS.Coding, '🛠️ Tools', '⚡ Productivity'],
    likes: 670,
    imageUrl: 'https://picsum.photos/400/300?random=524',
  },
  {
    id: '525',
    title: { en: 'SQL Joins visualized', zh: '一张图看懂 SQL Join (Inner, Left, Right, Full)' },
    content: { en: 'Venn diagrams make it so much easier to understand.', zh: '用韦恩图看就容易理解多了。' },
    author: 'DataNerd',
    tags: [...STUDENT_TAGS.Coding, '📊 Data Science', '🗄️ SQL'],
    likes: 1500,
    imageUrl: 'https://picsum.photos/400/300?random=525',
  },
  {
    id: '526',
    title: { en: 'Why is my C++ code segfaulting?', zh: 'C++ 段错误 (Segfault) 调试心得' },
    content: { en: 'Check your pointers. You probably accessed unallocated memory.', zh: '检查你的指针。你大概率访问了野指针。' },
    author: 'SegFaultSurvivor',
    tags: [...STUDENT_TAGS.Coding, '💻 C++', '🐛 Debugging', '😱 Scary'],
    likes: 430,
    imageUrl: 'https://picsum.photos/400/300?random=526',
  },
  {
    id: '527',
    title: { en: 'Docker for dummies', zh: 'Docker 入门：把你的环境打包带走' },
    content: { en: 'Works on my machine? Now it works on everyone\'s machine.', zh: '在我这能跑？现在在谁那都能跑了。' },
    author: 'DevOpsJr',
    tags: [...STUDENT_TAGS.Coding, '🐳 Docker', '🛠️ Tools'],
    likes: 890,
    imageUrl: 'https://picsum.photos/400/300?random=527',
  },
  {
    id: '528',
    title: { en: 'LeetCode Two Sum: Optimized approach', zh: 'LeetCode 第一题 Two Sum 的最优解' },
    content: { en: 'Use a Hash Map for O(n) time complexity. Don\'t double loop.', zh: '用哈希表实现 O(n) 时间复杂度。别用双重循环。' },
    author: 'AlgoExpert',
    tags: [...STUDENT_TAGS.Coding, '🧮 Algorithms', '💼 Interview Prep'],
    likes: 2100,
    imageUrl: 'https://picsum.photos/400/300?random=528',
  },
  {
    id: '529',
    title: { en: 'CSS Grid vs Flexbox: When to use what?', zh: 'CSS Grid 和 Flexbox 到底该用哪个？' },
    content: { en: 'Grid for 2D layouts, Flexbox for 1D. Simple rule.', zh: 'Grid 适合二维布局，Flexbox 适合一维。记住这个原则。' },
    author: 'DesignDev',
    tags: [...STUDENT_TAGS.Coding, '🎨 CSS', '🕸️ Web Dev'],
    likes: 550,
    imageUrl: 'https://picsum.photos/400/300?random=529',
  },
  {
    id: '530',
    title: { en: 'JavaScript "this" keyword is confusing', zh: 'JavaScript 的 "this" 到底指向谁？' },
    content: { en: 'Arrow functions vs regular functions. It depends on how it\'s called.', zh: '箭头函数 vs 普通函数。取决于它怎么被调用。' },
    author: 'JSConfused',
    tags: [...STUDENT_TAGS.Coding, '📜 JavaScript', '❓ Question'],
    likes: 780,
    imageUrl: 'https://picsum.photos/400/300?random=530',
  },
  {
    id: '531',
    title: { en: 'My first Hackathon experience', zh: '第一次参加黑客松 Hackathon 体验' },
    content: { en: 'Did not sleep for 24 hours. Ate too much pizza. We won 3rd place!', zh: '24小时没睡。吃了一吨披萨。我们拿了第三名！' },
    author: 'HackThePlanet',
    tags: [...STUDENT_TAGS.Coding, '🏆 Success Story', '🍕 Pizza'],
    likes: 1200,
    imageUrl: 'https://picsum.photos/400/300?random=531',
  },
  {
    id: '532',
    title: { en: 'Terminal shortcuts you need (Mac/Linux)', zh: 'Mac/Linux 终端快捷键大全' },
    content: { en: 'Ctrl+R to search history. Tab to autocomplete.', zh: 'Ctrl+R 搜索历史。Tab 自动补全。' },
    author: 'LinuxUser',
    tags: [...STUDENT_TAGS.Coding, '💻 Terminal', '⚡ Productivity'],
    likes: 340,
    imageUrl: 'https://picsum.photos/400/300?random=532',
  },
  {
    id: '533',
    title: { en: 'Why Java is so verbose', zh: 'Java 为什么写起来这么啰嗦？' },
    content: { en: 'Boilerplate code everywhere. Thank god for Lombok.', zh: '到处都是样板代码。感谢 Lombok 救我狗命。' },
    author: 'JavaHater',
    tags: [...STUDENT_TAGS.Coding, '☕ Java', '😡 Rant'],
    likes: 670,
    imageUrl: 'https://picsum.photos/400/300?random=533',
  },
  {
    id: '534',
    title: { en: 'Understanding REST APIs', zh: '五分钟看懂什么是 REST API' },
    content: { en: 'GET, POST, PUT, DELETE. It\'s just CRUD over HTTP.', zh: 'GET, POST, PUT, DELETE。就是 HTTP 上的增删改查。' },
    author: 'BackendDev',
    tags: [...STUDENT_TAGS.Coding, '🕸️ Web Dev', '📚 Tutorial'],
    likes: 560,
    imageUrl: 'https://picsum.photos/400/300?random=534',
  },

  // --- SECTION 3: CAMPUS UTILITIES & HACKS (20 items) ---
  {
    id: '540',
    title: { en: 'Best nap spots on campus (Secret)', zh: '校园最佳午睡点大揭秘（亲测）' },
    content: { en: 'Top floor of the library, behind the stacks. Super quiet.', zh: '图书馆顶楼书架后面。超级安静，没人打扰。' },
    author: 'SleepyHead',
    tags: [...STUDENT_TAGS.Campus, '💤 Sleep', '🤫 Secret Hack'],
    likes: 890,
    imageUrl: 'https://picsum.photos/400/300?random=540',
  },
  {
    id: '541',
    title: { en: 'Free condoms and advil at Health Center', zh: '校医院羊毛：免费避孕套和止痛药' },
    content: { en: 'You pay tuition fees for this. Go get them.', zh: '这都是你的学费包了的。不去白不去。' },
    author: 'HealthMonitor',
    tags: [...STUDENT_TAGS.Campus, '💸 Money Saving', '🏥 Health'],
    likes: 1200,
    imageUrl: 'https://picsum.photos/400/300?random=541',
  },
  {
    id: '542',
    title: { en: 'Dining hall hacks: Make your own waffle', zh: '食堂隐藏吃法：DIY 华夫饼三明治' },
    content: { en: 'Put fried chicken inside the waffle iron. Thank me later.', zh: '把炸鸡放进华夫饼机里压一下。你会回来谢我的。' },
    author: 'CampusChef',
    tags: [...STUDENT_TAGS.Campus, '🍱 Foodie', '💡 Hacks'],
    likes: 450,
    imageUrl: 'https://picsum.photos/400/300?random=542',
  },
  {
    id: '543',
    title: { en: 'Bus 51B is always late!!', zh: '51B 公交车永远在迟到！！' },
    content: { en: 'Missed my 9am class again. The app tracking is a lie.', zh: '又错过了早八的课。App 上的定位就是骗人的。' },
    author: 'LateStudent',
    tags: [...STUDENT_TAGS.Campus, '🚌 Transport', '😡 Rant'],
    likes: 780,
    imageUrl: 'https://picsum.photos/400/300?random=543',
  },
  {
    id: '544',
    title: { en: 'Hidden microwave in the Engineering building', zh: '工程楼里藏着的微波炉在哪里？' },
    content: { en: 'Basement, near the vending machines. Clean and fast.', zh: '地下室，自动贩卖机旁边。很干净。' },
    author: 'MealPrepLife',
    tags: [...STUDENT_TAGS.Campus, '🍱 Foodie', '🛠️ Practical'],
    likes: 210,
    imageUrl: 'https://picsum.photos/400/300?random=544',
  },
  {
    id: '545',
    title: { en: 'Gym hours are changing next week', zh: '下周健身房开放时间变动' },
    content: { en: 'Closing early for holidays. Check the schedule.', zh: '因为假期提前关门。大家注意看时间表。' },
    author: 'GymStaff',
    tags: [...STUDENT_TAGS.Campus, '🏋️ Gym', '📅 Schedule'],
    likes: 150,
    imageUrl: 'https://picsum.photos/400/300?random=545',
  },
  {
    id: '546',
    title: { en: 'Cleanest bathrooms on campus?', zh: '学校里哪个厕所最干净？' },
    content: { en: 'The Art building, 3rd floor. Always empty and smells nice.', zh: '艺术楼三楼。永远没人，而且香香的。' },
    author: 'PottyMap',
    tags: [...STUDENT_TAGS.Campus, '🚽 Hidden Gems', '🛠️ Practical'],
    likes: 990,
    imageUrl: 'https://picsum.photos/400/300?random=546',
  },
  {
    id: '547',
    title: { en: 'How to use print credits?', zh: '打印余额怎么用？快过期了' },
    content: { en: 'You have $20 free credits per semester. Print your textbooks.', zh: '每学期有20刀免费额度。把教科书打出来吧。' },
    author: 'PaperSaver',
    tags: [...STUDENT_TAGS.Campus, '💸 Money Saving', '📚 Academic'],
    likes: 340,
    imageUrl: 'https://picsum.photos/400/300?random=547',
  },
  {
    id: '548',
    title: { en: 'Roommate left laundry in machine for 5 hours', zh: '室友把衣服在洗衣机里放了5个小时' },
    content: { en: 'Can I take it out and put it on the floor?', zh: '我能把它拿出来扔地上吗？' },
    author: 'LaundryRage',
    tags: [...STUDENT_TAGS.Campus, '👯 Roommate', '😡 Rant', '❓ Question'],
    likes: 560,
    imageUrl: 'https://picsum.photos/400/300?random=548',
  },
  {
    id: '549',
    title: { en: 'Student discount at Apple Store', zh: '苹果店的学生优惠怎么用？' },
    content: { en: 'Bring your student ID. Save $100 on MacBooks.', zh: '带上学生证。MacBook 立省100刀。' },
    author: 'AppleEdu',
    tags: [...STUDENT_TAGS.Campus, '💸 Student Discount', '💻 Tech'],
    likes: 810,
    imageUrl: 'https://picsum.photos/400/300?random=549',
  },
  {
    id: '550',
    title: { en: 'Avoid the main library during finals', zh: '期末周千万别去主图书馆' },
    content: { en: 'It smells like sweat and desperation. Go to the Law library instead.', zh: '里面弥漫着汗水和绝望的味道。去法学院图书馆吧。' },
    author: 'StudyPro',
    tags: [...STUDENT_TAGS.Campus, '📚 Study', '⚠️ Warning'],
    likes: 670,
    imageUrl: 'https://picsum.photos/400/300?random=550',
  },
  {
    id: '551',
    title: { en: 'Free coffee at the Career Fair', zh: '招聘会上有免费咖啡！' },
    content: { en: 'Bring a resume, get a latte. Fair trade.', zh: '带上简历，换杯拿铁。这波不亏。' },
    author: 'CaffeineAddict',
    tags: [...STUDENT_TAGS.Campus, '☕ Coffee', '💼 Career'],
    likes: 230,
    imageUrl: 'https://picsum.photos/400/300?random=551',
  },
  {
    id: '552',
    title: { en: 'Lost Student ID card, replacement fee?', zh: '学生卡丢了，补办要多少钱？' },
    content: { en: '$25?? Are they printing it on gold?', zh: '25刀？？他们是用金子印的吗？' },
    author: 'ClumsyStudent',
    tags: [...STUDENT_TAGS.Campus, '💸 Money', '😡 Rant'],
    likes: 180,
    imageUrl: 'https://picsum.photos/400/300?random=552',
  },
  {
    id: '553',
    title: { en: 'Which vending machine takes Apple Pay?', zh: '哪个自动贩卖机支持 Apple Pay？' },
    content: { en: 'I forgot my wallet. Hungry.', zh: '忘带钱包了。饿。' },
    author: 'DigitalWallet',
    tags: [...STUDENT_TAGS.Campus, '❓ Question', '🍱 Foodie'],
    likes: 90,
    imageUrl: 'https://picsum.photos/400/300?random=553',
  },

  // --- SECTION 4: MISC / ART / SCI / SPORTS (Mix) ---
  {
    id: '560',
    title: { en: 'My bacteria culture grew mold :(', zh: '生物实验翻车：我的细菌培养皿长霉了' },
    content: { en: 'Contaminated sample. Have to restart the whole week.', zh: '样本污染了。整周的工作都要重做。心态崩了。' },
    author: 'LabRat',
    tags: [...STUDENT_TAGS.Misc, '🔬 Lab', '😭 Crying', '🧪 Biology'],
    likes: 450,
    imageUrl: 'https://picsum.photos/400/300?random=560',
  },
  {
    id: '561',
    title: { en: 'Intramural Soccer finals tonight!', zh: '今晚校内足球赛决赛！' },
    content: { en: 'Come support team "Goal Diggers". Free snacks.', zh: '来给“淘金者”队加油。有免费零食。' },
    author: 'SoccerCaptain',
    tags: [...STUDENT_TAGS.Misc, '⚽ Soccer', '🏆 Sports'],
    likes: 210,
    imageUrl: 'https://picsum.photos/400/300?random=561',
  },
  {
    id: '562',
    title: { en: 'Physics Problem Set 3 is impossible', zh: '物理作业 Set 3 根本做不出来' },
    content: { en: 'Question 4 about angular momentum... help.', zh: '第四题那个角动量... 救命。' },
    author: 'PhysicsMajor',
    tags: [...STUDENT_TAGS.Misc, '🌌 Physics', '🆘 Help Needed', '📚 Academic'],
    likes: 320,
    imageUrl: 'https://picsum.photos/400/300?random=562',
  },
  {
    id: '563',
    title: { en: 'Architecture studio: Haven\'t slept in 48h', zh: '建筑系日常：48小时没睡做模型' },
    content: { en: 'Glue gun burns everywhere. But the model looks sick.', zh: '满手都是热熔胶烫的泡。但是模型真的很帅。' },
    author: 'ArchStudent',
    tags: [...STUDENT_TAGS.Misc, '🏗️ Architecture', '🎨 Art', '😴 Sleep Deprived'],
    likes: 1500,
    imageUrl: 'https://picsum.photos/400/300?random=563',
  },
  {
    id: '564',
    title: { en: 'Auditions for Spring Musical "Hamilton"', zh: '春季音乐剧《汉密尔顿》试镜' },
    content: { en: 'Looking for singers and dancers. No experience needed.', zh: '招募歌手和舞者。无需经验。' },
    author: 'TheaterClub',
    tags: [...STUDENT_TAGS.Misc, '🎭 Theater', '🎶 Music', '💃 Dance'],
    likes: 670,
    imageUrl: 'https://picsum.photos/400/300?random=564',
  },
  {
    id: '565',
    title: { en: 'Ceramics class ruined my manicure', zh: '陶艺课毁了我的美甲' },
    content: { en: 'Clay gets everywhere. But making a bowl is therapeutic.', zh: '到处都是泥。但是捏个碗真的很治愈。' },
    author: 'ArtMinor',
    tags: [...STUDENT_TAGS.Misc, '🎨 Art', '💅 Fashion', '✨ Healing'],
    likes: 240,
    imageUrl: 'https://picsum.photos/400/300?random=565',
  },
  {
    id: '566',
    title: { en: 'Telescope night at the Observatory', zh: '天文台观星之夜' },
    content: { en: 'You can see Jupiter\'s moons tonight. Bring a jacket.', zh: '今晚能看到木星的卫星。带件外套。' },
    author: 'AstronomyClub',
    tags: [...STUDENT_TAGS.Misc, '🌌 Astronomy', '✨ Aesthetic', '🌿 Nature'],
    likes: 890,
    imageUrl: 'https://picsum.photos/400/300?random=566',
  },
  {
    id: '567',
    title: { en: 'Chemistry lab exploded (small fire)', zh: '化学实验室炸了（小火）' },
    content: { en: 'Someone mixed the wrong chemicals. We evacuated.', zh: '有人搞错了试剂。我们全撤离了。' },
    author: 'ChemHazard',
    tags: [...STUDENT_TAGS.Misc, '🧪 Chemistry', '🔥 Fire', '😰 Scary'],
    likes: 1200,
    imageUrl: 'https://picsum.photos/400/300?random=567',
  },
  {
    id: '568',
    title: { en: 'Selling my heavy architecture portfolio case', zh: '出闲置：建筑系超大作品集箱子' },
    content: { en: 'It\'s huge and fits A1 paper. $20.', zh: '巨无霸，能装 A1 纸。20刀拿走。' },
    author: 'GraduatedArch',
    tags: [...STUDENT_TAGS.Misc, '🛒 Marketplace', '🎨 Art'],
    likes: 80,
    imageUrl: 'https://picsum.photos/400/300?random=568',
  },
  {
    id: '569',
    title: { en: 'Quantum Mechanics is breaking my brain', zh: '量子力学要把我脑子烧干了' },
    content: { en: 'Schrodinger\'s cat is dead and alive. So is my GPA.', zh: '薛定谔的猫既死又活。我的 GPA 也是。' },
    author: 'QuantumTears',
    tags: [...STUDENT_TAGS.Misc, '🌌 Physics', '😭 Crying', '🤣 Funny'],
    likes: 950,
    imageUrl: 'https://picsum.photos/400/300?random=569',
  },
  {
    id: '570',
    title: { en: 'Digital Art exhibition in the lobby', zh: '大厅有数字艺术展' },
    content: { en: 'Come see our final projects. Interactive projections.', zh: '来看看我们的期末作业。交互投影。' },
    author: 'NewMediaArt',
    tags: [...STUDENT_TAGS.Misc, '🎨 Art', '💻 Tech', '👀 Watching'],
    likes: 310,
    imageUrl: 'https://picsum.photos/400/300?random=570',
  },
  {
    id: '571',
    title: { en: 'Badminton club needs more players', zh: '羽毛球社招新' },
    content: { en: 'We have rackets. Beginners welcome.', zh: '我们有拍子。欢迎萌新。' },
    author: 'Shuttlecock',
    tags: [...STUDENT_TAGS.Misc, '🏸 Badminton', '🤝 Team Up'],
    likes: 150,
    imageUrl: 'https://picsum.photos/400/300?random=571',
  },
  {
    id: '572',
    title: { en: '3D printing lab is open 24/7 now', zh: '3D 打印实验室现在24小时开放了' },
    content: { en: 'Wait times are still long though. Book online.', zh: '但是排队还是很长。记得网上预约。' },
    author: 'MakerSpace',
    tags: [...STUDENT_TAGS.Misc, '🛠️ DIY', '💻 Tech', '🏫 Campus Life'],
    likes: 440,
    imageUrl: 'https://picsum.photos/400/300?random=572',
  },
  {
    id: '573',
    title: { en: 'Psychology experiment: Paid participation', zh: '心理学实验招募：有偿' },
    content: { en: '$20 for 1 hour. Just need to look at pictures.', zh: '一小时20刀。只需要看图片。' },
    author: 'PsychDept',
    tags: [...STUDENT_TAGS.Misc, '🧠 Psychology', '💸 Money'],
    likes: 670,
    imageUrl: 'https://picsum.photos/400/300?random=573',
  }
];