import { Post } from './types';

// Redefine/Extend helper tags locally for this file to ensure high density without touching constants.ts
const WESTERN_TAGS = {
  // Topics (Mirrors original + extensions)
  Life: ['🌉 Bay Area', '🏠 Renting', '💸 Cost of Living', '💘 Dating', '🧘 Mental Health', '🚗 Cars', '✈️ Travel'],
  Tech: ['💻 Computer Science', '💼 Tech Career', '🔥 Burnout', 'Layoffs', 'RTO'],
  
  // New Vibe Categories
  Reddit: ['💬 Discussion', '❓ Question', '😡 Rant', '📖 Storytime', '🆘 Advice Needed', '🟢 Green Flag', '🚩 Red Flag', '🤬 AITA', '🔥 Hot Take', '🤷‍♂️ Unpopular Opinion', '💀 Dead'],
  GenZ: ['✨ Vibe', '🧢 Cap', '🗣️ Real Talk', '😭 Crying', '🤡 Clown World', '💅 Slay', '🤪 Delulu', '💀 I\'m Dead'],
  Context: ['🇺🇸 USA Culture', '🇺🇸 English Content', '🍔 American Life', '🏫 Student Problems', '🏢 Corporate Life']
};

// Export these so App.tsx can merge them into the LLM's vocabulary
export const EXTRA_TAGS = Object.values(WESTERN_TAGS).flat();

export const ADDITIONAL_POSTS: Post[] = [
  {
    id: '300',
    title: { en: 'AITA for telling my roommate to wear headphones?', zh: '叫室友戴耳机算我混蛋吗？' },
    content: { en: 'He plays TikToks at full volume at 2am. I have an 8am lecture. I snapped today.', zh: '他凌晨两点外放刷 TikTok。我早上八点还有课。今天我终于爆发了。' },
    author: 'SleepyStudent',
    tags: [...WESTERN_TAGS.Reddit, ...WESTERN_TAGS.GenZ, ...WESTERN_TAGS.Context, '👯 Roommate', '⚔️ Conflict', '🎧 Noise Complaint', '🏫 Dorm Life', '👿 Bad Roommate', '😴 Sleep Deprived', '📱 TikTok Addiction'],
    tagWeights: { '👯 Roommate': 2.5, '⚔️ Conflict': 2.0, '🏫 Dorm Life': 1.5, '🤬 AITA': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=300',
    likes: 5400,
  },
  {
    id: '301',
    title: { en: 'Tipping culture is out of control', zh: '小费文化已经失控了' },
    content: { en: 'The iPad asked for 20% on a self-serve frozen yogurt. I clicked "No Tip" and the cashier glared at me.', zh: '自助酸奶店的 iPad 都要20%小费。我点了“无小费”，收银员瞪了我一眼。' },
    author: 'NoTipWarrior',
    tags: [...WESTERN_TAGS.Reddit, ...WESTERN_TAGS.Life, '💸 Cost of Living', '🧾 Tipping Culture', '📉 Inflation', '🔥 Hot Take', '💵 Money', '🍽️ Dining Out', '🛑 Stop This', '🤬 Outrage', '🤖 iPad Tipping', '🙄 Eye Roll'],
    imageUrl: 'https://picsum.photos/400/300?random=301',
    likes: 12500,
  },
  {
    id: '302',
    title: { en: 'My HOA fined me $50 for "wrong mulch color"', zh: 'HOA 因为“护根颜色不对”罚了我50刀' },
    content: { en: 'I hate the suburbs. Can I fight this? It\'s literally brown mulch.', zh: '我讨厌郊区生活。这能申诉吗？明明就是普通的棕色护根。' },
    author: 'SuburbanDad',
    tags: [...WESTERN_TAGS.Reddit, '🏠 Renting', '🏡 Homeownership', '🏘️ Suburbs', '👮‍♂️ HOA Nightmare', '⚖️ Legal', '💸 Fines', '😡 Rant', '🌳 Gardening', '🇺🇸 USA Culture', '🆘 Advice Needed', '🤦‍♂️ Facepalm'],
    imageUrl: 'https://picsum.photos/400/300?random=302',
    likes: 890,
  },
  {
    id: '303',
    title: { en: 'Just paid off my student loans! ($45k)', zh: '终于还清了助学贷款！（4万5千刀）' },
    content: { en: 'Ate rice and beans for 3 years. It feels surreal. I\'m free.', zh: '吃了三年大米挂逼饭。感觉像做梦一样。我自由了。' },
    author: 'DebtFree23',
    tags: [...WESTERN_TAGS.Life, '💸 Money', '🎓 Student Loans', '✨ Inspirational', '🏆 Success Story', '🏦 Debt Free', '💰 Personal Finance', '🍚 Frugal Living', '🔓 Freedom', '📅 3 Year Journey', '💪 Grind', '🎉 Celebration', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=303',
    likes: 34000,
  },
  {
    id: '304',
    title: { en: 'Why is dating in SF so hard?', zh: '在旧金山约会怎么这么难？' },
    content: { en: 'Every guy works in tech and wears Patagonia vests. Conversations are like interviews.', zh: '每个男的都在科技公司，穿 Patagonia 马甲。聊天像面试一样。' },
    author: 'HingeSucks',
    tags: [...WESTERN_TAGS.Life, ...WESTERN_TAGS.Reddit, '💘 Dating', '🌉 Bay Area', '🌉 San Francisco', '💼 Tech Bro', '🧥 Patagonia Vest', '📱 Hinge', '💔 Heartbreak', '🎤 Interview Style', '🚬 Boring', '🚩 Red Flag', '👩 Female Perspective'],
    tagWeights: { '💘 Dating': 2.5, '🌉 Bay Area': 2.0, '👩 Female Perspective': 1.5, '💼 Tech Bro': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=304',
    likes: 2100,
  },
  {
    id: '305',
    title: { en: 'Taylor Swift Eras Tour tickets are impossible', zh: '霉霉演唱会门票根本抢不到' },
    content: { en: 'Ticketmaster crashed again. I was in queue for 4 hours. Crying rn.', zh: 'Ticketmaster 又崩了。排队排了4个小时。崩溃大哭。' },
    author: 'SwiftieForever',
    tags: [...WESTERN_TAGS.GenZ, '🍿 Entertainment', '🎶 Music', '🎤 Taylor Swift', '🎫 Ticketmaster', '💻 Tech Fail', '😭 Crying', '😰 Anxiety', '🎭 Emotional', '🎟️ Eras Tour', '😡 Rant', '👸 Pop Culture', '🇺🇸 English Content'],
    tagWeights: { '🎤 Taylor Swift': 2.5, '🎶 Music': 2.0, '🎫 Ticketmaster': 1.5, '🍿 Entertainment': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=305',
    likes: 4500,
  },
  {
    id: '306',
    title: { en: 'Unpopular Opinion: RTO is actually good', zh: '不吐不快：其实回办公室上班挺好的' },
    content: { en: 'I was depressed working from home alone. Free lunch + human interaction saved me.', zh: '在家办公太抑郁了。免费午餐加真人社交救了我。' },
    author: 'OfficeFan',
    tags: [...WESTERN_TAGS.Tech, ...WESTERN_TAGS.Reddit, '🏢 Return to Office', '🍱 Free Food', '🧘 Mental Health', '🤷‍♂️ Unpopular Opinion', '🤝 Networking', '👔 Corporate Life', '🏘️ Hybrid Work', '💬 Discussion', '🌥️ Depression', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=306',
    likes: 120,
  },
  {
    id: '307',
    title: { en: 'Super Bowl commercials were mid this year', zh: '今年的超级碗广告很一般' },
    content: { en: 'Too many celebrities, not enough creativity. Bring back the Clydesdales.', zh: '明星太多，创意太少。还我百威马。' },
    author: 'AdCritic',
    tags: [...WESTERN_TAGS.Reddit, '🍿 Entertainment', '🏈 Super Bowl', '📺 Commercials', '👎 Negative', '💬 Discussion', '🍺 Beer Ads', '🧔 Celebrities', '📉 Boring', '🇺🇸 USA Culture', '🏈 NFL', '💭 Opinion', '🇺🇸 English Content'],
    tagWeights: { '🏈 Super Bowl': 2.5, '📺 Commercials': 2.0, '🍿 Entertainment': 0.5 },
    imageUrl: 'https://picsum.photos/400/300?random=307',
    likes: 670,
  },
  {
    id: '308',
    title: { en: 'Gas is $5.50 again. Thanks California.', zh: '油价又涨到5.5刀了。谢谢你加州。' },
    content: { en: 'My commute is costing me a fortune. Is it time for a Tesla?', zh: '通勤费太贵了。是不是该买特斯拉了？' },
    author: 'GasPriceHater',
    tags: [...WESTERN_TAGS.Life, ...WESTERN_TAGS.Reddit, '⛽ Gas Prices', '🚗 Cars', '⚡ Tesla', '🌉 California', '📉 Inflation', '😡 Rant', '💸 Money', '🛣️ Commute', '🔌 EV Switch', '🇺🇸 English Content', '🤬 Politics'],
    imageUrl: 'https://picsum.photos/400/300?random=308',
    likes: 1500,
  },
  {
    id: '309',
    title: { en: 'Does anyone actually use Threads?', zh: '真的有人在用 Threads 吗？' },
    content: { en: 'It feels like a ghost town. Sticking to X (Twitter) for now.', zh: '感觉像个鬼城。我还是继续用推特吧。' },
    author: 'SocialMediaAddict',
    tags: [...WESTERN_TAGS.GenZ, '📱 Tech', '🧵 Threads', '🐦 Twitter', '👻 Ghost Town', '💬 Discussion', '❓ Question', '🤔 Curiosity', '📉 Dead App', '🌐 Social Media', '📸 Instagram', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=309',
    likes: 330,
  },
  {
    id: '310',
    title: { en: 'My landlord is selling the house', zh: '房东要把房子卖了' },
    content: { en: 'We have 30 days to move out. The rental market is insane right now.', zh: '只要30天搬家时间。现在的租房市场简直疯了。' },
    author: 'RentingNightmare',
    tags: [...WESTERN_TAGS.Reddit, '🏠 Renting', '📦 Moving', '😰 Anxiety', '🆘 Help Needed', '🏚️ Eviction', '💸 Expensive', '📈 Housing Market', '🤬 Landlords', '🛡️ Tenant Rights', '⚖️ Legal', '🇺🇸 English Content', '📅 Deadline'],
    imageUrl: 'https://picsum.photos/400/300?random=310',
    likes: 780,
  },
  {
    id: '311',
    title: { en: '49ers lost the Super Bowl...', zh: '49人队输了超级碗...' },
    content: { en: 'Heartbroken. Shanahan choked in OT. See you next season.', zh: '心碎了。Shanahan 加时赛拉胯了。下赛季见。' },
    author: 'NinersFan',
    tags: [...WESTERN_TAGS.Life, '🏀 Sports', '🏈 NFL', '🏈 49ers', '🌉 Bay Area', '🎭 Emotional', '😭 Crying', '🏆 Super Bowl', '💔 Heartbroken', '🏟️ Levi Stadium', '🇺🇸 English Content', '📅 Season Over', '😔 Sad'],
    imageUrl: 'https://picsum.photos/400/300?random=311',
    likes: 2200,
  },
  {
    id: '312',
    title: { en: 'Anyone hearing loud booms in Sunset district?', zh: 'Sunset 区听到巨响了吗？' },
    content: { en: 'Is it fireworks or gunshots? My dog is freaking out.', zh: '是烟花还是枪声？我家狗吓坏了。' },
    author: 'ConcernedNeighbor',
    tags: [...WESTERN_TAGS.Life, '🌉 San Francisco', '🌉 Sunset District', '❓ Question', '💥 Loud Noise', '🎇 Fireworks', '🔫 Gunshots', '🐾 Pets', '😰 Scary', '🛡️ Safety', '🏘️ Neighborhood', '🇺🇸 English Content', '👂 Hearing'],
    imageUrl: 'https://picsum.photos/400/300?random=312',
    likes: 45,
  },
  {
    id: '313',
    title: { en: 'Trader Joe\'s parking lot gives me anxiety', zh: 'Trader Joe\'s 的停车场让我焦虑' },
    content: { en: 'Why are the spaces so small? I almost scratched a BMW.', zh: '为什么车位这么小？差点蹭到一辆宝马。' },
    author: 'BadDriver',
    tags: [...WESTERN_TAGS.Reddit, '🚗 Cars', '🅿️ Parking', '😰 Anxiety', '🛒 Shopping', '🥦 Trader Joes', '🚘 BMW', '💥 Accident', '🏥 Stress', '🎢 Chaos', '🇺🇸 English Content', '🙋‍♂️ Relatable'],
    imageUrl: 'https://picsum.photos/400/300?random=313',
    likes: 1100,
  },
  {
    id: '314',
    title: { en: 'Is getting a MBA worth it in 2024?', zh: '2024年读 MBA 还值吗？' },
    content: { en: 'Tuition is $150k+. Job market seems weak for PMs.', zh: '学费15万刀。PM 的就业市场看起来很差。' },
    author: 'CareerPivot',
    tags: [...WESTERN_TAGS.Reddit, '💼 Career Advice', '🎓 MBA', '💸 Money', '❓ Question', '📉 Job Market', '📊 Product Management', '💰 ROI', '🏫 Business School', '🇺🇸 English Content', '🤔 Doubt', '♟️ Strategy'],
    imageUrl: 'https://picsum.photos/400/300?random=314',
    likes: 560,
  },
  {
    id: '315',
    title: { en: 'Found a stray cat, help needed', zh: '捡到一只流浪猫，求助' },
    content: { en: 'No chip. Very friendly. Taking it to SPCA tomorrow.', zh: '没芯片。很亲人。明天带去 SPCA。' },
    author: 'CatRescuer',
    tags: [...WESTERN_TAGS.Reddit, '🐾 Pets', '🐱 Cat', '🆘 Help Needed', '😇 Good Deed', '🏥 SPCA', '🏠 Adoption', '😺 Stray', '❤️ Wholesome', '🇺🇸 English Content', '🙌 Rescue'],
    imageUrl: 'https://picsum.photos/400/300?random=315',
    likes: 2300,
  },
  {
    id: '316',
    title: { en: 'Amazon Return Policy changed?', zh: '亚马逊退货政策变了？' },
    content: { en: 'They charged me $1 for dropping off at UPS. Prime isn\'t what it used to be.', zh: '去 UPS 退货居然收了我1刀。Prime 会员不如以前了。' },
    author: 'PrimeMember',
    tags: [...WESTERN_TAGS.Reddit, '🛒 Shopping', '📦 Amazon', '🚚 UPS', '💸 Money', '😡 Rant', '👎 Negative', '📉 Enshittification', '💳 Subscription', '❓ Question', '🇺🇸 English Content', '📦 Returns'],
    imageUrl: 'https://picsum.photos/400/300?random=316',
    likes: 310,
  },
  {
    id: '317',
    title: { en: 'Best tacos in Mission District?', zh: 'Mission 区哪家 Tacos 最好吃？' },
    content: { en: 'El Farolito or La Taqueria? I need authentic al pastor.', zh: 'El Farolito 还是 La Taqueria？想吃正宗的。' },
    author: 'TacoLover',
    tags: [...WESTERN_TAGS.Life, '🍱 Foodie', '🌮 Tacos', '🇲🇽 Mexican Food', '🌉 San Francisco', '🌉 Mission District', '❓ Question', '🌯 Burrito', '🍽️ Dining Out', '⚔️ Debate', '🇺🇸 English Content', '😋 Yummy'],
    imageUrl: 'https://picsum.photos/400/300?random=317',
    likes: 420,
  },
  {
    id: '318',
    title: { en: 'Tech bros ruining the city vibe', zh: '科技男毁了这城市的氛围' },
    content: { en: 'Everything is expensive and boring now. Where are the artists?', zh: '现在所有东西都又贵又无聊。艺术家都去哪了？' },
    author: 'LocalArtist',
    tags: [...WESTERN_TAGS.Reddit, '🌉 Bay Area', '🌉 San Francisco', '💸 Gentrification', '💼 Tech Bro', '🎨 Art Scene', '😡 Rant', '💬 Discussion', '🏙️ City Life', '📉 Boring', '😔 Nostalgia', '🇺🇸 English Content', '🔥 Hot Take'],
    tagWeights: { '🌉 San Francisco': 2.0, '💸 Gentrification': 2.0, '💼 Tech Bro': 2.0, '🎨 Art Scene': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=318',
    likes: 890,
  },
  {
    id: '319',
    title: { en: 'Hiking Half Dome: Permit Lottery', zh: '半圆顶徒步：抽签攻略' },
    content: { en: 'Applied 3 times and failed. Any tips for the daily lottery?', zh: '申请三次都挂了。每日抽签有什么技巧吗？' },
    author: 'Hiker4Life',
    tags: [...WESTERN_TAGS.Life, '🥾 Hiking', '🌲 Outdoors', '⛰️ Yosemite', '🏔️ Half Dome', '🎫 Permits', '❓ Question', '🏞️ National Parks', '🎰 Lottery', '🏃 Fitness', '🇺🇸 English Content', '📅 Travel Planning'],
    imageUrl: 'https://picsum.photos/400/300?random=319',
    likes: 150,
  },
  {
    id: '320',
    title: { en: 'Gym Etiquette: Wipe down your bench!', zh: '健身房礼仪：擦干净你的凳子！' },
    content: { en: 'Sat in a puddle of sweat today. Disgusting. Do better people.', zh: '今天坐了一屁股汗。太恶心了。素质高点好吗。' },
    author: 'GymRegular',
    tags: [...WESTERN_TAGS.Reddit, '🏋️ Gym', '💪 Fitness', '🧼 Hygiene', '😡 Rant', '⚠️ Warning', '🦠 Gross', '🧘 Etiquette', '🤬 Anger', '🏃 Workout', '🇺🇸 English Content', '🤢 Disgusting'],
    imageUrl: 'https://picsum.photos/400/300?random=320',
    likes: 670,
  },
  {
    id: '321',
    title: { en: 'Is therapy actually helpful?', zh: '心理咨询真的有用吗？' },
    content: { en: 'It costs $200/session out of pocket. I feel like I\'m just venting.', zh: '自费200刀一次。感觉我就是在发牢骚。' },
    author: 'MentalHealthCheck',
    tags: [...WESTERN_TAGS.Reddit, '🧘 Mental Health', '💸 Money', '🏥 Therapy', '🩺 Healthcare', '❓ Question', '🤔 Skeptical', '💬 Talk Therapy', '🇺🇸 USA System', '🆘 Help Needed', '💵 Expensive', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=321',
    likes: 330,
  },
  {
    id: '322',
    title: { en: 'Looking for D&D group (Beginner friendly)', zh: '寻找 D&D 跑团（萌新友好）' },
    content: { en: 'Watched Stranger Things and want to try. Can bring snacks.', zh: '看了怪奇物语想试试。可以带零食。' },
    author: 'DndNewbie',
    tags: [...WESTERN_TAGS.Life, '🎮 Gaming', '🐉 Dungeons & Dragons', '🎲 Board Games', '🤝 Team Up', '🥂 Social', '🍿 Stranger Things', '🤓 Geek Culture', '🟢 Beginner Friendly', '🇺🇸 English Content', '🍕 Snacks'],
    // CRITICAL FIX: Core is Gaming/D&D (2.0). Social is secondary (1.0).
    tagWeights: { '🎮 Gaming': 2.0, '🐉 Dungeons & Dragons': 2.5, '🥂 Social': 1.0, '🎲 Board Games': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=322',
    likes: 80,
  },
  {
    id: '323',
    title: { en: 'My instacart shopper ate my fries', zh: 'Instacart 配送员吃了我的薯条' },
    content: { en: 'The bag was open and half gone. Support gave me $5 credit. Joke.', zh: '袋子是开的，少了一半。客服给了5刀 credit。笑话。' },
    author: 'HangryCustomer',
    tags: [...WESTERN_TAGS.Reddit, '🍱 Foodie', '🚗 Delivery', '🛒 Instacart', '😡 Rant', '👎 Negative', '🍟 Fries', '🤐 Customer Service', '📉 Fail', '🤬 Theft', '🇺🇸 English Content', '🍟 Food Theft'],
    imageUrl: 'https://picsum.photos/400/300?random=323',
    likes: 1200,
  },
  {
    id: '324',
    title: { en: 'Barbie movie was better than Oppenheimer', zh: '芭比比奥本海默好看' },
    content: { en: 'Fight me. The satire was on point.', zh: '不服来辩。讽刺很到位。' },
    author: 'MovieBuff',
    tags: [...WESTERN_TAGS.GenZ, '🍿 Entertainment', '🎬 Movies', '🎀 Barbie', '💣 Oppenheimer', '💬 Discussion', '💭 Opinion', '🔥 Hot Take', '⚔️ Debate', '🎭 Satire', '👸 Feminism', '🇺🇸 English Content'],
    tagWeights: { '🎬 Movies': 2.0, '🎀 Barbie': 2.0, '💣 Oppenheimer': 2.0, '⚔️ Debate': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=324',
    likes: 950,
  },
  {
    id: '325',
    title: { en: 'Winter depression (SAD) is hitting hard', zh: '冬季抑郁 (SAD) 来了' },
    content: { en: 'It gets dark at 4:30pm. I have zero motivation.', zh: '下午4点半天就黑了。完全没有动力。' },
    author: 'SeasonalBlue',
    tags: [...WESTERN_TAGS.Reddit, '🧘 Mental Health', '😰 Anxiety', '🌧️ SAD', '❄️ Winter', '🌑 Darkness', '🎭 Emotional', '💊 Vitamin D', '😴 Fatigue', '🇺🇸 USA Weather', '🆘 Advice Needed', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=325',
    likes: 1400,
  },
  {
    id: '326',
    title: { en: 'Credit Score dropped 50 points?', zh: '信用分跌了50分？' },
    content: { en: 'I paid off my car loan and my score went DOWN. Make it make sense.', zh: '我还清了车贷结果分数跌了。这合理吗？' },
    author: 'CreditConfused',
    tags: [...WESTERN_TAGS.Life, '💸 Money', '💳 Credit Score', '🏦 Banking', '❓ Question', '😡 Rant', '🤔 Confused', '📉 FICO', '💵 Loans', '🇺🇸 USA System', '🤬 Nonsense', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=326',
    likes: 210,
  },
  {
    id: '327',
    title: { en: 'Best place to work remotely in SF?', zh: '旧金山哪里适合远程办公？' },
    content: { en: 'Coffee shops with good wifi and outlets. No Capital One Cafe please.', zh: '求推荐网好有插座的咖啡店。不要 Capital One。' },
    author: 'DigitalNomad',
    tags: [...WESTERN_TAGS.Tech, '☕ Coffee', '⚡ Productivity', '💻 Remote Work', '🌉 San Francisco', '📶 Wifi', '❓ Question', '🏢 Coworking', '🔌 Outlets', '👨‍💻 Digital Nomad', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=327',
    likes: 180,
  },
  {
    id: '328',
    title: { en: 'Neighbors smoking weed, smell entering my apartment', zh: '邻居抽大麻，味道飘进我家了' },
    content: { en: 'I have a baby. Landlord won\'t do anything. Advice?', zh: '家里有宝宝。房东不管。求建议？' },
    author: 'ConcernedMom',
    tags: [...WESTERN_TAGS.Reddit, '🏠 Renting', '🌿 Weed', '⚔️ Conflict', '🆘 Help Needed', '👶 Parenting', '👃 Smell', '👮‍♂️ Legal', '😈 Bad Neighbors', '🇺🇸 English Content', '🚭 Smoke'],
    imageUrl: 'https://picsum.photos/400/300?random=328',
    likes: 410,
  },
  {
    id: '329',
    title: { en: 'Coachella Lineup sucks this year', zh: '今年 Coachella 阵容太烂了' },
    content: { en: 'Selling my wristband. DM to buy.', zh: '出票。私信我。' },
    author: 'FestivalGoer',
    tags: [...WESTERN_TAGS.GenZ, '🎉 Party', '🎶 Music', '🎡 Coachella', '👎 Negative', '🎫 Ticket Sales', '💸 Waste of Money', '🌵 Festival', '📉 Flop', '🇺🇸 English Content', '🤬 Hate It'],
    tagWeights: { '🎉 Party': 2.0, '🎡 Coachella': 2.5, '🎶 Music': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=329',
    likes: 90,
  },
  {
    id: '330',
    title: { en: 'I quit my job to travel the world', zh: '辞职去环游世界了' },
    content: { en: 'Scary but exciting. Starting in Thailand. Follow my journey.', zh: '很害怕但也兴奋。第一站泰国。' },
    author: 'Wanderlust',
    tags: [...WESTERN_TAGS.Reddit, '✈️ Travel', '✨ Inspirational', '📖 Storytime', '🌏 Digital Nomad', '🇹🇭 Thailand', '💼 Resignation', '🔓 Freedom', '📸 Photography', '🎒 Backpacking', '🇺🇸 English Content', '🌅 Adventure'],
    imageUrl: 'https://picsum.photos/400/300?random=330',
    likes: 3100,
  },
  {
    id: '331',
    title: { en: 'Dating a coworker? Bad idea?', zh: '和同事约会？作死吗？' },
    content: { en: 'We have great chemistry but I don\'t want HR trouble.', zh: '我们很合得来，但是我不想惹 HR 麻烦。' },
    author: 'OfficeRomance',
    tags: [...WESTERN_TAGS.Reddit, '💘 Dating', '💼 Tech Career', '🏢 Office Politics', '❓ Question', '🤐 HR', '🚩 Red Flag', '❤️ Romance', '🤔 Dilemma', '⚠️ Risky', '🇺🇸 English Content', '💑 Relationships'],
    tagWeights: { '💘 Dating': 2.0, '💼 Tech Career': 0.5, '🏢 Office Politics': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=331',
    likes: 550,
  },
  {
    id: '332',
    title: { en: 'Wait time at SFO security', zh: 'SFO 安检排队时间' },
    content: { en: 'Clear line is longer than TSA Pre. What is the point of paying?', zh: 'Clear 的队比 TSA Pre 还长。花钱图啥？' },
    author: 'FrequentFlyer',
    tags: [...WESTERN_TAGS.Life, '✈️ Travel', '😡 Rant', '🌉 Bay Area', '🛫 SFO', '🛂 TSA', '💸 Scam', '⏳ Long Lines', '🏢 Airports', '🎫 Clear', '🇺🇸 English Content', '👎 Disappointment'],
    imageUrl: 'https://picsum.photos/400/300?random=332',
    likes: 220,
  },
  {
    id: '333',
    title: { en: 'Best pizza: NY or Chicago style?', zh: '最好的披萨：纽约还是芝加哥风味？' },
    content: { en: 'Deep dish is a casserole, not a pizza. Don\'t @ me.', zh: '深盘是砂锅菜，不是披萨。不接受反驳。' },
    author: 'PizzaPurist',
    tags: [...WESTERN_TAGS.Reddit, '🍱 Foodie', '🍕 Pizza', '⚔️ Debate', '💬 Discussion', '🗽 New York', '🏙️ Chicago', '🔥 Hot Take', '🤐 Shut Up', '🍽️ Dining', '🇺🇸 USA Food', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=333',
    likes: 890,
  },
  {
    id: '334',
    title: { en: 'My dog ate a grape, headed to ER', zh: '狗吃了葡萄，正在去急诊' },
    content: { en: 'Please pray for Buster. Vet said kidney failure is possible.', zh: '为 Buster 祈祷。兽医说可能会肾衰竭。' },
    author: 'DogDad',
    tags: [...WESTERN_TAGS.Reddit, '🐾 Pets', '🐶 Dog', '😰 Scary', '🆘 Help Needed', '🏥 Vet', '🍇 Poison', '🚑 Emergency', '🙏 Prayers', '😢 Sad', '🏥 Medical', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=334',
    likes: 1500,
  },
  {
    id: '335',
    title: { en: 'Internship search is depressing', zh: '找实习找得抑郁了' },
    content: { en: '500 applications, 2 interviews, 0 offers. Is it me?', zh: '投了500份，2个面试，0 offer。是我的问题吗？' },
    author: 'CSStudent25',
    tags: [...WESTERN_TAGS.Reddit, '🎓 Internship', '😰 Anxiety', '💼 Tech Career', '📄 Resume', '🛑 Rejection', '😞 Depression', '💪 Grind', '🏫 Student Life', '🆘 Advice Needed', '📉 Tough Market', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=335',
    likes: 2100,
  },
  {
    id: '336',
    title: { en: 'Side hustle ideas for weekends?', zh: '周末有什么副业路子？' },
    content: { en: 'Inflation is killing me. Uber Eats? Dog walking?', zh: '通胀受不了了。送外卖？遛狗？' },
    author: 'Hustler',
    tags: [...WESTERN_TAGS.Life, '💸 Money', '❓ Question', '🛠️ Practical', '💼 Side Hustle', '🚗 Uber', '🐶 Rover', '📉 Inflation', '💰 Extra Cash', '😫 Broke', '🇺🇸 English Content', '📅 Weekend'],
    imageUrl: 'https://picsum.photos/400/300?random=336',
    likes: 410,
  },
  {
    id: '337',
    title: { en: 'Anyone watching "The Bear" season 2?', zh: '有人在看《熊家餐馆》第二季吗？' },
    content: { en: 'The Christmas episode gave me PTSD. Brilliant acting.', zh: '圣诞节那集看我有 PTSD 了。演技炸裂。' },
    author: 'TVJunkie',
    tags: [...WESTERN_TAGS.GenZ, '📺 TV Show', '👍 Recommendation', '🐻 The Bear', '🍳 Cooking', '🎭 Drama', '😰 Stressful', '🏆 Emmy', '🥯 Hulu', '💬 Discussion', '🇺🇸 English Content', '🤯 Mind Blowing'],
    imageUrl: 'https://picsum.photos/400/300?random=337',
    likes: 670,
  },
  {
    id: '338',
    title: { en: 'Scared of AI taking my job', zh: '害怕 AI 抢我饭碗' },
    content: { en: 'I am a copywriter. ChatGPT is getting too good.', zh: '我是文案。ChatGPT 现在太强了。' },
    author: 'WriterBlock',
    tags: [...WESTERN_TAGS.Tech, ...WESTERN_TAGS.Reddit, '😰 Anxiety', '💼 Career', '🤖 ChatGPT', '✍️ Writing', '📉 Layoffs', '🔮 Future', '🆘 Help', '😨 Fear', '🏢 Corporate', '🇺🇸 English Content', '🤖 Automation'],
    imageUrl: 'https://picsum.photos/400/300?random=338',
    likes: 920,
  },
  {
    id: '339',
    title: { en: 'Best sneaker store in SF?', zh: 'SF 哪家球鞋店最好？' },
    content: { en: 'Looking for Jordan 1s. Nice Kicks or somewhere else?', zh: '想买 AJ1。Nice Kicks 还是别的？' },
    author: 'Sneakerhead',
    tags: [...WESTERN_TAGS.GenZ, '💅 Fashion', '🛍️ Shopping', '❓ Question', '👟 Sneakers', '🏀 Jordans', '🌉 San Francisco', '🧢 Streetwear', '🔥 Hypebeast', '🏪 Retail', '🇺🇸 English Content', '👟 Shoes'],
    imageUrl: 'https://picsum.photos/400/300?random=339',
    likes: 130,
  },
  {
    id: '340',
    title: { en: 'Wedding cost breakdown ($50k)', zh: '婚礼花销明细（5万刀）' },
    content: { en: 'Venue was $15k alone. Is this normal??', zh: '光场地就1万5。这正常吗？？' },
    author: 'BrideToBe',
    tags: [...WESTERN_TAGS.Reddit, '💸 Money', '🎉 Party', '📊 Analysis', '💍 Wedding', '👰 Bride', '📉 Expensive', '🤬 Ripoff', '🥂 Event Planning', '💸 Budget', '🇺🇸 USA Culture', '🇺🇸 English Content'],
    tagWeights: { '💍 Wedding': 2.5, '💸 Money': 2.0, '🎉 Party': 0.5 },
    imageUrl: 'https://picsum.photos/400/300?random=340',
    likes: 560,
  },
  {
    id: '341',
    title: { en: 'Meal prep ideas for busy week', zh: '忙碌周的备餐点子' },
    content: { en: 'Chicken, rice, broccoli again. I need variety.', zh: '又是鸡胸肉西兰花。我需要换换口味。' },
    author: 'GymRatCook',
    tags: [...WESTERN_TAGS.Life, '🍱 Foodie', '⚡ Productivity', '❓ Question', '🥦 Healthy', '🍗 Chicken', '💪 Fitness', '🍳 Cooking', '🍱 Meal Prep', '🕒 Time Saving', '🇺🇸 English Content', '🥗 Diet'],
    imageUrl: 'https://picsum.photos/400/300?random=341',
    likes: 340,
  },
  {
    id: '342',
    title: { en: 'Is Prime Day worth it anymore?', zh: 'Prime Day 还值得买吗？' },
    content: { en: 'Feels like they markup prices just to discount them.', zh: '感觉是先提价再打折。' },
    author: 'SkepticShopper',
    tags: [...WESTERN_TAGS.Life, '🛍️ Shopping', '💸 Money', '💬 Discussion', '📦 Amazon', '🏷️ Prime Day', '📉 Scam', '🧐 Skeptical', '🇺🇸 USA Consumerism', '💳 Deals', '🇺🇸 English Content', '🛑 Don\'t Buy'],
    imageUrl: 'https://picsum.photos/400/300?random=342',
    likes: 450,
  },
  {
    id: '343',
    title: { en: 'Learning Spanish on Duolingo', zh: '在多邻国学西班牙语' },
    content: { en: 'Day 100 streak! The owl is threatening my family.', zh: '打卡100天！那只鸟在威胁我的家人。' },
    author: 'LanguageLearner',
    tags: [...WESTERN_TAGS.GenZ, '✨ Motivation', '🤣 Funny', '🦉 Duolingo', '🇪🇸 Spanish', '📚 Learning', '📱 App', '🔥 Streak', '🐦 Meme', '🇺🇸 English Content', '🎓 Education'],
    imageUrl: 'https://picsum.photos/400/300?random=343',
    likes: 890,
  },
  {
    id: '344',
    title: { en: 'Best place for a first date?', zh: '初次约会去哪好？' },
    content: { en: 'Something casual, not dinner. Mini golf? Museum?', zh: '轻松点的，不要吃饭。迷你高尔夫？博物馆？' },
    author: 'DateNight',
    tags: [...WESTERN_TAGS.Life, '💘 Dating', '❓ Question', '⛳ Mini Golf', '🎨 Museum', '🥂 Social', '😬 Nervous', '💡 Advice', '💑 Relationships', '🇺🇸 English Content', '🌃 Night Out'],
    imageUrl: 'https://picsum.photos/400/300?random=344',
    likes: 210,
  },
  {
    id: '345',
    title: { en: 'How to make friends as an adult?', zh: '成年人怎么交朋友？' },
    content: { en: 'Everyone is busy or has kids. I feel lonely.', zh: '大家都很忙或者有娃了。感觉很孤独。' },
    author: 'LonelyMillennial',
    tags: [...WESTERN_TAGS.Reddit, '🥂 Social', '😰 Anxiety', '🆘 Help Needed', '😔 Lonely', '👫 Friendship', '📅 Adulting', '🏙️ City Life', '💬 Discussion', '🇺🇸 English Content', '🫂 Wholesome'],
    tagWeights: { '🥂 Social': 2.5, '👫 Friendship': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=345',
    likes: 1800,
  },
  {
    id: '346',
    title: { en: 'Visiting parents for Thanksgiving', zh: '感恩节回父母家' },
    content: { en: 'Prepare for the "when are you getting married" questions.', zh: '准备好迎接“什么时候结婚”的轰炸了。' },
    author: 'HolidayStress',
    tags: [...WESTERN_TAGS.Life, '😰 Anxiety', '🤣 Funny', '🦃 Thanksgiving', '👨‍👩‍👧‍👦 Family', '💍 Marriage Pressure', '✈️ Travel', '🍽️ Holiday', '🇺🇸 USA Culture', '😖 Awkward', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=346',
    likes: 920,
  },
  {
    id: '347',
    title: { en: 'Got ghosted after 3 dates', zh: '约会三次后被玩消失了' },
    content: { en: 'Thought we had a connection. Modern dating is trash.', zh: '以为我们有感觉的。现代约会就是垃圾。' },
    author: 'GhostedAgain',
    tags: [...WESTERN_TAGS.Reddit, '💘 Dating', '😡 Rant', '🎭 Emotional', '👻 Ghosting', '💔 Heartbreak', '🚮 Trash', '🚩 Red Flag', '📱 Tinder', '👿 Jerk', '🇺🇸 English Content', '😔 Sad'],
    imageUrl: 'https://picsum.photos/400/300?random=347',
    likes: 670,
  },
  {
    id: '348',
    title: { en: 'Best coffee beans for espresso?', zh: '求推荐意式浓缩咖啡豆' },
    content: { en: 'Bought a Breville machine. Need good beans.', zh: '买了台 Breville。求好豆子。' },
    author: 'HomeBarista',
    tags: [...WESTERN_TAGS.Life, '☕ Coffee', '❓ Question', '☕ Espresso', '🏠 Home Cafe', '🛍️ Recommendations', '😋 Taste', '🇺🇸 English Content', '🔌 Breville', '🍵 Beans', '🛠️ Practical'],
    imageUrl: 'https://picsum.photos/400/300?random=348',
    likes: 150,
  },
  {
    id: '349',
    title: { en: 'Thinking of moving to Colorado', zh: '想搬去科罗拉多' },
    content: { en: 'Love skiing and mountains. Is Denver diverse?', zh: '喜欢滑雪和山。丹佛多样性好吗？' },
    author: 'MountainLife',
    tags: [...WESTERN_TAGS.Life, '🌲 Outdoors', '❓ Question', '🏔️ Colorado', '🏙️ Denver', '⛷️ Skiing', '📦 Moving', '🌄 Nature', '💬 Discussion', '☃️ Snow', '🇺🇸 English Content', '✈️ Relocation'],
    imageUrl: 'https://picsum.photos/400/300?random=349',
    likes: 330,
  },
  {
    id: '350',
    title: { en: 'Vintage shopping haul!', zh: '古着店战利品！' },
    content: { en: 'Found a 90s Levis jacket for $20. Steal.', zh: '20刀淘到了90年代的李维斯夹克。赚翻了。' },
    author: 'Thrifter',
    tags: [...WESTERN_TAGS.GenZ, '💅 Fashion', '🛍️ Shopping', '✨ Aesthetic', '🧥 Vintage', '👖 Thrift Flip', '💸 Deal', '♻️ Sustainable', '📸 OOTD', '🧵 Style', '🇺🇸 English Content', '😎 Cool'],
    imageUrl: 'https://picsum.photos/400/300?random=350',
    likes: 560,
  },
  {
    id: '351',
    title: { en: 'Applying for Global Entry', zh: '申请 Global Entry' },
    content: { en: 'Interview slots are fully booked for months. Any hacks?', zh: '面试名额几个月都满了。有技巧吗？' },
    author: 'TravelHacker',
    tags: [...WESTERN_TAGS.Life, '✈️ Travel', '❓ Question', '🛂 Global Entry', '🛂 TSA Pre', '💡 Hacks', '⏳ Waiting', '🇺🇸 Government', '🛠️ Practical', '📅 Appointments', '🇺🇸 English Content', '✈️ Airport'],
    imageUrl: 'https://picsum.photos/400/300?random=351',
    likes: 240,
  },
  {
    id: '352',
    title: { en: 'Does retinol really work?', zh: '视黄醇真的有用吗？' },
    content: { en: 'My skin is peeling. Is this the "purge"?', zh: '我的脸在脱皮。这就是“爆痘期”吗？' },
    author: 'SkincareAddict',
    tags: [...WESTERN_TAGS.Life, '💄 Beauty', '❓ Question', '🧴 Skincare', '🧪 Retinol', '👩‍⚕️ Dermatology', '😰 Side Effects', '✨ Glow Up', '💊 Anti-Aging', '🆘 Advice', '🇺🇸 English Content', '💆‍♀️ Self Care'],
    imageUrl: 'https://picsum.photos/400/300?random=352',
    likes: 410,
  },
  {
    id: '353',
    title: { en: 'Reading challenge: 52 books a year', zh: '阅读挑战：一年52本书' },
    content: { en: 'Currently on book #10. Reading "Dune".', zh: '正在读第10本。《沙丘》。' },
    author: 'BookWorm',
    tags: [...WESTERN_TAGS.GenZ, '📚 Academic', '✨ Motivation', '📖 Books', '🐛 Reading', '🌌 Dune', '🗓️ Challenge', '🤓 Nerd', '📚 Literature', '📈 Progress', '🇺🇸 English Content', '☕ Cozy'],
    imageUrl: 'https://picsum.photos/400/300?random=353',
    likes: 890,
  },
  {
    id: '354',
    title: { en: 'Podcast recommendations?', zh: '求推荐播客' },
    content: { en: 'Like True Crime and Tech. Listened to Serial already.', zh: '喜欢真实犯罪和科技类。听过 Serial 了。' },
    author: 'PodListener',
    tags: [...WESTERN_TAGS.GenZ, '🍿 Entertainment', '❓ Question', '🎧 Podcast', '🕵️‍♀️ True Crime', '💻 Tech', '👂 Listening', '🚗 Commute', '👍 Recommendations', '🇺🇸 English Content', '🎙️ Audio'],
    imageUrl: 'https://picsum.photos/400/300?random=354',
    likes: 120,
  },
  {
    id: '355',
    title: { en: 'Quit caffeine, headache is real', zh: '戒咖啡了，头疼是真的' },
    content: { en: 'Day 2 without coffee. I hate everyone.', zh: '没喝咖啡第二天。我看谁都不顺眼。' },
    author: 'DecafLife',
    tags: [...WESTERN_TAGS.Life, '🏥 Health', '😡 Rant', '🤣 Funny', '☕ Caffeine Withdrawal', '💊 Headache', '👿 Grumpy', '🍵 Detox', '😴 Tired', '😖 Pain', '🇺🇸 English Content', '🩸 Addiction'],
    imageUrl: 'https://picsum.photos/400/300?random=355',
    likes: 350,
  },
  {
    id: '356',
    title: { en: 'Are coding bootcamps a scam?', zh: '编程培训班是骗局吗？' },
    content: { en: 'Cost $20k and no job support. Be careful.', zh: '花了2万刀，不包就业。大家小心。' },
    author: 'BootcampGrad',
    tags: [...WESTERN_TAGS.Tech, ...WESTERN_TAGS.Reddit, '⚠️ Warning', '💸 Money', '💼 Career', '💻 Bootcamp', '🚫 Scam', '📉 Job Market', '🎓 Education', '🤬 Regret', '🇺🇸 English Content', '🤥 Lies'],
    imageUrl: 'https://picsum.photos/400/300?random=356',
    likes: 1100,
  },
  {
    id: '357',
    title: { en: 'Working from a cafe: Etiquette?', zh: '咖啡店办公礼仪？' },
    content: { en: 'How long can I stay with one coffee? 2 hours?', zh: '一杯咖啡能坐多久？2小时？' },
    author: 'RemoteLife',
    tags: [...WESTERN_TAGS.Life, '☕ Coffee', '❓ Question', '💬 Discussion', '💻 Remote Work', '🧘 Etiquette', '⏳ Time Limit', '👨‍💻 Nomad', '🏢 Third Place', '🇺🇸 English Content', '🤔 Wondering'],
    imageUrl: 'https://picsum.photos/400/300?random=357',
    likes: 220,
  },
  {
    id: '358',
    title: { en: 'NBA Playoffs predictions', zh: 'NBA 季后赛预测' },
    content: { en: 'Celtics looking strong. Can anyone stop them?', zh: '凯尔特人很强。有人能拦住他们吗？' },
    author: 'HoopsFan',
    tags: [...WESTERN_TAGS.Life, '🏀 Sports', '💬 Discussion', '🏀 NBA', '🏆 Playoffs', '🍀 Celtics', '🔮 Predictions', '⚔️ Competition', '⛹️‍♂️ Basketball', '🇺🇸 English Content', '🏟️ Stadium'],
    tagWeights: { '🏀 Sports': 2.5, '🏀 NBA': 2.5, '💬 Discussion': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=358',
    likes: 450,
  },
  {
    id: '359',
    title: { en: 'Best budget airline?', zh: '最好的廉价航空？' },
    content: { en: 'Spirit vs Frontier? Or just pay for Southwest?', zh: 'Spirit 还是 Frontier？还是直接买 Southwest？' },
    author: 'BudgetTravel',
    tags: [...WESTERN_TAGS.Life, '✈️ Travel', '💸 Money', '❓ Question', '✈️ Airlines', '👎 Spirit Airlines', '🥜 Peanuts', '💺 Economy', '🤬 Discomfort', '🇺🇸 English Content', '🤑 Cheap'],
    imageUrl: 'https://picsum.photos/400/300?random=359',
    likes: 180,
  },
  {
    id: '360',
    title: { en: 'How to ask for a raise?', zh: '怎么提涨薪？' },
    content: { en: 'Been here 2 years, exceeded targets. Nervous.', zh: '干了两年，超额完成指标。好紧张。' },
    author: 'SalaryNeg',
    tags: [...WESTERN_TAGS.Tech, ...WESTERN_TAGS.Reddit, '💼 Career Advice', '💸 Money', '❓ Question', '💰 Raise', '🗣️ Negotiation', '👔 Corporate', '😰 Nervous', '📈 Promotion', '🇺🇸 English Content', '💪 Courage'],
    imageUrl: 'https://picsum.photos/400/300?random=360',
    likes: 670,
  },
  {
    id: '361',
    title: { en: 'Meal kit delivery services reviews', zh: '生鲜配送服务测评' },
    content: { en: 'HelloFresh vs Blue Apron. Portion sizes are small.', zh: 'HelloFresh 对比 Blue Apron。分量有点小。' },
    author: 'LazyCook',
    tags: [...WESTERN_TAGS.Life, '🍱 Foodie', '📝 Review', '📦 HelloFresh', '🍳 Cooking', '🍽️ Dinner', '👎 Small Portions', '💸 Subscription', '❓ Question', '🇺🇸 English Content', '🥘 Meal Kit'],
    imageUrl: 'https://picsum.photos/400/300?random=361',
    likes: 210,
  },
  {
    id: '362',
    title: { en: 'Did anyone see the meteor shower?', zh: '有人看到流星雨了吗？' },
    content: { en: 'Drove to Joshua Tree. Absolutely stunning.', zh: '开车去了 Joshua Tree。美哭了。' },
    author: 'StarGazer',
    tags: [...WESTERN_TAGS.Life, '🌿 Nature', '📸 Photography', '✨ Aesthetic', '🌠 Meteor Shower', '🌌 Space', '🏜️ Joshua Tree', '😍 Beautiful', '🌃 Night Sky', '🇺🇸 English Content', '🚙 Roadtrip'],
    imageUrl: 'https://picsum.photos/400/300?random=362',
    likes: 1200,
  },
  {
    id: '363',
    title: { en: 'Best burger in LA?', zh: '洛杉矶最好吃的汉堡？' },
    content: { en: 'In-N-Out is classic, but have you tried Shake Shack?', zh: 'In-N-Out 是经典，但是你试过 Shake Shack 吗？' },
    author: 'BurgerKing',
    tags: [...WESTERN_TAGS.Life, '🍱 Foodie', '⚔️ Debate', '🍔 Burgers', '🌴 Los Angeles', '🍟 In-N-Out', '🏙️ Shake Shack', '❓ Question', '🍽️ Fast Food', '🇺🇸 English Content', '😋 Tasty'],
    imageUrl: 'https://picsum.photos/400/300?random=363',
    likes: 560,
  },
  {
    id: '364',
    title: { en: 'How to deal with burnout?', zh: '怎么应对职业倦怠？' },
    content: { en: 'I dread opening my laptop every morning.', zh: '每天早上都不想打开电脑。' },
    author: 'BurnedOutDev',
    tags: [...WESTERN_TAGS.Tech, ...WESTERN_TAGS.Reddit, '🧘 Mental Health', '💼 Career', '🆘 Help Needed', '🔥 Burnout', '😩 Exhaustion', '📉 Productivity', '👔 Corporate', '😰 Anxiety', '🇺🇸 English Content', '😢 Sad'],
    tagWeights: { '🔥 Burnout': 2.5, '🧘 Mental Health': 2.0, '💼 Career': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=364',
    likes: 900,
  },
  {
    id: '365',
    title: { en: 'Buying a house in 2024 seems impossible', zh: '2024年买房感觉不可能' },
    content: { en: '7% interest rates and high prices. I give up.', zh: '7%的利率加上高房价。我放弃了。' },
    author: 'ForeverRenter',
    tags: [...WESTERN_TAGS.Reddit, '🏠 Renting', '💸 Money', '😰 Anxiety', '🏡 Real Estate', '📉 Economy', '👴 Boomers', '😞 Hopeless', '🏦 Mortgage', '📈 Interest Rates', '🇺🇸 English Content', '🏘️ Housing Crisis'],
    imageUrl: 'https://picsum.photos/400/300?random=365',
    likes: 2500,
  },
  {
    id: '366',
    title: { en: 'Anyone playing Elden Ring DLC?', zh: '有人在玩艾尔登法环 DLC 吗？' },
    content: { en: 'The difficulty spike is real. I keep dying.', zh: '难度真的激增。我一直在死。' },
    author: 'GamerGuy',
    tags: [...WESTERN_TAGS.GenZ, '🎮 Gaming', '🔥 Hardcore', '💬 Discussion', '💍 Elden Ring', '💀 You Died', '⚔️ RPG', '😓 Difficult', '👾 Video Games', '🇺🇸 English Content', '🤯 Intense'],
    tagWeights: { '🎮 Gaming': 2.5, '💍 Elden Ring': 2.0, '🔥 Hardcore': 1.5, '💬 Discussion': 0.5 },
    imageUrl: 'https://picsum.photos/400/300?random=366',
    likes: 780,
  },
  {
    id: '367',
    title: { en: 'Best credit card for travel points?', zh: '最好的旅行积分信用卡？' },
    content: { en: 'Chase Sapphire Reserve vs Amex Platinum?', zh: 'Chase Sapphire Reserve 还是 Amex Platinum？' },
    author: 'PointsGuyFan',
    tags: [...WESTERN_TAGS.Life, '💸 Money', '✈️ Travel', '❓ Question', '💳 Credit Cards', '🏦 Chase', '💎 Amex', '🎁 Rewards', '🧠 Strategy', '🇺🇸 USA Finance', '🇺🇸 English Content', '✈️ Points'],
    imageUrl: 'https://picsum.photos/400/300?random=367',
    likes: 410,
  },
  {
    id: '368',
    title: { en: 'Is 28 too old to learn coding?', zh: '28岁学编程太晚了吗？' },
    content: { en: 'Want to switch careers. Be honest.', zh: '想转行。请说实话。' },
    author: 'LateBloomer',
    tags: [...WESTERN_TAGS.Tech, ...WESTERN_TAGS.Reddit, '🔄 Career Change', '❓ Question', '⌨️ Coding', '👴 Ageism', '✨ Inspirational', '😨 Fear', '🏫 Learning', '🎓 Bootcamp', '🇺🇸 English Content', '🙌 Support'],
    imageUrl: 'https://picsum.photos/400/300?random=368',
    likes: 670,
  },
  {
    id: '369',
    title: { en: 'Trader Joe\'s unionizing efforts', zh: 'Trader Joe\'s 的工会化进程' },
    content: { en: 'Support the workers! Local store voted yes.', zh: '支持工人！本地店投票通过了。' },
    author: 'UnionStrong',
    tags: [...WESTERN_TAGS.Reddit, '📰 News', '✨ Inspirational', '🛒 Trader Joes', '✊ Unions', '👷 Workers Rights', '🗳️ Politics', '🇺🇸 USA', '🙌 Solidarity', '💬 Discussion', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=369',
    likes: 1200,
  },
  {
    id: '370',
    title: { en: 'Why does Zoom drain my battery so fast?', zh: '为什么 Zoom 这么费电？' },
    content: { en: 'MacBook Pro lasts 2 hours on video calls.', zh: 'MacBook Pro 开视频只能撑2小时。' },
    author: 'TechSupport',
    tags: [...WESTERN_TAGS.Tech, '💻 Tech', '😡 Rant', '📹 Zoom', '🔋 Battery Life', '🍎 Apple', '❓ Question', '🛠️ Bug', '📉 Performance', '👨‍💻 Work From Home', '🇺🇸 English Content'],
    imageUrl: 'https://picsum.photos/400/300?random=370',
    likes: 150,
  },
  {
    id: '371',
    title: { en: 'Solo traveling as a woman', zh: '女生独自旅行' },
    content: { en: 'Tips for safety? Thinking of going to Japan.', zh: '安全建议？想去日本。' },
    author: 'SoloTraveler',
    tags: [...WESTERN_TAGS.Life, '✈️ Travel', '❓ Question', '👩 Female Perspective', '🛡️ Safety', '🌏 Japan', '🎒 Backpacking', '💪 Empowerment', '🔦 Tips', '🇺🇸 English Content', '💃 Solo Trip'],
    tagWeights: { '✈️ Travel': 2.0, '👩 Female Perspective': 2.0, '🛡️ Safety': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=371',
    likes: 890,
  },
  {
    id: '372',
    title: { en: 'Best white elephant gift under $25?', zh: '25刀以下最好的白象交换礼物？' },
    content: { en: 'Needs to be funny but useful. Office party.', zh: '要好笑但实用。办公室派对。' },
    author: 'PartyPlanner',
    tags: [...WESTERN_TAGS.GenZ, '🎉 Party', '🛍️ Shopping', '❓ Question', '🎁 Gift Ideas', '🎄 Christmas', '🐘 White Elephant', '🏢 Office', '💸 Cheap', '🤣 Funny', '🇺🇸 English Content', '💡 Ideas'],
    imageUrl: 'https://picsum.photos/400/300?random=372',
    likes: 220,
  },
  {
    id: '373',
    title: { en: 'I miss Blockbuster', zh: '我想念 Blockbuster' },
    content: { en: 'Streaming is convenient but browsing shelves was a vibe.', zh: '流媒体很方便，但逛货架很有感觉。' },
    author: 'Nostalgia90s',
    tags: [...WESTERN_TAGS.GenZ, '🍿 Entertainment', '📖 Storytime', '🎭 Emotional', '📼 Blockbuster', '📼 Nostalgia', '📅 90s Kid', '📺 Movies', '⏪ Retro', '😔 Sad', '🇺🇸 English Content', '🎞️ Memory Lane'],
    imageUrl: 'https://picsum.photos/400/300?random=373',
    likes: 1500,
  },
  {
    id: '374',
    title: { en: 'How to clean white Converse?', zh: '怎么洗白色匡威？' },
    content: { en: 'They are looking grey. Bleach?', zh: '发灰了。漂白水？' },
    author: 'CleanKicks',
    tags: [...WESTERN_TAGS.Life, '💅 Fashion', '🛠️ Practical', '❓ Question', '👟 Shoes', '👟 Converse', '🧼 Cleaning', '⚪ White', '👟 Sneakers', '🆘 Help', '🇺🇸 English Content', '👟 Footwear'],
    imageUrl: 'https://picsum.photos/400/300?random=374',
    likes: 90,
  },
  {
    id: '375',
    title: { en: 'Why are concert tickets so expensive?', zh: '为什么演唱会门票这么贵？' },
    content: { en: '$400 for nosebleeds? I\'ll watch on YouTube.', zh: '山顶票都要400？我在 YouTube 上看算了。' },
    author: 'BrokeFan',
    tags: [...WESTERN_TAGS.GenZ, '🎶 Music', '💸 Money', '😡 Rant', '🎫 Tickets', '📉 Inflation', '💸 Greed', '🏟️ Concerts', '🤬 Ticketmaster', '👎 Negative', '🇺🇸 English Content', '🎤 Live Music'],
    imageUrl: 'https://picsum.photos/400/300?random=375',
    likes: 670,
  },
  {
    id: '376',
    title: { en: 'Learning to play guitar', zh: '学吉他' },
    content: { en: 'Fingers hurt so much. When do calluses form?', zh: '手指疼死了。什么时候长茧？' },
    author: 'MusicNewbie',
    tags: [...WESTERN_TAGS.GenZ, '🎶 Music', '❓ Question', '🎸 Guitar', '🎼 Hobby', '😖 Pain', '✨ Practice', '🧠 Learning', '🤘 Rock', '🇺🇸 English Content', '🎵 Instrument'],
    imageUrl: 'https://picsum.photos/400/300?random=376',
    likes: 180,
  },
  {
    id: '377',
    title: { en: 'Best yoga studio in Mission?', zh: 'Mission 区最好的瑜伽馆？' },
    content: { en: 'Looking for vinyasa flow. Not too hot.', zh: '找流瑜伽。不要太热的。' },
    author: 'YogiLife',
    tags: [...WESTERN_TAGS.Life, '🧘 Mental Health', '🏋️ Gym', '❓ Question', '🧘‍♀️ Yoga', '🌉 San Francisco', '🌉 Mission District', '🕯️ Zen', '💪 Fitness', '🧘 Vinyasa', '🇺🇸 English Content', '☮️ Peace'],
    imageUrl: 'https://picsum.photos/400/300?random=377',
    likes: 110,
  },
  {
    id: '378',
    title: { en: 'My plant is dying', zh: '我的植物快死了' },
    content: { en: 'Leaves are turning yellow. Too much water?', zh: '叶子黄了。浇水太多？' },
    author: 'PlantMom',
    tags: [...WESTERN_TAGS.Life, '🌿 Nature', '🆘 Help Needed', '🪴 Plants', '🥀 Gardening', '🏠 Indoor Plants', '❓ Question', '😢 Sad', '🌸 Flowers', '🇺🇸 English Content', '🍃 Botany'],
    imageUrl: 'https://picsum.photos/400/300?random=378',
    likes: 240,
  },
  {
    id: '379',
    title: { en: 'Spotify Wrapped is embarrassing', zh: 'Spotify 年度总结太尴尬了' },
    content: { en: 'Top artist is Glee Cast. Don\'t judge me.', zh: '年度艺人是 Glee Cast。别喷我。' },
    author: 'MusicFan',
    tags: [...WESTERN_TAGS.GenZ, '🎶 Music', '🤣 Funny', '🎧 Spotify', '📅 Wrapped', '😳 Embarrassing', '🎤 Glee', '🤡 Guilty Pleasure', '💬 Discussion', '🇺🇸 English Content', '📊 Data'],
    imageUrl: 'https://picsum.photos/400/300?random=379',
    likes: 550,
  },
  {
    id: '380',
    title: { en: 'Is air fryer worth the hype?', zh: '空气炸锅值得买吗？' },
    content: { en: 'Limited counter space. Does it taste like fried food?', zh: '台面空间有限。吃起来像油炸的吗？' },
    author: 'CookingNoob',
    tags: [...WESTERN_TAGS.Life, '🍱 Foodie', '❓ Question', '🍳 Cooking', '🍟 Air Fryer', '🏠 Appliances', '🗑️ Kitchen', '🤔 Skeptical', '🍿 Snacks', '🇺🇸 English Content', '🍔 Food'],
    imageUrl: 'https://picsum.photos/400/300?random=380',
    likes: 410,
  },
  {
    id: '381',
    title: { en: 'Neighbor stole my package', zh: '邻居偷了我的快递' },
    content: { en: 'Caught on Ring camera. Confront or call police?', zh: 'Ring 监控拍到了。对质还是报警？' },
    author: 'PackageThiefvictim',
    tags: [...WESTERN_TAGS.Reddit, '🏠 Renting', '⚔️ Conflict', '😰 Scary', '📦 Theft', '📹 Ring Camera', '👮‍♂️ Police', '🤬 Rage', '🆘 Advice', '🚪 Neighbors', '🇺🇸 English Content', '🚓 Crime'],
    imageUrl: 'https://picsum.photos/400/300?random=381',
    likes: 890,
  },
  {
    id: '382',
    title: { en: 'Best ramen in NYC?', zh: '纽约最好吃的拉面？' },
    content: { en: 'Ichiran is overrated. Give me hidden gems.', zh: '一兰过誉了。求推荐宝藏店。' },
    author: 'RamenHunter',
    tags: [...WESTERN_TAGS.Life, '🍱 Foodie', '❓ Question', '🍜 Ramen', '🗽 NYC', '🍎 New York', '😋 Delicious', '🥢 Noodles', '🇯🇵 Japanese Food', '💎 Hidden Gem', '🇺🇸 English Content', '🍽️ Dinner'],
    imageUrl: 'https://picsum.photos/400/300?random=382',
    likes: 330,
  },
  {
    id: '383',
    title: { en: 'Should I get a MBA or Masters in CS?', zh: '读 MBA 还是 CS 硕士？' },
    content: { en: 'Want to move into product management.', zh: '想转产品经理。' },
    author: 'GradSchoolDilemma',
    tags: [...WESTERN_TAGS.Tech, '💼 Career Advice', '❓ Question', '🎓 Masters', '🎓 MBA', '📊 Product Management', '🤔 Dilemma', '📉 ROI', '🎓 Education', '🇺🇸 English Content', '👔 Corporate'],
    tagWeights: { '💼 Career Advice': 2.0, '🎓 Masters': 1.5, '🎓 MBA': 1.5, '📊 Product Management': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=383',
    likes: 210,
  },
  {
    id: '384',
    title: { en: 'Running my first marathon', zh: '跑人生第一个马拉松' },
    content: { en: 'Training is brutal. Knees hurt. Send motivation.', zh: '训练太残酷了。膝盖疼。求鼓励。' },
    author: 'Runner5k',
    tags: [...WESTERN_TAGS.Life, '🏋️ Gym', '✨ Motivation', '✨ Inspirational', '🏃 Running', '🏅 Marathon', '👟 Fitness', '🦵 Pain', '🏁 Goal', '🏥 Health', '🇺🇸 English Content', '🔥 Training'],
    imageUrl: 'https://picsum.photos/400/300?random=384',
    likes: 670,
  },
  {
    id: '385',
    title: { en: 'Why is dating so expensive?', zh: '为什么约会这么贵？' },
    content: { en: 'Dinner and drinks = $100. I\'m going broke.', zh: '吃饭喝酒100刀。我要破产了。' },
    author: 'BrokeDate',
    tags: [...WESTERN_TAGS.Reddit, '💘 Dating', '💸 Money', '😡 Rant', '🍸 Drinks', '🍽️ Dinner', '📉 Inflation', '💸 Expensive', '👬 Single Life', '😩 Broke', '🇺🇸 English Content', '👎 Complaints'],
    imageUrl: 'https://picsum.photos/400/300?random=385',
    likes: 450,
  },
  {
    id: '386',
    title: { en: 'My cat is my best friend', zh: '猫是我最好的朋友' },
    content: { en: 'People are disappointing. Cats are loyal.', zh: '人类让人失望。猫很忠诚。' },
    author: 'CatLady',
    tags: [...WESTERN_TAGS.Reddit, '🐱 Cat', '🐾 Pets', '🎭 Emotional', '❤️ Love', '🧘 Loneliness', '🏠 Home', '🐈 Feline', '🤗 Hugs', '🇺🇸 English Content', '😺 Cute', '🥺 Wholesome'],
    imageUrl: 'https://picsum.photos/400/300?random=386',
    likes: 1200,
  },
  {
    id: '387',
    title: { en: 'Best place to donate clothes?', zh: '旧衣服捐哪好？' },
    content: { en: 'Goodwill resells for profit. Any shelters?', zh: 'Goodwill 转手赚钱。有避难所推荐吗？' },
    author: 'Donor123',
    tags: [...WESTERN_TAGS.Life, '😇 Good Deed', '❓ Question', '👕 Clothes', '♻️ Donation', '🏙️ Community', '🚮 Declutter', '🏚️ Shelter', '💡 Advice', '🧹 Cleaning', '🇺🇸 English Content', '♻️ Recycling'],
    imageUrl: 'https://picsum.photos/400/300?random=387',
    likes: 180,
  },
  {
    id: '388',
    title: { en: 'Learning to code at 40', zh: '40岁学编程' },
    content: { en: 'It\'s never too late. Building my first app.', zh: '永远不晚。正在做第一个 App。' },
    author: 'OldCoder',
    tags: [...WESTERN_TAGS.Tech, ...WESTERN_TAGS.Reddit, '✨ Inspirational', '✨ Motivation', '⌨️ Coding', '👴 Age', '🔄 Career Change', '📱 App Dev', '👨‍💻 Developer', '💪 Grit', '🎓 Learning', '🇺🇸 English Content', '🧠 Growth'],
    imageUrl: 'https://picsum.photos/400/300?random=388',
    likes: 3100,
  },
  {
    id: '389',
    title: { en: 'Favorite board games?', zh: '最喜欢的桌游？' },
    content: { en: 'Catan is getting old. Need something new.', zh: '卡坦岛玩腻了。来点新的。' },
    author: 'BoardGamer',
    tags: [...WESTERN_TAGS.GenZ, '🎮 Gaming', '🥂 Social', '❓ Question', '🎲 Board Games', '🤓 Geek', '🃏 Cards', '🏠 House Party', '🤔 Strategy', '🇺🇸 English Content', '🎲 Catan', '🎲 Monopoly'],
    tagWeights: { '🎮 Gaming': 2.0, '🎲 Board Games': 2.0, '🥂 Social': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=389',
    likes: 240,
  },
  {
    id: '390',
    title: { en: 'I saw a bear in Tahoe!', zh: '在 Tahoe 看到熊了！' },
    content: { en: 'It opened my car door. Lock your doors people.', zh: '它打开了我的车门。大家锁好门。' },
    author: 'BearWitness',
    tags: [...WESTERN_TAGS.Life, '🌲 Outdoors', '😰 Scary', '⚠️ Warning', '🐻 Bear', '🏞️ Tahoe', '🚗 Cars', '🌲 Nature', '📸 Wildlife', '😱 Shocking', '🇺🇸 English Content', '⛺ Camping'],
    imageUrl: 'https://picsum.photos/400/300?random=390',
    likes: 1500,
  },
  {
    id: '391',
    title: { en: 'Best sunscreen for face?', zh: '最好的面部防晒？' },
    content: { en: 'No white cast please. Supergoop dupe?', zh: '不要假白。Supergoop 平替？' },
    author: 'SkincareFan',
    tags: [...WESTERN_TAGS.GenZ, '💄 Beauty', '❓ Question', '☀️ Sunscreen', '🧴 Skincare', '🏖️ Beach', '😎 Summer', '💊 Dermatology', '💰 Budget', '🧖‍♀️ Face', '🇺🇸 English Content', '✨ Glow'],
    imageUrl: 'https://picsum.photos/400/300?random=391',
    likes: 330,
  },
  {
    id: '392',
    title: { en: 'My flight got cancelled', zh: '航班取消了' },
    content: { en: 'Stuck in Denver airport overnight. Sleeping on floor.', zh: '在丹佛机场过夜。睡地板。' },
    author: 'StrandedTraveler',
    tags: [...WESTERN_TAGS.Reddit, '✈️ Travel', '😡 Rant', '😰 Anxiety', '✈️ Airlines', '🏙️ Denver', '😴 Sleep', '😫 Exhausted', '🤬 Angry', '🏚️ Stranded', '🇺🇸 English Content', '🎫 Rebooking'],
    imageUrl: 'https://picsum.photos/400/300?random=392',
    likes: 890,
  },
  {
    id: '393',
    title: { en: 'How to make iced coffee at home?', zh: '在家怎么做冰咖啡？' },
    content: { en: 'Cold brew or just ice hot coffee?', zh: '冷萃还是热咖啡加冰？' },
    author: 'CoffeeLover',
    tags: [...WESTERN_TAGS.Life, '☕ Coffee', '❓ Question', '🧊 Iced Coffee', '🏠 Home Cafe', '🥄 Recipe', '☕ Brewing', '😋 Refreshing', '☀️ Summer', '🍵 Barista', '🇺🇸 English Content', '🥤 Drink'],
    imageUrl: 'https://picsum.photos/400/300?random=393',
    likes: 210,
  },
  {
    id: '394',
    title: { en: 'Anyone else watch Formula 1?', zh: '有人看 F1 吗？' },
    content: { en: 'Verstappen is unstoppable. Boring season.', zh: '维斯塔潘势不可挡。无聊的赛季。' },
    author: 'F1Fan',
    tags: [...WESTERN_TAGS.Life, '🏀 Sports', '🏎️ Cars', '💬 Discussion', '🏁 Formula 1', '🏎️ Racing', '🇳🇱 Verstappen', '💤 Boring', '🌍 International', '🏆 Championship', '🇺🇸 English Content', '📺 TV'],
    imageUrl: 'https://picsum.photos/400/300?random=394',
    likes: 560,
  },
  {
    id: '395',
    title: { en: 'Best tacos in Austin?', zh: '奥斯汀最好的 Tacos？' },
    content: { en: 'Torchy\'s is overrated. Where do locals go?', zh: 'Torchy\'s 过誉了。本地人去哪？' },
    author: 'AustinEats',
    tags: [...WESTERN_TAGS.Life, '🍱 Foodie', '❓ Question', '🌮 Tacos', '🤠 Austin', '🌵 Texas', '🌶️ Spicy', '🍽️ Dinner', '🗺️ Local Tips', '🤤 Hungry', '🇺🇸 English Content', '👎 Overrated'],
    imageUrl: 'https://picsum.photos/400/300?random=395',
    likes: 180,
  },
  {
    id: '396',
    title: { en: 'Remote work visa countries?', zh: '远程办公签证国家？' },
    content: { en: 'Portugal D7 or Spain? Looking for low tax.', zh: '葡萄牙 D7 还是西班牙？找低税的。' },
    author: 'NomadLife',
    tags: [...WESTERN_TAGS.Reddit, '✈️ Travel', '🛂 Visa', '❓ Question', '💻 Digital Nomad', '🇵🇹 Portugal', '🇪🇸 Spain', '💸 Taxes', '🌍 Europe', '🏠 Relocation', '🗺️ Lifestyle', '🇺🇸 English Content', '💼 Work'],
    imageUrl: 'https://picsum.photos/400/300?random=396',
    likes: 670,
  },
  {
    id: '397',
    title: { en: 'My kid won\'t eat vegetables', zh: '我家娃不吃蔬菜' },
    content: { en: 'Tried hiding them in smoothies. He knows.', zh: '试过藏在奶昔里。他知道。' },
    author: 'ParentStruggle',
    tags: [...WESTERN_TAGS.Reddit, '👶 Parenting', '🆘 Advice Needed', '🤣 Funny', '🥦 Vegetables', '🧒 Kids', '🍽️ Eating', '😖 Picky Eater', '🥤 Smoothies', '🥦 Health', '🇺🇸 English Content', '😫 Frustrated'],
    imageUrl: 'https://picsum.photos/400/300?random=397',
    likes: 420,
  },
  {
    id: '398',
    title: { en: 'Best horror movies on Netflix?', zh: 'Netflix 最好的恐怖片？' },
    content: { en: 'Scare me. I\'ve seen everything.', zh: '吓死我。我都看遍了。' },
    author: 'HorrorFan',
    tags: [...WESTERN_TAGS.GenZ, '🍿 Entertainment', '👍 Recommendation', '👻 Horror', '📺 Netflix', '😱 Scary', '🎥 Movies', '🍿 Popcorn', '🎃 Halloween', '💀 Spooky', '🇺🇸 English Content', '👀 Watching'],
    imageUrl: 'https://picsum.photos/400/300?random=398',
    likes: 310,
  },
  {
    id: '399',
    title: { en: 'I love California weather', zh: '我爱加州的天气' },
    content: { en: '70 degrees and sunny. Can\'t complain.', zh: '20度晴天。无可抱怨。' },
    author: 'CalLife',
    tags: [...WESTERN_TAGS.Life, '🌿 Nature', '✨ Inspirational', '☀️ California', '😎 Sunny', '🏖️ Beach', '😌 Relaxing', '🌡️ Weather', '🌉 West Coast', '❤️ Love', '🇺🇸 English Content', '😊 Happy'],
    imageUrl: 'https://picsum.photos/400/300?random=399',
    likes: 1200,
  }
];