import { Post, UserProfile } from './types';

// Helper to get common tags easily with Emojis for better UX
// This serves as the "Schema" or "Registry" for the application.
const TAGS = {
  // Topics
  CS: ['💻 Computer Science', '⌨️ Coding', '💼 Tech Career', '🛠️ Software Engineering', '🌉 Silicon Valley', '🎓 Internship'],
  AI: ['🤖 AI/ML', '🧠 Deep Learning', '💬 LLM', '📊 Data Science', '🐍 Python', '📐 Math Heavy'],
  School: ['🏫 Community College', '🔄 UC Transfer', '🐻 UC Berkeley', '📝 GPA', '📚 Academic', '💡 Study Tips'],
  English: ['🇺🇸 English Learning', '🗣️ TOEFL/IELTS', '💬 ESL', '🚧 Language Barrier', '✍️ Writing'],
  Life: ['🌉 Bay Area', '🏠 Renting', '👯 Roommate', '💸 Cost of Living', '🥂 Social Life', '💘 Dating', '🧘 Mental Health'],
  Fun: ['🎮 Gaming', '🎉 Party', '🌙 Nightlife', '🍿 Entertainment', '💅 Fashion', '🍱 Foodie', '🗣️ Gossip'],
  
  // New "Vibe" categories for western content
  Reddit: ['💬 Discussion', '❓ Question', '😡 Rant', '📖 Storytime', '🆘 Advice Needed', '🟢 Green Flag', '🚩 Red Flag', '🤬 AITA', '🔥 Hot Take', '🤷‍♂️ Unpopular Opinion'],
  GenZ: ['💀 Dead', '✨ Vibe', '🧢 Cap', '🗣️ Real Talk', '😭 Crying', '🤡 Clown World', '💅 Slay', '🤪 Delulu'],

  // Attributes (Crucial for filtering)
  Difficulty: ['🚦 Beginner Friendly', '🧠 Advanced', '🔥 Hardcore', '📖 Theory', '🛠️ Practical', '👶 Noob Friendly'],
  Tone: ['😡 Rant', '😰 Anxiety', '🎭 Emotional', '😐 Serious', '📘 Guide', '📖 Storytime', '✨ Inspirational', '🎣 Clickbait', '😏 Sarcastic', '🤔 Humblebrag'],
  Language: ['🇨🇳 Chinese Content', '🇺🇸 English Content', '🌐 Chinglish'],
  Audience: ['🎓 Students', '💼 Professionals', '🎓 New Grads', '🌏 International Students', '🐣 Freshman', '🔄 Transfer Student', '🌟 Elite Students', '🔬 PhD Hopefuls']
};

// Flatten all tags into a single array for the LLM to use as a reference vocabulary.
// This ensures the LLM knows exactly which tags are valid in our system.
export const ALL_TAGS = Object.values(TAGS).flat();

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'user_001',
  name: 'Alex Chen',
  bio: 'Community College Student aiming for UCB CS transfer. Interested in AI and Research.',
  interests: [
    { tag: '🏫 Community College', weight: 10 },
    { tag: '🔄 UC Transfer', weight: 15 },
    { tag: '🔬 Research', weight: 12 },
    { tag: '🤖 AI/ML', weight: 8 },
    { tag: '💻 Computer Science', weight: 8 },
    { tag: '📚 Academic', weight: 5 }
  ],
  dislikes: [], 
};

export const MOCK_POSTS: Post[] = [
  // --- EXISTING POSTS (1-39) ---
  {
    id: '1',
    title: { en: 'GPA 2.0 to UCB? The Secret Path No One Knows', zh: 'GPA 2.0 也能上 UCB？这个冷门路径没人知道！' },
    content: { en: 'As long as you choose the right classes and use these special hacks, even low grades can make it to a top school...', zh: '只要选对课，加上这几个特殊操作，低分也能逆袭名校...' },
    author: 'StudyAbroadHelper',
    tags: [...TAGS.School, '📉 Low GPA', '🏆 Success Story', '🎣 Clickbait', '📘 Guide', '🇨🇳 Chinese Content', '✨ Inspirational', '🤫 Secret Hack'],
    imageUrl: 'https://picsum.photos/400/300?random=1',
    likes: 120,
  },
  {
    id: '2',
    title: { en: 'Bad English? How to Get into Ivy League with 60 Points', zh: '英语基础差？60分也能逆袭藤校的秘密' },
    content: { en: 'Don\'t let language scores be your stumbling block. See how he did it...', zh: '别让语言成绩成为你的绊脚石，看看他是如何做到的...' },
    author: 'TestPrepGuru',
    tags: [...TAGS.English, ...TAGS.School, '🚦 Beginner Friendly', '📉 Low GPA', '📝 Test Prep', '🇨🇳 Chinese Content', '📘 Guide', '📢 Marketing'],
    imageUrl: 'https://picsum.photos/400/300?random=2',
    likes: 45,
  },
  {
    id: '3',
    title: { en: 'Building an AI Recommendation System from Scratch', zh: '如何从零开始做一个 AI 推荐系统独立项目' },
    content: { en: 'Detailed breakdown of collaborative filtering and deep learning model implementation...', zh: '本文详细拆解了推荐系统的协同过滤与深度学习模型实现...' },
    author: 'TechLead Jay',
    tags: [...TAGS.CS, ...TAGS.AI, '💻 Project', '📂 Portfolio', '🧠 Advanced', '🔥 Hardcore', '🇨🇳 Chinese Content', '📚 Tutorial', '🏗️ System Design', '⚙️ Backend'],
    imageUrl: 'https://picsum.photos/400/300?random=3',
    likes: 890,
  },
  {
    id: '4',
    title: { en: '2025 CC Transfer to UC System Guide (TAG Details)', zh: '2025年 CC 转学 UC 系统全攻略（含Tag协议细节）' },
    content: { en: 'Detailed interpretation of the latest transfer policies and how to use Assist.org correctly...', zh: '详细解读最新转学政策，Assist.org 的正确用法...' },
    author: 'TransferWiki',
    tags: [...TAGS.School, '📜 Policy', '🤝 Tag Agreement', '😐 Serious', '📘 Guide', '📖 Must Read', '🇨🇳 Chinese Content', '📅 Timeline', '📝 Application'],
    imageUrl: 'https://picsum.photos/400/300?random=4',
    likes: 1200,
  },
  {
    id: '5',
    title: { en: 'What Undergraduate Research Do UCB Professors Like?', zh: 'UCB 教授最喜欢什么样的本科科研经历？' },
    content: { en: 'Interviewed EECS admissions officers, they value these three abilities...', zh: '采访了 EECS 系的招生官，他们看重这三点能力...' },
    author: 'BerkeleySenior',
    tags: [...TAGS.School, ...TAGS.CS, '🔬 Research', '👨‍🏫 Professor', '🎤 Interview', '🤫 Insider Info', '😐 Serious', '🧠 Advanced', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=5',
    likes: 560,
  },
  {
    id: '6',
    title: { en: 'Transformer Architecture Explained with PyTorch', zh: 'Transformer 架构详解与 PyTorch 实现' },
    content: { en: 'Step-by-step guide to writing Attention mechanisms, suitable for beginners...', zh: '手把手教你写 Attention 机制，适合新手入门...' },
    author: 'AI_Study_Group',
    tags: [...TAGS.AI, ...TAGS.CS, '📖 Theory', '📐 Math Heavy', '💻 Code Implementation', '🔥 Pytorch', '🔥 Hardcore', '🇨🇳 Chinese Content', '📚 Academic'],
    imageUrl: 'https://picsum.photos/400/300?random=7',
    likes: 430,
  },
  {
    id: '7',
    title: { en: 'LeetCode Top 100 Solution Guide', zh: 'LeetCode 刷题清单：Top 100 题解' },
    content: { en: 'Summary of most frequent interview questions from Facebook and Google...', zh: 'Facebook, Google 面试出现频率最高的题目汇总...' },
    author: 'CodeMaster',
    tags: [...TAGS.CS, '💼 Interview Prep', '🏢 FAANG', '🧮 Algorithms', '🌳 Data Structures', '🛠️ Practical', '💪 Grind', '🇨🇳 Chinese Content', '📘 Guide'],
    imageUrl: 'https://picsum.photos/400/300?random=101',
    likes: 900,
  },
  {
    id: '8',
    title: { en: 'Bay Area Renting: Avoid Daly City Houses Like This', zh: '湾区租房避雷指南：Daly City 这种房子千万别租' },
    content: { en: 'Lived there for three months, grew mushrooms from humidity, landlord kept deposit!', zh: '住了三个月潮湿到长蘑菇，房东还不退押金，气死我了！' },
    author: 'BayRentBot',
    tags: [...TAGS.Life, '🏠 Renting', '⚠️ Scam Alert', '😡 Rant', '👎 Negative', '⚠️ Warning', '🇨🇳 Chinese Content', '💸 Money'],
    imageUrl: 'https://picsum.photos/400/300?random=8',
    likes: 230,
  },
  {
    id: '9',
    title: { en: 'Help! Roommate screams at games at 3AM', zh: '求助！奇葩舍友半夜三点还在打游戏大叫怎么办？' },
    content: { en: 'Talked multiple times, they promised to change but continued the next night...', zh: '已经沟通了好几次了，每次都说改，结果当晚继续...' },
    author: 'SleepDeprived',
    tags: [...TAGS.Life, '👯 Roommate', '⚔️ Conflict', '😡 Rant', '🎭 Emotional', '🆘 Help Needed', '🇨🇳 Chinese Content', '🎭 Drama'],
    imageUrl: 'https://picsum.photos/400/300?random=9',
    likes: 55,
  },
  {
    id: '10',
    title: { en: 'Sublease 2b2b near Berkeley, Furnished', zh: 'Berkeley 附近 2b2b 转租，带家具拎包入住' },
    content: { en: '10 min walk to campus, graduating urgent sublease, price negotiable...', zh: '距离校园步行10分钟，因为毕业回国急转，价格好商量...' },
    author: 'MoveOutSale',
    tags: [...TAGS.Life, ...TAGS.School, '🏠 Housing', '🔄 Sublease', '🛒 Marketplace', '🛠️ Practical', '🔥 Urgent', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=10',
    likes: 12,
  },
  {
    id: '11',
    title: { en: 'San Jose Nightlife Guide: Best Clubs', zh: 'San Jose 最强夜店攻略，周末不醉不归' },
    content: { en: 'This new club has amazing music and great vibes...', zh: '这家新开的 Club 音乐超炸，而且美女帅哥特别多...' },
    author: 'NightOwl',
    tags: [...TAGS.Fun, ...TAGS.Life, '🌙 Nightlife', '🍷 Alcohol', '💃 Clubbing', '💘 Dating', '🥂 Social', '🇨🇳 Chinese Content', '📘 Guide'],
    imageUrl: 'https://picsum.photos/400/300?random=11',
    likes: 800,
  },
  {
    id: '12',
    title: { en: 'Easy A Classes! Professors Never Take Attendance', zh: '这学期水课推荐！这几门课从来不点名' },
    content: { en: 'Great for GPA boosting, all homework is online...', zh: '适合想混学分的同学，教授给分巨高，作业全是网上的...' },
    author: 'GPADefender',
    tags: [...TAGS.School, '💯 Easy A', '😴 Slacker', '🎮 Cheat Code', '🛋️ Lazy', '🛠️ Practical', '🇨🇳 Chinese Content', '📝 Course Review'],
    imageUrl: 'https://picsum.photos/400/300?random=6',
    likes: 210,
  },
  {
    id: '13',
    title: { en: 'LOL Wild Rift NA Rank Push, Need Support', zh: 'LOL 手游美服上分车队，缺个辅助' },
    content: { en: 'Grinding all night, need someone with good mental, no toxic players...', zh: '今晚通宵上分，来个心态好的，不要压力怪...' },
    author: 'EsportsBoy',
    tags: [...TAGS.Fun, '🎮 Gaming', '⚔️ League of Legends', '🤝 Team Up', '🎤 Voice Chat', '🇨🇳 Chinese Content', '🍿 Entertainment'],
    imageUrl: 'https://picsum.photos/400/300?random=13',
    likes: 30,
  },
  {
    id: '14',
    title: { en: 'That new dating show is so addictive!', zh: '最近很火的那个恋爱综艺太上头了！' },
    content: { en: 'Male #3 is such a player, I\'m so mad! Girls beware...', zh: '男三号简直是海王本王，气死我了，集美们快来避雷...' },
    author: 'DramaQueen',
    tags: [...TAGS.Fun, '📺 TV Show', '🎭 Drama', '🗣️ Gossip', '💘 Relationships', '😡 Rant', '🎭 Emotional', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=14',
    likes: 450,
  },
  {
    id: '15',
    title: { en: 'Sephora 20% Off! Niche Perfumes to Buy', zh: '丝芙兰八折大促！这些小众香水必入' },
    content: { en: 'Compiled a list of woody scents perfect for spring/summer...', zh: '给大家整理了适合春夏的木质调香水，高级感满满...' },
    author: 'BeautyIntel',
    tags: [...TAGS.Fun, ...TAGS.Life, '💄 Beauty', '🛍️ Shopping', '🏷️ Sale', '💸 Money', '✨ Esthetic', '🇨🇳 Chinese Content', '👍 Recommendation'],
    imageUrl: 'https://picsum.photos/400/300?random=15',
    likes: 660,
  },
  {
    id: '16',
    title: { en: 'SF Weekend Hike: Lands End Trail', zh: '旧金山周末好去处：Lands End 徒步路线' },
    content: { en: 'Beautiful views of Golden Gate, moderate difficulty, relaxing...', zh: '风景绝美，能看到金门大桥，难度适中，适合周末放松...' },
    author: 'BayAreaOutdoor',
    tags: [...TAGS.Life, '🥾 Hiking', '🌲 Outdoors', '🌿 Nature', '📸 Photography', '🌉 San Francisco', '😌 Relaxing', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=16',
    likes: 320,
  },
  {
    id: '17',
    title: { en: 'Why I Don\'t Recommend CS Students Return to China Immediately', zh: '为什么我不建议 CS 学生一毕业就回国？' },
    content: { en: 'Deep analysis of US vs China tech job markets and H1B reality...', zh: '深度分析中美大厂的就业环境差异，以及 H1B 现状...' },
    author: 'ValleyVeteran',
    tags: [...TAGS.CS, '💼 Career Advice', '🛂 Visa/H1B', '🌏 China vs US', '😐 Serious', '⚔️ Debate', '💭 Opinion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=17',
    likes: 1100,
  },
  {
    id: '18',
    title: { en: 'Costco Deals: Tiramisu is Back!', zh: 'Costco 本周特价实拍，那个神仙提拉米苏回归了！' },
    content: { en: 'Dyson dryer $50 off too! Go get it...', zh: '还有戴森吹风机立减50刀，大家冲啊...' },
    author: 'DealHunter',
    tags: [...TAGS.Life, '🛍️ Shopping', '🥦 Groceries', '🏷️ Deals', '💸 Money', '🍱 Foodie', '🛠️ Practical', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=18',
    likes: 540,
  },
  {
    id: '19',
    title: { en: 'Finally Got Amazon SDE Intern Offer!', zh: '终于拿到了 Amazon 的 SDE Intern Offer！' },
    content: { en: 'Sharing my interview timeline and preparation materials...', zh: '分享一下我的面试时间线和主要复习资料...' },
    author: 'LuckyFish',
    tags: [...TAGS.CS, '🎓 Internship', '🏆 Success Story', '🏢 Amazon', '💼 Interview Prep', '✨ Inspirational', '📘 Guide', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=19',
    likes: 1500,
  },
  {
    id: '20',
    title: { en: 'De Anza Math Prof Warning: Do Not Take Him', zh: 'De Anza College 选课避雷：这个数学教授千万别选' },
    content: { en: 'Heavy accent, impossible exams, completely unpredictable...', zh: '讲课口音极重，考试巨难，完全不按套路出牌...' },
    author: 'CCStudent',
    tags: [...TAGS.School, '👨‍🏫 Professor Review', '📐 Math', '⚠️ Warning', '👎 Negative', '😡 Rant', '🇨🇳 Chinese Content', '🏫 Community College'],
    imageUrl: 'https://picsum.photos/400/300?random=20',
    likes: 180,
  },
  {
    id: '21',
    title: { en: 'Warriors Game Tonight Was Lit! Curry MVP', zh: 'NBA 勇士队今天的比赛太燃了！库里yyds' },
    content: { en: 'That game winner made me cry...', zh: '绝杀那一球真的看哭了，这就是金州拉文...' },
    author: 'SportsFan',
    tags: [...TAGS.Fun, '🏀 Sports', '🏀 Basketball', '🌉 Warriors', '🎉 Fan', '🎭 Emotional', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=21',
    likes: 880,
  },
  {
    id: '22',
    title: { en: 'How to Scrape Xiaohongshu with Python?', zh: '如何用 Python 爬取小红书数据？' },
    content: { en: 'For learning only, bypassing anti-scraping mechanisms...', zh: '仅供学习交流，教你如何绕过反爬机制...' },
    author: 'Scraper',
    tags: [...TAGS.CS, '🐍 Python', '🕷️ Web Scraping', '📚 Tutorial', '🚦 Intermediate', '🎩 Grey Hat', '💻 Project', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=22',
    likes: 670,
  },
  {
    id: '23',
    title: { en: 'Where to find authentic Luosifen in Bay Area?', zh: '湾区哪里有正宗的螺蛳粉？想家了' },
    content: { en: 'Tried a few places, none are quite right. Recommendations?', zh: '试了好几家都差点意思，求推荐...' },
    author: 'FoodieCN',
    tags: [...TAGS.Life, '🍱 Food', '🏠 Homesick', '🍜 Chinese Food', '❓ Question', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=23',
    likes: 150,
  },
  {
    id: '24',
    title: { en: '3 Years Abroad Cured My Anxiety', zh: '留学三年，我治好了我的精神内耗' },
    content: { en: 'I used to compete with everyone, now I accept being ordinary...', zh: '以前总想着要比别人强，现在学会了接受平凡...' },
    author: 'Philosopher',
    tags: [...TAGS.Life, '🧘 Mental Health', '🌱 Personal Growth', '📖 Storytime', '🎭 Emotional', '🤔 Reflection', '🇨🇳 Chinese Content', '✨ Inspirational'],
    imageUrl: 'https://picsum.photos/400/300?random=24',
    likes: 2200,
  },
  {
    id: '25',
    title: { en: 'Used Car: Camry or Civic?', zh: '二手车避坑：买 Camry 还是 Civic？' },
    content: { en: 'Budget 15k, mainly for commuting to school...', zh: '预算 15k 左右，主要用来上学通勤，求老司机带带...' },
    author: 'CarNewbie',
    tags: [...TAGS.Life, '🚗 Cars', '📘 Buying Guide', '💸 Money', '❓ Question', '🛠️ Practical', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=25',
    likes: 90,
  },
  {
    id: '26',
    title: { en: 'Advanced GitHub Copilot Tricks 2024', zh: '2024 GitHub Copilot 高级用法技巧' },
    content: { en: 'Don\'t just use it for completion, it can write tests and refactor...', zh: '别只用来补全代码，它还能帮你写测试、重构...' },
    author: 'DevTools',
    tags: [...TAGS.CS, ...TAGS.AI, '⚡ Productivity', '🛠️ Tools', '📚 Tutorial', '⌨️ Coding', '📘 Guide', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=26',
    likes: 720,
  },
  {
    id: '27',
    title: { en: 'Bay Area Dating is just Coffee Chats', zh: '吐槽一下湾区的约会文化，全是 Coffee Chat' },
    content: { en: 'Can we be creative? It\'s always Philz Coffee talking about work...', zh: '能不能有点创意？每次都是去 Philz Coffee 聊工作...' },
    author: 'SingleDog',
    tags: [...TAGS.Life, '💘 Dating', '🌉 Culture', '🌉 Bay Area', '😡 Rant', '🤣 Funny', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=27',
    likes: 410,
  },
  {
    id: '28',
    title: { en: 'Is C++ really harder than Java?', zh: 'C++ 真的比 Java 难很多吗？' },
    content: { en: 'Taking Data Structures next semester, which language to pick?', zh: '下学期要上 Data Structure，在纠结选哪门语言...' },
    author: 'Freshman101',
    tags: [...TAGS.CS, ...TAGS.School, '💻 C++', '☕ Java', '❓ Question', '📚 Academic', '🚦 Beginner Friendly', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=28',
    likes: 130,
  },
  {
    id: '29',
    title: { en: 'Affordable Student OOTD', zh: '适合学生党的平价 OOTD' },
    content: { en: 'Uniqlo can look high-end too. Sharing my daily fits...', zh: '优衣库也能穿出高级感，分享几套我的日常搭配...' },
    author: 'FashionBlogger',
    tags: [...TAGS.Fun, '💅 Fashion', '👗 Outfit', '💸 Budget', '🎓 Student Life', '📸 Photos', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=29',
    likes: 560,
  },
  {
    id: '30',
    title: { en: 'What is the Next GenAI Trend?', zh: 'Generative AI 的下一个风口是什么？' },
    content: { en: 'From Text-to-Video to 3D generation, technology moves fast...', zh: '从 Text-to-Video 到 3D 生成，技术发展太快了...' },
    author: 'AI_Observer',
    tags: [...TAGS.AI, '📈 Trends', '🏢 Tech Industry', '📊 Analysis', '😐 Serious', '🔮 Future', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=30',
    likes: 980,
  },
  {
    id: '31',
    title: { en: 'Help! Ex won\'t stop stalking me', zh: '救命！被 ex 纠缠怎么办？' },
    content: { en: 'Broke up 6 months ago, keeps texting me recently...', zh: '已经分手半年了，最近又开始发短信骚扰我...' },
    author: 'Anonymous',
    tags: [...TAGS.Life, '💘 Relationship', '🎭 Drama', '🆘 Help Needed', '😨 Scary', '⚖️ Legal', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=31',
    likes: 88,
  },
  {
    id: '32',
    title: { en: 'Best Dim Sum in San Mateo', zh: 'San Mateo 最好吃的早茶推荐' },
    content: { en: 'Waited 2 hours but worth it! Har Gow was amazing...', zh: '排队两小时才吃到，但真的值得！虾饺皇绝了...' },
    author: 'FoodieSquad',
    tags: [...TAGS.Life, '🍱 Food', '🥟 Dim Sum', '🍱 Restaurant Review', '🌉 Bay Area', '📸 Photos', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=32',
    likes: 340,
  },
  {
    id: '33',
    title: { en: 'Want to switch to CS but bad at Math?', zh: '想转码，但是数学基础很差怎么办？' },
    content: { en: 'Liberal arts background, calculus scares me. Is there hope?', zh: '文科背景，看到微积分就头大，还有救吗？' },
    author: 'CareerChanger',
    tags: [...TAGS.CS, '🔄 Career Change', '📐 Math', '😰 Anxiety', '❓ Question', '🆘 Advice Needed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=33',
    likes: 210,
  },
  {
    id: '34',
    title: { en: 'Study Vlog: Closing the Library', zh: '沉浸式学习 Vlog | 图书馆闭馆才走' },
    content: { en: 'Day 100 of studying with me, no procrastination...', zh: '和你一起学习的第100天，拒绝拖延症...' },
    author: 'StudyWithMe',
    tags: [...TAGS.School, '✨ Motivation', '🎥 Vlog', '📚 Study', '⚡ Productivity', '✨ Aesthetic', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=34',
    likes: 120,
  },
  {
    id: '35',
    title: { en: 'Bay Area Ski Carpool to Tahoe!', zh: '湾区滑雪拼车群，Tahoe 走起！' },
    content: { en: 'Have spots this weekend, split gas...', zh: '这周末有车位，来两个会滑的，AA油费...' },
    author: 'SkiLover',
    tags: [...TAGS.Life, '🎿 Skiing', '❄️ Tahoe', '🚗 Carpool', '🥂 Social', '🌲 Outdoors', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=35',
    likes: 95,
  },
  {
    id: '36',
    title: { en: 'DeepSeek Review: Better than ChatGPT?', zh: 'DeepSeek 深度评测：比 ChatGPT 强在哪？' },
    content: { en: 'Tested code generation, results are shocking...', zh: '实测了代码生成能力，结果让人大吃一惊...' },
    author: 'TechReview',
    tags: [...TAGS.AI, ...TAGS.CS, '📝 Review', '🤖 DeepSeek', '⚖️ Comparison', '📰 Tech News', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=36',
    likes: 1300,
  },
  {
    id: '37',
    title: { en: 'Is US Party Culture Boring?', zh: '有没有人觉得美国大学的 Party 文化很无聊？' },
    content: { en: 'Just drinking and dancing, can\'t fit in. Am I too traditional?', zh: '除了喝酒就是蹦迪，完全融入不进去，是我太土了吗...' },
    author: 'IntrovertLife',
    tags: [...TAGS.Life, ...TAGS.School, '🤯 Culture Shock', '🎉 Party', '🤐 Introvert', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=37',
    likes: 420,
  },
  {
    id: '38',
    title: { en: 'Kpop Random Dance at Union Square!', zh: 'Kpop 随机舞蹈活动，就在 Union Square！' },
    content: { en: 'Idol comeback, come dance with us...', zh: '喜欢的爱豆回归了，大家一起来跳舞啊...' },
    author: 'KpopFan',
    tags: [...TAGS.Fun, '💃 Dance', '🎵 Kpop', '🌉 San Francisco', '📅 Event', '🥂 Social', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=38',
    likes: 180,
  },
  {
    id: '39',
    title: { en: 'SMC to UCLA Transfer Stats', zh: 'SMC 转学 UCLA 成功率分析' },
    content: { en: 'If not set on UCB, UCLA is a great choice...', zh: '如果你不是非 UCB 不去，UCLA 也是个很好的选择...' },
    author: 'TransferAdvisor',
    tags: [...TAGS.School, '🐻 UCLA', '🏫 Community College', '📊 Analysis', '📈 Data', '📘 Guide', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=39',
    likes: 600,
  },
  
  // --- GENERATED FILLER POSTS (40-55) ---
  {
    id: '40',
    title: { en: 'Cat has diarrhea, Help!', zh: '猫咪拉肚子了怎么办？急！' },
    content: { en: 'Ate expired wet food, looking lethargic...', zh: '可能是偷吃了过期的罐头，精神有点萎靡...' },
    author: 'NewCatMom',
    tags: [...TAGS.Life, '🐾 Pets', '🐱 Cat', '🏥 Veterinary', '🆘 Help Needed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=40',
    likes: 70,
  },
  {
    id: '41',
    title: { en: 'React 19 Preview: The Compiler is Here', zh: 'React 19 新特性前瞻：Compiler 来了' },
    content: { en: 'No more useMemo? Frontend is changing...', zh: '不再需要 useMemo 和 useCallback？前端要变天了...' },
    author: 'FrontendGuy',
    tags: [...TAGS.CS, '⚛️ React', '🎨 Frontend', '📜 JavaScript', '📰 Tech News', '🧠 Advanced', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=41',
    likes: 850,
  },
  {
    id: '42',
    title: { en: 'DIY Haircut Guide for Men', zh: '如何低成本自己剪头发？男生篇' },
    content: { en: 'Barbers are too expensive, do it yourself...', zh: '美国的理发店太贵了，买个推子自己动手...' },
    author: 'TonyTeacher',
    tags: [...TAGS.Life, '💇 Haircut', '🛠️ DIY', '💸 Money Saving', '📚 Tutorial', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=42',
    likes: 330,
  },
  {
    id: '43',
    title: { en: 'Met a creepy guy at the Gym today', zh: '今天在 Gym 遇到了个下头男' },
    content: { en: 'Tried to "correct" my squat form when he had bad form...', zh: '非要过来指导我深蹲姿势，明明自己练得也不咋样...' },
    author: 'GymGirl',
    tags: [...TAGS.Life, '🏋️ Gym', '😡 Rant', '🚫 Harassment', '👩 Female Perspective', '📖 Storytime', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=43',
    likes: 510,
  },
  {
    id: '44',
    title: { en: 'Stanford Campus Tour Guide', zh: 'Stanford 校园一日游，除了塔还有什么好逛的？' },
    content: { en: 'Visiting with parents, need route and parking tips...', zh: '带父母来旅游，求推荐路线和停车攻略...' },
    author: 'Visitor123',
    tags: [...TAGS.Life, '✈️ Travel', '🌲 Stanford', '🌉 Bay Area', '📘 Guide', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=44',
    likes: 140,
  },
  {
    id: '45',
    title: { en: 'My Notion Template for GPA & Activities', zh: '我的 Notion 模版分享：管理 GPA 和课外活动' },
    content: { en: 'Time management is key to transfer success...', zh: '高效的时间管理是转学成功的关键...' },
    author: 'ProductivityGuru',
    tags: [...TAGS.School, '⚡ Productivity', '📝 Notion', '🛠️ Tools', '💡 Study Tips', '📋 Template', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=45',
    likes: 770,
  },
  {
    id: '46',
    title: { en: 'Stock Market Crash: Buy NVDA Dip?', zh: '最近股市大跌，NVDA 还能抄底吗？' },
    content: { en: 'Technical analysis says support level is at...', zh: '技术面分析，感觉支撑位在...' },
    author: 'StockDiary',
    tags: [...TAGS.Life, '📈 Stocks', '💰 Investing', '🟩 Nvidia', '💸 Money', '⚠️ Risk', '📊 Analysis', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=46',
    likes: 290,
  },
  {
    id: '47',
    title: { en: 'Highly Recommend this Underrated Show (Cancelled)', zh: '强烈推荐这部冷门美剧，虽然被砍了' },
    content: { en: 'Tight plot, great twists, sadly low ratings...', zh: '剧情紧凑，反转不断，可惜收视率不高...' },
    author: 'ShowSaver',
    tags: [...TAGS.Fun, '📺 TV Show', '👍 Recommendation', '💎 Underrated', '🔪 Thriller', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=47',
    likes: 160,
  },
  {
    id: '48',
    title: { en: 'Thoughts on OpenAI Internal Conflict?', zh: '如何看待 OpenAI 现在的内斗？' },
    content: { en: 'What does Sam Altman\'s return mean...', zh: 'Sam Altman 的回归意味着什么...' },
    author: 'TechComment',
    tags: [...TAGS.AI, '🏢 OpenAI', '📰 News', '🎭 Drama', '🏢 Tech Industry', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=48',
    likes: 920,
  },
  {
    id: '49',
    title: { en: 'Dog Shelters in Bay Area?', zh: '湾区哪里有可以领养狗狗的 Shelter？' },
    content: { en: 'Want to adopt a Golden Retriever, need recommendations...', zh: '想养一只金毛，求推荐靠谱的机构...' },
    author: 'DogLover',
    tags: [...TAGS.Life, '🐾 Pets', '🐶 Dog', '🏠 Adoption', '🌉 Bay Area', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=49',
    likes: 220,
  },
  {
    id: '50',
    title: { en: 'No Thesis Ideas? Try These AI Topics', zh: '毕业设计没思路？这几个 AI 方向容易发论文' },
    content: { en: 'Multimodal, RAG, Agents... What professors like...', zh: '多模态，RAG，Agent... 导师最喜欢的选题...' },
    author: 'AcademicTrash',
    tags: [...TAGS.School, ...TAGS.AI, '🔬 Research', '📝 Thesis', '🎓 Grad School', '🆘 Advice', '📚 Academic', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=50',
    likes: 640,
  },
  {
    id: '51',
    title: { en: 'Freshmen: Do NOT Buy School Health Insurance!', zh: '新生必看：千万别买学校的医保 (Insurance Waiver)' },
    content: { en: 'School plan is $3000, outside is $800. How to waive...', zh: '学校医保一年要3000刀，买这个校外保险只要800，cover的项目还更多！手把手教你waive...' },
    author: 'MoneySaver',
    tags: [...TAGS.School, '🏥 Insurance', '📝 Waiver', '🐣 Freshman', '💸 Money Saving', '📘 Guide', '🇨🇳 Chinese Content', '📖 Must Read'],
    imageUrl: 'https://picsum.photos/400/300?random=51',
    likes: 890,
  },
  {
    id: '52',
    title: { en: 'Class of 2027 Group Chat! UCB/De Anza', zh: '2027 Fall 新生抱团组织！UCB/De Anza/Foothill' },
    content: { en: 'Finding friends? Drop your major to join the WeChat group...', zh: '还在找不到组织吗？备注你的专业，拉你进大群，不要做独行侠...' },
    author: 'BayAreaStudent',
    tags: [...TAGS.School, ...TAGS.Life, '🐣 Freshman', '📅 Class of 2027', '🥂 Social', '💬 WeChat Group', '🤝 Networking', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=52',
    likes: 450,
  },
  {
    id: '53',
    title: { en: 'Don\'t Join Too Many Clubs! A Warning', zh: '学姐泪的教训：大一不要加太多社团！' },
    content: { en: 'Joined 5 clubs, failed midterms. Don\'t overcommit...', zh: '刚来美国太兴奋，一口气加了5个club，结果期中考试直接崩盘...' },
    author: 'JuniorSister',
    tags: [...TAGS.School, '🆘 Advice', '⚠️ Warning', '🐣 Freshman', '⏳ Time Management', '📝 GPA', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=54',
    likes: 670,
  },
  {
    id: '54',
    title: { en: 'Drop Deadline Tomorrow! Should I Drop?', zh: '急！明天是 Drop Deadline，这门课要不要退？' },
    content: { en: 'Currently at C-, will a W hurt transfer chances?', zh: '目前的成绩只有C-，如果不退的话GPA就完了，但是退了会有一个W，对转学影响大吗？' },
    author: 'AnxiousStudent',
    tags: [...TAGS.School, '📝 Drop Class', '📜 Transcript', '⚠️ Academic Probation', '🆘 Help Needed', '❓ Question', '♟️ Strategy', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=55',
    likes: 120,
  },
  {
    id: '55',
    title: { en: 'CC Students Can Get Internships Too!', zh: '谁说 Community College 学生找不到实习？' },
    content: { en: 'Sharing my journey finding startups that hire CC students...', zh: '分享我的 CC 找工经历，虽然拿不到大厂，但是这些 Startup 真的很缺人...' },
    author: 'InternPro',
    tags: [...TAGS.CS, ...TAGS.School, '🎓 Internship', '💼 Career', '📄 Resume', '🏫 Community College', '🏆 Success Story', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=57',
    likes: 780,
  },

  // --- FILLED GAP (60-110) ---
  {
    id: '60',
    title: { en: 'My manager is ghosting me on Slack', zh: '经理在 Slack 上不回我消息' },
    content: { en: 'It\'s been 3 days. Am I getting fired?', zh: '已经三天没回我了，我是不是要被裁了？' },
    author: 'AnxiousDev',
    tags: [...TAGS.CS, '😰 Anxiety', '💼 Tech Career', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=60',
    likes: 120,
  },
  {
    id: '61',
    title: { en: 'Best spicy hotpot in South Bay?', zh: '南湾哪家火锅最辣最正宗？' },
    content: { en: 'Craving Sichuan style. Haidilao is too mild.', zh: '想吃正宗川味，海底捞太淡了。' },
    author: 'SpicyLover',
    tags: [...TAGS.Life, '🍱 Foodie', '🌶️ Spicy', '🍜 Chinese Food', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=61',
    likes: 450,
  },
  {
    id: '62',
    title: { en: 'Is it worth upgrading to iPhone 16?', zh: 'iPhone 16 值得买吗？' },
    content: { en: 'Still on iPhone 12. Battery is dying.', zh: '还在用 iPhone 12，电池快不行了。' },
    author: 'AppleFan',
    tags: [...TAGS.Fun, '📱 Tech', '💸 Money', '❓ Question', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=62',
    likes: 230,
  },
  {
    id: '63',
    title: { en: 'Found a lost AirPod case at gym', zh: '健身房捡到一个 AirPod 盒子' },
    content: { en: 'Left it at the front desk. Identify it to claim.', zh: '放在前台了，失主快去认领。' },
    author: 'GoodSamaritan',
    tags: [...TAGS.Life, '🏋️ Gym', '😇 Good Deed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=63',
    likes: 50,
  },
  {
    id: '64',
    title: { en: 'Free sofa bed (heavy), pickup only', zh: '免费送沙发床（很重），自取' },
    content: { en: 'Moving out. Needs 2 people to lift.', zh: '搬家带不走，需要两个人抬。' },
    author: 'MovingOut',
    tags: [...TAGS.Life, '🛒 Marketplace', '💸 Free', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=64',
    likes: 90,
  },
  {
    id: '65',
    title: { en: 'Dating a PM vs SWE?', zh: '和 PM 谈恋爱 vs 和程序员谈恋爱？' },
    content: { en: 'My PM boyfriend keeps creating Jira tickets for our dates.', zh: '我的 PM 男朋友给我们的约会建了 Jira ticket...' },
    author: 'TechGF',
    tags: [...TAGS.Life, '💘 Dating', '🤣 Funny', '💼 Tech Career', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=65',
    likes: 880,
  },
  {
    id: '66',
    title: { en: 'Why is Highway 101 always red?', zh: '为什么 101 高速永远是红色的？' },
    content: { en: 'Left at 10am, still stuck. Is there an accident?', zh: '早上10点出发，现在还在堵。是有车祸吗？' },
    author: 'TrafficHater',
    tags: [...TAGS.Life, '🚗 Cars', '😡 Rant', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=66',
    likes: 310,
  },
  {
    id: '67',
    title: { en: 'Foggy today in Daly City', zh: '今天 Daly City 又是大雾' },
    content: { en: 'Can\'t see my neighbor\'s house. Silent Hill vibes.', zh: '看不见邻居家房子了。寂静岭既视感。' },
    author: 'FogCity',
    tags: [...TAGS.Life, '🌿 Nature', '📸 Photography', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=67',
    likes: 150,
  },
  {
    id: '68',
    title: { en: 'Good dentist recommendation in Cupertino?', zh: 'Cupertino 求推荐靠谱牙医' },
    content: { en: 'Need a root canal. Scared of pain.', zh: '要做根管治疗，怕疼。' },
    author: 'ToothAche',
    tags: [...TAGS.Life, '🏥 Health', '❓ Question', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=68',
    likes: 80,
  },
  {
    id: '69',
    title: { en: 'Tax return accountant needed', zh: '求推荐靠谱的报税会计师' },
    content: { en: 'Have RSUs and crypto. TurboTax is confusing.', zh: '有 RSU 和加密货币，TurboTax 搞不定了。' },
    author: 'TaxSeason',
    tags: [...TAGS.Life, '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=69',
    likes: 120,
  },
  {
    id: '70',
    title: { en: 'Layoff anxiety thread', zh: '裁员焦虑集中贴' },
    content: { en: 'Hearing rumors about my org. How to prepare?', zh: '听到组里有传言。怎么准备？' },
    author: 'Paranoid',
    tags: [...TAGS.CS, '😰 Anxiety', '📉 Layoff', '💼 Tech Career', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=70',
    likes: 1500,
  },
  {
    id: '71',
    title: { en: 'RTO (Return to Office) sucks', zh: '强制回办公室上班太恶心了' },
    content: { en: 'Commute is 1.5 hours each way. Productivity tanked.', zh: '单程通勤1.5小时，效率直线下降。' },
    author: 'RemoteWorker',
    tags: [...TAGS.CS, '😡 Rant', '💼 Tech Career', '🚗 Traffic', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=71',
    likes: 900,
  },
  {
    id: '72',
    title: { en: 'Free company lunch is getting worse', zh: '公司的免费午餐越来越难吃了' },
    content: { en: 'Budget cuts? It\'s just cold sandwiches now.', zh: '预算砍了吗？现在全是冷三明治。' },
    author: 'FoodCritic',
    tags: [...TAGS.Life, '🍱 Foodie', '😡 Rant', '💼 Tech Career', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=72',
    likes: 340,
  },
  {
    id: '73',
    title: { en: 'Team building event ideas?', zh: '求推荐团建活动点子' },
    content: { en: 'Budget $100/person. No hiking please.', zh: '预算人均100，不要徒步。' },
    author: 'ManagerDave',
    tags: [...TAGS.Life, '🥂 Social', '❓ Question', '💼 Tech Career', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=73',
    likes: 110,
  },
  {
    id: '74',
    title: { en: 'Promotion denied, should I quit?', zh: '升职被拒，该离职吗？' },
    content: { en: 'Did all the work, manager said "next cycle".', zh: '活都干了，经理说“下次一定”。' },
    author: 'Frustrated',
    tags: [...TAGS.CS, '💼 Career Advice', '😡 Rant', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=74',
    likes: 670,
  },
  {
    id: '75',
    title: { en: 'Switching teams internal transfer', zh: '内部转组有什么坑吗？' },
    content: { en: 'Current manager is toxic. Want to switch to AI org.', zh: '现在的经理太 toxic 了，想转去 AI 组。' },
    author: 'InternalMover',
    tags: [...TAGS.CS, '💼 Career Advice', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=75',
    likes: 250,
  },
  {
    id: '76',
    title: { en: 'Blind (app) is so toxic', zh: 'Blind 上的人戾气太重了' },
    content: { en: 'Everyone talks about TC (Total Compensation). Is money everything?', zh: '每个人都在比包裹。钱就是一切吗？' },
    author: 'NewGrad',
    tags: [...TAGS.Life, '😡 Rant', '💬 Discussion', '🌉 Silicon Valley', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=76',
    likes: 560,
  },
  {
    id: '77',
    title: { en: 'Levels.fyi accuracy?', zh: 'Levels.fyi 上的数据准吗？' },
    content: { en: 'Recruiter offered 20k less than average.', zh: 'HR 给的包比平均值低了2万。' },
    author: 'Negotiator',
    tags: [...TAGS.CS, '💸 Money', '❓ Question', '💼 Interview Prep', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=77',
    likes: 410,
  },
  {
    id: '78',
    title: { en: 'H1B lottery results coming out!', zh: 'H1B 抽签结果要出了！' },
    content: { en: 'Praying for everyone. Third attempt.', zh: '为大家祈祷。这是我第三次抽了。' },
    author: 'VisaStress',
    tags: [...TAGS.CS, '🛂 Visa/H1B', '😰 Anxiety', '✨ Inspirational', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=78',
    likes: 2100,
  },
  {
    id: '79',
    title: { en: 'OPT extension timeline', zh: 'OPT 延期大概要多久？' },
    content: { en: 'Submitted 3 months ago. Still pending.', zh: '提交三个月了，还在 pending。' },
    author: 'StudentVisa',
    tags: [...TAGS.CS, '🛂 Visa', '❓ Question', '😰 Anxiety', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=79',
    likes: 330,
  },
  {
    id: '80',
    title: { en: 'Green card priority date retrogressed', zh: '绿卡排期倒退了' },
    content: { en: 'Wait time increased by 2 years. I want to cry.', zh: '等待时间又加了两年。想哭。' },
    author: 'ImmigrationWoes',
    tags: [...TAGS.Life, '🛂 Immigration', '😰 Anxiety', '😡 Rant', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=80',
    likes: 890,
  },
  {
    id: '81',
    title: { en: 'Parents visiting visa tips', zh: '父母探亲签证 B2 攻略' },
    content: { en: 'What documents to prepare for interview?', zh: '面试需要准备什么材料？' },
    author: 'FilialChild',
    tags: [...TAGS.Life, '🛂 Visa', '❓ Question', '📘 Guide', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=81',
    likes: 450,
  },
  {
    id: '82',
    title: { en: 'Flight ticket prices to China are crazy', zh: '回国机票也太贵了吧' },
    content: { en: '$2000 for economy? Used to be $800.', zh: '经济舱都要2000刀？以前只要800。' },
    author: 'Traveler',
    tags: [...TAGS.Life, '✈️ Travel', '💸 Money', '😡 Rant', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=82',
    likes: 670,
  },
  {
    id: '83',
    title: { en: 'Jet lag cure?', zh: '求倒时差神器' },
    content: { en: 'Waking up at 3am every day. Melatonin not working.', zh: '每天凌晨3点醒。褪黑素没用。' },
    author: 'Sleepless',
    tags: [...TAGS.Life, '🏥 Health', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=83',
    likes: 120,
  },
  {
    id: '84',
    title: { en: 'Bringing cat on plane', zh: '带猫坐飞机攻略' },
    content: { en: 'Which airline is pet friendly? Soft carrier recommendations?', zh: '哪家航司对宠物友好？求推荐软包。' },
    author: 'CatMom',
    tags: [...TAGS.Life, '🐾 Pets', '✈️ Travel', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=84',
    likes: 310,
  },
  {
    id: '85',
    title: { en: 'Buying furniture from IKEA vs Wayfair', zh: 'IKEA 和 Wayfair 哪个买家具更好？' },
    content: { en: 'Need cheap but sturdy stuff.', zh: '想要便宜又结实的。' },
    author: 'HomeDecorator',
    tags: [...TAGS.Life, '🏠 Renting', '🛍️ Shopping', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=85',
    likes: 180,
  },
  {
    id: '86',
    title: { en: 'Taskrabbit experience', zh: 'Taskrabbit 找人拼家具体验' },
    content: { en: 'Guy showed up 2 hours late but did a good job.', zh: '大哥迟到了两个小时，但是活干得不错。' },
    author: 'LazyReview',
    tags: [...TAGS.Life, '🛠️ Practical', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=86',
    likes: 90,
  },
  {
    id: '87',
    title: { en: 'PG&E bill is insane', zh: '这个月的电费单太离谱了' },
    content: { en: '$300 for a 1B1B? I barely used heater.', zh: '1B1B 要300刀？我都没怎么开暖气。' },
    author: 'BillShock',
    tags: [...TAGS.Life, '💸 Cost of Living', '😡 Rant', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=87',
    likes: 1200,
  },
  {
    id: '88',
    title: { en: 'Comcast vs AT&T fiber', zh: 'Comcast 和 AT&T 光纤哪个好？' },
    content: { en: 'Comcast keeps dropping connection during meetings.', zh: 'Comcast 开会老掉线。' },
    author: 'InternetUser',
    tags: [...TAGS.Life, '💻 Tech', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=88',
    likes: 140,
  },
  {
    id: '89',
    title: { en: 'Clipper card on phone', zh: '怎么把 Clipper 卡加到手机里？' },
    content: { en: 'Instructions are unclear. Help.', zh: '说明书看不懂。求助。' },
    author: 'PublicTransit',
    tags: [...TAGS.Life, '🛠️ Practical', '❓ Question', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=89',
    likes: 60,
  },
  {
    id: '90',
    title: { en: 'Fastrak violation notice', zh: '收到 Fastrak 罚单了' },
    content: { en: 'I thought it was set to 3 people? How to dispute?', zh: '我明明设了3人 carpool，怎么申诉？' },
    author: 'Driver',
    tags: [...TAGS.Life, '🚗 Cars', '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=90',
    likes: 220,
  },
  {
    id: '91',
    title: { en: 'Parking ticket contest', zh: '谁有比我更多的停车罚单？' },
    content: { en: 'Got 3 in one week. SF parking is a nightmare.', zh: '一周三张。旧金山停车是噩梦。' },
    author: 'BadParker',
    tags: [...TAGS.Life, '🚗 Cars', '🤣 Funny', '🌉 San Francisco', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=91',
    likes: 350,
  },
  {
    id: '92',
    title: { en: 'Car break-in SF', zh: '车窗被砸了，坐标 SF' },
    content: { en: 'Left a jacket inside. Lesson learned.', zh: '留了件外套在里面。花钱买教训。' },
    author: 'SadDriver',
    tags: [...TAGS.Life, '🚗 Cars', '😰 Scary', '🌉 San Francisco', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=92',
    likes: 800,
  },
  {
    id: '93',
    title: { en: 'Safe neighborhoods in Oakland', zh: 'Oakland 有安全的区吗？' },
    content: { en: 'Found a cheap apartment near Lake Merritt. Is it safe?', zh: '在 Merritt 湖附近看到个便宜公寓。安全吗？' },
    author: 'Mover',
    tags: [...TAGS.Life, '🏠 Renting', '❓ Question', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=93',
    likes: 410,
  },
  {
    id: '94',
    title: { en: 'Moving to Seattle? Pros and Cons', zh: '想搬去西雅图，求劝退/安利' },
    content: { en: 'No income tax sounds great. But the rain...', zh: '没有州税很诱人。但是听说天天下雨...' },
    author: 'Relocation',
    tags: [...TAGS.Life, '🌲 Outdoors', '💸 Money', '❓ Question', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=94',
    likes: 550,
  },
  {
    id: '95',
    title: { en: 'Moving to Austin? Tech scene', zh: 'Austin 的科技圈怎么样？' },
    content: { en: 'Is it really the next Silicon Valley?', zh: '真的是下一个硅谷吗？' },
    author: 'TexanWannabe',
    tags: [...TAGS.CS, '💼 Tech Career', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=95',
    likes: 280,
  },
  {
    id: '96',
    title: { en: 'Leaving California', zh: '决定离开加州了' },
    content: { en: 'Cost of living is just too high. Goodbye sunshine.', zh: '生活成本太高了。再见阳光。' },
    author: 'ExCalifornian',
    tags: [...TAGS.Life, '💸 Cost of Living', '📖 Storytime', '👋 Goodbye', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=96',
    likes: 1300,
  },
  {
    id: '97',
    title: { en: 'Sales tax is too high', zh: '这边的消费税也太高了吧' },
    content: { en: 'Almost 10%? My wallet hurts.', zh: '快 10% 了？钱包在滴血。' },
    author: 'Shopper',
    tags: [...TAGS.Life, '💸 Money', '😡 Rant', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=97',
    likes: 120,
  },
  {
    id: '98',
    title: { en: 'Income tax calculation', zh: '到手工资怎么算？' },
    content: { en: 'Offer says 150k, take home is like 90k?', zh: 'Offer 15万，到手怎么才9万？' },
    author: 'FirstJob',
    tags: [...TAGS.Life, '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=98',
    likes: 670,
  },
  {
    id: '99',
    title: { en: 'Stock options vs RSUs', zh: '期权和 RSU 怎么选？' },
    content: { en: 'Startup offering options, big tech offering RSU.', zh: '初创给期权，大厂给 RSU。怎么选？' },
    author: 'EquityNewbie',
    tags: [...TAGS.CS, '💸 Money', '💼 Tech Career', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=99',
    likes: 450,
  },
  {
    id: '100',
    title: { en: 'ESPP worth it?', zh: '公司的 ESPP 值得买吗？' },
    content: { en: '15% discount. Should I max it out?', zh: '85折，要不要拉满？' },
    author: 'Investor',
    tags: [...TAGS.Life, '💰 Investing', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=100',
    likes: 310,
  },
  {
    id: '101',
    title: { en: '401k matching', zh: '401k match 应该存多少？' },
    content: { en: 'Free money? Or trap?', zh: '白送的钱？还是陷阱？' },
    author: 'RetirementPlan',
    tags: [...TAGS.Life, '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=101',
    likes: 240,
  },
  {
    id: '102',
    title: { en: 'Roth IRA backdoor explained', zh: '有人能解释一下 Roth IRA Backdoor 吗？' },
    content: { en: 'Income limit exceeded. How to do it legally?', zh: '收入超了，怎么合法操作？' },
    author: 'FinanceGeek',
    tags: [...TAGS.Life, '💰 Investing', '📘 Guide', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=102',
    likes: 890,
  },
  {
    id: '103',
    title: { en: 'Crypto crash, lost savings', zh: '币圈崩了，存款归零' },
    content: { en: 'Don\'t invest what you can\'t lose.', zh: '投资需谨慎，别用吃饭钱玩。' },
    author: 'SadInvestor',
    tags: [...TAGS.Life, '💰 Investing', '😰 Scary', '⚠️ Warning', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=103',
    likes: 1500,
  },
  {
    id: '104',
    title: { en: 'Buying a Tesla Model Y', zh: '提了 Model Y，真香' },
    content: { en: 'Tax credit helped. Autopilot is cool.', zh: '退税真香。自动驾驶很酷。' },
    author: 'TeslaOwner',
    tags: [...TAGS.Life, '🚗 Cars', '✨ Inspirational', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=104',
    likes: 720,
  },
  {
    id: '105',
    title: { en: 'Charging stations availability', zh: '湾区充电桩好找吗？' },
    content: { en: 'Thinking of getting EV but live in apartment.', zh: '想买电车但是住公寓，充电方便吗？' },
    author: 'EVCurious',
    tags: [...TAGS.Life, '🚗 Cars', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=105',
    likes: 180,
  },
  {
    id: '106',
    title: { en: 'Gas prices Costco line', zh: 'Costco 加油站排队太长了吧' },
    content: { en: 'Saved $5 but waited 30 mins. Worth it?', zh: '省了5块钱，排了半小时。值得吗？' },
    author: 'GasSaver',
    tags: [...TAGS.Life, '💸 Money', '😡 Rant', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=106',
    likes: 330,
  },
  {
    id: '107',
    title: { en: 'Car insurance premium hike', zh: '车险怎么涨了这么多？' },
    content: { en: 'Geico increased by 20%. No accidents.', zh: 'Geico 涨了 20%，明明没出险。' },
    author: 'Insured',
    tags: [...TAGS.Life, '🚗 Cars', '💸 Money', '😡 Rant', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=107',
    likes: 410,
  },
  {
    id: '108',
    title: { en: 'DMV appointment wait time', zh: 'DMV 预约要等两个月？' },
    content: { en: 'Need license renewal asap. Any tips?', zh: '急需换驾照。有什么技巧吗？' },
    author: 'DriverLicense',
    tags: [...TAGS.Life, '🛠️ Practical', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=108',
    likes: 140,
  },
  {
    id: '109',
    title: { en: 'Real ID deadline', zh: 'Real ID 截止日期又延了？' },
    content: { en: 'Do I really need it to fly domestic?', zh: '飞国内线真的必须要有吗？' },
    author: 'TravelDoc',
    tags: [...TAGS.Life, '✈️ Travel', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=109',
    likes: 90,
  },
  {
    id: '110',
    title: { en: 'Jury duty summons', zh: '收到 Jury Duty 传票了，不想去' },
    content: { en: 'Can I say I am not a citizen yet? (I am not)', zh: '可以说我还不是公民吗？（确实不是）' },
    author: 'CitizenToBe',
    tags: [...TAGS.Life, '⚖️ Legal', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=110',
    likes: 120,
  },

  // --- SPECIFIC SOLUTION/VISA POSTS REQUESTED (Mapped to 130-135) ---
  {
    id: '130',
    title: { en: 'Retiring at 35 (FIRE) Guide', zh: '35岁退休 (FIRE) 指南' },
    content: { en: 'Saved $2M, 4% withdrawal rule. Moving to Portugal.', zh: '存够了 2M，按 4% 提取，准备搬去葡萄牙躺平了。' },
    author: 'FireLife',
    tags: [...TAGS.Life, '🔥 FIRE', '💸 Money', '👴 Retirement', '✨ Inspirational', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=130',
    likes: 3100,
  },
  {
    id: '131',
    title: { en: 'Day 1 CPT Guide: Legally Work While Studying', zh: 'Day 1 CPT 完全指南：如何在读书期间合法工作' },
    content: { en: 'List of accredited universities and how to apply. Stay legal.', zh: '整理了靠谱的挂靠学校名单和申请流程，确保身份合法合规。' },
    author: 'VisaHelper',
    tags: [...TAGS.CS, '🛂 Visa/H1B', '🎓 CPT', '⚖️ Legal', '📘 Guide', '♟️ Strategy', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=131',
    likes: 800,
  },
  {
    id: '132',
    title: { en: 'O-1 Visa: You Might Be Qualified Already', zh: 'O-1 杰出人才签证：其实你可能已经符合条件了' },
    content: { en: 'Don\'t need Nobel prize. High salary and key role count.', zh: '不需要诺贝尔奖，高薪和关键职位也算。很多工程师忽略了这个选项。' },
    author: 'ImmigrationPro',
    tags: [...TAGS.CS, '🛂 Visa', '🌟 O-1', '💼 Career', '📘 Guide', '🏆 Success Story', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=132',
    likes: 1200,
  },
  {
    id: '133',
    title: { en: 'Canada Express Entry (EE) Walkthrough', zh: '加拿大 EE 通道打分自测与申请流程' },
    content: { en: 'Plan B is important. How to get PR in Canada fast.', zh: 'Plan B 很重要。手把手教你如何快速拿到加拿大枫叶卡。' },
    author: 'MapleLeaf',
    tags: [...TAGS.Life, '🛂 Immigration', '🇨🇦 Canada', '📘 Guide', '♟️ Strategy', '🛡️ Plan B', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=133',
    likes: 950,
  },
  {
    id: '134',
    title: { en: 'EB2-NIW: National Interest Waiver Explained', zh: 'EB2-NIW 国家利益豁免详解：无需雇主也能拿绿卡' },
    content: { en: 'Great for PhDs and Researchers. Skip the PERM process.', zh: '适合博士和研究人员，跳过 PERM 流程，直接排期。' },
    author: 'GreenCardExpert',
    tags: [...TAGS.School, '🛂 Visa', '🟩 Green Card', '🔬 Research', '📘 Guide', '⚖️ Legal', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=134',
    likes: 700,
  },
  {
    id: '135',
    title: { en: 'Tech Layout Survival Guide: Severance & COBRA', zh: '裁员生存指南：遣散费谈判与 COBRA 医保' },
    content: { en: 'What to sign, what to ask for. Protect your rights.', zh: '被裁了不要慌，先别急着签字。这些权益你必须知道。' },
    author: 'LegalAid',
    tags: [...TAGS.Life, '📉 Layoff', '⚖️ Legal', '💸 Money', '📘 Guide', '🛠️ Practical', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=135',
    likes: 1500,
  },

  // --- MISCELLANEOUS / DAILY LIFE POSTS (200-229) ---
  {
    id: '200',
    title: { en: 'My Neighbor is Playing Trombone at 1 AM', zh: '隔壁邻居凌晨一点还在吹长号...' },
    content: { en: 'It\'s been 3 nights in a row. It sounds like a dying elephant. Should I call the police or join in?', zh: '已经连续三天了，听起来像垂死的大象。我是该报警还是加入他？' },
    author: 'SleeplessInSF',
    tags: [...TAGS.Life, '👯 Roommate', '😡 Rant', '🤣 Funny', '🌉 Bay Area', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=200',
    likes: 240,
  },
  {
    id: '201',
    title: { en: 'Trader Joe\'s Kimbap is FINALLY Restocked', zh: 'Trader Joe\'s 的紫菜包饭终于补货了！' },
    content: { en: 'Ran to the store at 8am. They have a limit of 2 per person. Run don\'t walk!', zh: '早上八点冲过去的，限购每人两个。集美们快冲！' },
    author: 'SnackQueen',
    tags: [...TAGS.Life, '🍱 Foodie', '🛒 Shopping', '🥦 Groceries', '🔥 Urgent', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=201',
    likes: 890,
  },
  {
    id: '202',
    title: { en: 'Uniqlo Bag: Why does everyone have one?', zh: '为什么湾区人手一个优衣库饺子包？' },
    content: { en: 'I see at least 50 of these on Caltrain every day. Is it a cult?', zh: '每天在 Caltrain 上至少能看到50个。这是什么邪教吗？' },
    author: 'FashionObserver',
    tags: [...TAGS.Fun, '💅 Fashion', '🌉 Bay Area', '🤔 Humblebrag', '🤣 Funny', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=202',
    likes: 450,
  },
  {
    id: '203',
    title: { en: 'Caltrain Delayed AGAIN due to "Mechanical Issues"', zh: 'Caltrain 又双叒叕延误了...' },
    content: { en: 'Stuck in Millbrae for 40 mins. My boss is going to kill me.', zh: '在 Millbrae 停了40分钟了，老板要杀了我了。' },
    author: 'CommuterPain',
    tags: [...TAGS.Life, '🌉 Bay Area', '😡 Rant', '💼 Tech Career', '😰 Anxiety', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=203',
    likes: 120,
  },
  {
    id: '204',
    title: { en: 'Is $18 for a Sandwich Normal Now?', zh: '现在一个三明治要18刀是正常的吗？' },
    content: { en: 'Went to a deli in Palo Alto. With tip and tax it was $25. I miss 2019 prices.', zh: '去 Palo Alto 吃了个午饭，加小费税后25刀。我想念2019年的物价。' },
    author: 'BudgetCry',
    tags: [...TAGS.Life, '💸 Cost of Living', '🍱 Foodie', '😡 Rant', '💸 Money', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=204',
    likes: 1500,
  },
  {
    id: '205',
    title: { en: 'Found this weird bug in my apartment', zh: '家里发现了这种奇怪的虫子，在线等挺急的' },
    content: { en: 'Is this a silverfish or a centipede? It moves super fast.', zh: '这是蚰蜒还是衣鱼？跑得巨快，吓死我了。' },
    author: 'BugHater',
    tags: [...TAGS.Life, '🏠 Renting', '😨 Scary', '❓ Question', '🆘 Help Needed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=205',
    likes: 60,
  },
  {
    id: '206',
    title: { en: 'Dating App Fatigue: Deleted Hinge Today', zh: '累了，今天把 Hinge 删了' },
    content: { en: 'Ghosted 3 times in a week. Maybe I\'ll just adopt 5 cats.', zh: '一周被鸽了三次。我还是养五只猫孤独终老吧。' },
    author: 'SingleForever',
    tags: [...TAGS.Life, '💘 Dating', '😰 Anxiety', '😡 Rant', '🎭 Emotional', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=206',
    likes: 920,
  },
  {
    id: '207',
    title: { en: 'Anyone want to play Badminton this weekend?', zh: '周末有约羽毛球的吗？' },
    content: { en: 'Intermediate level, booked a court in Fremont. Need 2 more.', zh: '中级水平，Fremont 订了场，缺两个。' },
    author: 'SportsGuy',
    tags: [...TAGS.Fun, '🥂 Social', '🌉 Bay Area', '💪 Grind', '🤝 Team Up', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=207',
    likes: 40,
  },
  {
    id: '208',
    title: { en: 'Review: The New boba place "TeaHehe"', zh: '测评：新开的奶茶店 TeaHehe 踩雷' },
    content: { en: 'Ordered 30% sugar and it tastes like syrup. Pearls are hard.', zh: '点的三分糖还是甜到齁，珍珠还是夹生的。' },
    author: 'BobaAddict',
    tags: [...TAGS.Life, '🍱 Foodie', '👎 Negative', '🍱 Restaurant Review', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=208',
    likes: 310,
  },
  {
    id: '209',
    title: { en: 'Saw a Coyote in Golden Gate Park!', zh: '在金门公园看到土狼了！' },
    content: { en: 'It was just walking on the path like it owns the place. Keep your dogs close.', zh: '它就在路上大摇大摆地走，各位遛狗的小心点。' },
    author: 'NatureWalk',
    tags: [...TAGS.Life, '🌿 Nature', '🌉 San Francisco', '⚠️ Warning', '📸 Photography', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=209',
    likes: 700,
  },
  {
    id: '210',
    title: { en: 'My roommate leaves dishes in the sink for 3 days', zh: '舍友把碗在水槽里堆了三天了' },
    content: { en: 'It\'s starting to smell. How do I politely tell him to grow up?', zh: '已经开始有味儿了。怎么礼貌地让他有点公德心？' },
    author: 'CleanFreak',
    tags: [...TAGS.Life, '👯 Roommate', '⚔️ Conflict', '😡 Rant', '🆘 Advice Needed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=210',
    likes: 550,
  },
  {
    id: '211',
    title: { en: 'Got a $90 Parking Ticket for Street Cleaning', zh: '扫街忘记挪车，喜提90刀罚单' },
    content: { en: 'I literally moved it 2 minutes after the time started. SFMTA has no mercy.', zh: '我就晚了两分钟，SFMTA 真的没有心。' },
    author: 'TicketMagnet',
    tags: [...TAGS.Life, '🚗 Cars', '💸 Money', '😡 Rant', '🌉 San Francisco', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=211',
    likes: 330,
  },
  {
    id: '212',
    title: { en: 'Furniture Sale: West Elm Sofa $200', zh: '搬家甩卖：West Elm 沙发 200刀' },
    content: { en: 'Moving to NYC. Must go by Friday. Pickup in Sunnyvale.', zh: '要搬去纽约了，周五前必须出掉。Sunnyvale 自取。' },
    author: 'Mover123',
    tags: [...TAGS.Life, '🛒 Marketplace', '🏠 Renting', '💸 Money', '🔥 Urgent', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=212',
    likes: 80,
  },
  {
    id: '213',
    title: { en: 'Is it just me or is LinkedIn becoming Facebook?', zh: 'LinkedIn 现在怎么越来越像朋友圈了？' },
    content: { en: 'People posting wedding photos and crying selfies. Can we keep it professional?', zh: '全是发结婚照和哭惨自拍的。能不能专业一点？' },
    author: 'ProUser',
    tags: [...TAGS.CS, '💼 Tech Career', '😡 Rant', '💬 Discussion', '🙄 Serious', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=213',
    likes: 1100,
  },
  {
    id: '214',
    title: { en: 'Best place to watch the sunset in Berkeley?', zh: 'Berkeley 哪里看日落最好？' },
    content: { en: 'Grizzly Peak is too crowded. Looking for hidden spots.', zh: 'Grizzly Peak 人太多了，求推荐小众景点。' },
    author: 'SunsetLover',
    tags: [...TAGS.Life, '📸 Photography', '🌿 Nature', '🐻 UC Berkeley', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=214',
    likes: 210,
  },
  {
    id: '215',
    title: { en: 'I accidentally replied "Love you" to my boss', zh: '社死现场：手滑给老板发了“爱你”' },
    content: { en: 'It was meant for my GF. He replied with "👍". Should I quit?', zh: '本来是发给女朋友的。他回了个大拇指。我是不是该辞职了？' },
    author: 'CorporateSlave',
    tags: [...TAGS.CS, '💼 Tech Career', '🤣 Funny', '😰 Anxiety', '💀 Storytime', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=215',
    likes: 4200,
  },
  {
    id: '216',
    title: { en: 'Looking for a Gym Buddy (24 Hour Fitness)', zh: '24 Hour Fitness 找个举铁搭子' },
    content: { en: 'Go at 6pm weekdays. Focus on compound lifts.', zh: '工作日晚上6点，主要练三大项。' },
    author: 'GymRat',
    tags: [...TAGS.Life, '🏋️ Gym', '🤝 Team Up', '💪 Grind', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=216',
    likes: 45,
  },
  {
    id: '217',
    title: { en: 'Why are strawberries tasteless in the US?', zh: '为什么美国的草莓一点草莓味都没有？' },
    content: { en: 'They are huge but taste like crunchy water. Miss fruits back home.', zh: '个头很大，但是吃起来像脆水。想念国内的水果了。' },
    author: 'FruitSnob',
    tags: [...TAGS.Life, '🍱 Foodie', '🏠 Homesick', '😡 Rant', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=217',
    likes: 660,
  },
  {
    id: '218',
    title: { en: 'Traffic on 101 South is a parking lot', zh: '101 南向堵成停车场了' },
    content: { en: 'Avoid it if you can. Accident near SFO.', zh: '能绕行就绕行吧，SFO 附近有车祸。' },
    author: 'TrafficAlert',
    tags: [...TAGS.Life, '🚗 Cars', '⚠️ Warning', '🌉 Bay Area', '🛠️ Practical', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=218',
    likes: 300,
  },
  {
    id: '219',
    title: { en: 'Free Pizza at the Student Union!', zh: '学生会有免费 Pizza！' },
    content: { en: 'Leftover from an event. Come get it before it\'s cold.', zh: '活动剩下的，快来拿，凉了就不好吃了。' },
    author: 'FreeFood',
    tags: [...TAGS.School, '🍱 Foodie', '💸 Money Saving', '🔥 Urgent', '🐻 UC Berkeley', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=219',
    likes: 150,
  },
  {
    id: '220',
    title: { en: 'My cat learned to open doors...', zh: '我家猫学会开门了...' },
    content: { en: 'Now no room is safe. Privacy is gone.', zh: '现在没有房间是安全的了。隐私彻底没了。' },
    author: 'CatSlave',
    tags: [...TAGS.Life, '🐱 Cat', '🐾 Pets', '🤣 Funny', '📖 Storytime', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=220',
    likes: 880,
  },
  {
    id: '221',
    title: { en: 'Recruiter called me by the wrong name', zh: 'Recruiter 把我名字叫错了全程没发现' },
    content: { en: 'Called me "David" for 30 mins. My name is Daniel. Did I fail?', zh: '叫了我30分钟 David。我叫 Daniel。是不是凉了？' },
    author: 'JobSeeker',
    tags: [...TAGS.CS, '💼 Interview Prep', '😰 Anxiety', '🤣 Funny', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=221',
    likes: 210,
  },
  {
    id: '222',
    title: { en: 'Scam Call: "Embassy Notice"', zh: '诈骗电话：“大使馆通知”' },
    content: { en: 'They said I have a package detained. Do people still fall for this?', zh: '说我有个包裹被扣留了。现在还有人信这个吗？' },
    author: 'AntiScam',
    tags: [...TAGS.Life, '⚠️ Scam Alert', '⚠️ Warning', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=222',
    likes: 400,
  },
  {
    id: '223',
    title: { en: 'Any good hairstylists for Asian hair?', zh: '求推荐擅长剪亚洲头发的理发师' },
    content: { en: 'Last time I looked like a mushroom. Please help.', zh: '上次剪完像个蘑菇。救救孩子。' },
    author: 'BadHairDay',
    tags: [...TAGS.Life, '💇 Haircut', '💅 Fashion', '❓ Question', '🆘 Advice Needed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=223',
    likes: 180,
  },
  {
    id: '224',
    title: { en: 'Just finished "Three Body Problem"!', zh: '终于看完了《三体》！' },
    content: { en: 'Mind blown. The Dark Forest theory makes so much sense.', zh: '太震撼了。黑暗森林法则细思极恐。' },
    author: 'SciFiFan',
    tags: [...TAGS.Fun, '📖 Storytime', '📚 Academic', '💬 Discussion', '👍 Recommendation', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=224',
    likes: 650,
  },
  {
    id: '225',
    title: { en: 'Raining in July? Global warming is real.', zh: '七月下雨？全球变暖是真的。' },
    content: { en: 'It never rains in summer here. This is weird.', zh: '这也太反常了，以前夏天从来不下雨。' },
    author: 'WeatherWatcher',
    tags: [...TAGS.Life, '🌿 Nature', '💬 Discussion', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=225',
    likes: 90,
  },
  {
    id: '226',
    title: { en: 'Should I buy a standing desk?', zh: '要不要买升降桌？' },
    content: { en: 'My back is killing me but they are so expensive.', zh: '腰快断了，但是真的好贵啊。' },
    author: 'BackPain',
    tags: [...TAGS.CS, '⚡ Productivity', '🛠️ Tools', '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=226',
    likes: 140,
  },
  {
    id: '227',
    title: { en: 'Karaoke Night this Friday!', zh: '周五 KTV 局！' },
    content: { en: 'Going to the one in Japantown. DM to join.', zh: '去 Japantown 那家。想来的私信。' },
    author: 'PartyAnimal',
    tags: [...TAGS.Fun, '🎉 Party', '🌙 Nightlife', '🥂 Social', '🌉 San Francisco', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=227',
    likes: 60,
  },
  {
    id: '228',
    title: { en: 'My parents are visiting for a month...', zh: '爸妈要来住一个月...' },
    content: { en: 'I love them but my freedom is gone. Prepare for conflict.', zh: '虽然很爱他们，但是我的自由没了。准备迎接家庭矛盾。' },
    author: 'FamilyStress',
    tags: [...TAGS.Life, '😰 Anxiety', '🏠 Renting', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=228',
    likes: 770,
  },
  {
    id: '229',
    title: { en: 'Best ramen in South Bay?', zh: '南湾哪家拉面最好吃？' },
    content: { en: 'HiroNori or Ramen Nagi? Fight in the comments.', zh: 'HiroNori 还是 Nagi？评论区打一架。' },
    author: 'NoodleLover',
    tags: [...TAGS.Life, '🍱 Foodie', '🍜 Chinese Food', '❓ Question', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=229',
    likes: 310,
  },

  // --- NEW WESTERN/US-CENTRIC POSTS (IDs 300-399) ---
  // ENRICHED with 15+ tags per post for better recommendation density
  
];