import { Post, UserProfile } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'user_001',
  name: 'Alex Chen',
  bio: 'Community College Student aiming for UCB CS transfer. Interested in AI and Research.',
  interests: [
    { tag: 'Community College', weight: 10 },
    { tag: 'Transfer Strategy', weight: 15 },
    { tag: 'Research', weight: 12 },
    { tag: 'AI/ML', weight: 8 },
    { tag: 'Computer Science', weight: 8 },
    { tag: 'Academic', weight: 5 }
  ],
  dislikes: [], 
};

// Helper to get common tags easily
const TAGS = {
  // Topics
  CS: ['Computer Science', 'Coding', 'Tech Career', 'Software Engineering', 'Silicon Valley', 'Internship'],
  AI: ['AI/ML', 'Deep Learning', 'LLM', 'Data Science', 'Python', 'Math Heavy'],
  School: ['Community College', 'UC Transfer', 'UC Berkeley', 'GPA', 'Academic', 'Study Tips'],
  English: ['English Learning', 'TOEFL/IELTS', 'ESL', 'Language Barrier', 'Writing'],
  Life: ['Bay Area', 'Renting', 'Roommate', 'Cost of Living', 'Social Life', 'Dating', 'Mental Health'],
  Fun: ['Gaming', 'Party', 'Nightlife', 'Entertainment', 'Gossip', 'Fashion', 'Foodie'],
  
  // Attributes (Crucial for filtering)
  Difficulty: ['Beginner Friendly', 'Advanced', 'Hardcore', 'Theory', 'Practical', 'Noob Friendly'],
  Tone: ['Rant', 'Emotional', 'Serious', 'Guide', 'Storytime', 'Inspirational', 'Clickbait', 'Sarcastic', 'Humblebrag', 'Anxiety'],
  Language: ['Chinese Content', 'English Content', 'Chinglish'],
  Audience: ['Students', 'Professionals', 'New Grads', 'International Students', 'Freshman', 'Transfer Student', 'Elite Students', 'PhD Hopefuls']
};

export const MOCK_POSTS: Post[] = [
  // ... (IDs 1-61 remain unchanged, keeping for brevity) ...
  {
    id: '1',
    title: { en: 'GPA 2.0 to UCB? The Secret Path No One Knows', zh: 'GPA 2.0 也能上 UCB？这个冷门路径没人知道！' },
    content: { en: 'As long as you choose the right classes and use these special hacks, even low grades can make it to a top school...', zh: '只要选对课，加上这几个特殊操作，低分也能逆袭名校...' },
    author: 'StudyAbroadHelper',
    tags: [...TAGS.School, 'Low GPA', 'Success Story', 'Clickbait', 'Guide', 'Chinese Content', 'Inspirational', 'Secret Hack'],
    imageUrl: 'https://picsum.photos/400/300?random=1',
    likes: 120,
  },
  {
    id: '2',
    title: { en: 'Bad English? How to Get into Ivy League with 60 Points', zh: '英语基础差？60分也能逆袭藤校的秘密' },
    content: { en: 'Don\'t let language scores be your stumbling block. See how he did it...', zh: '别让语言成绩成为你的绊脚石，看看他是如何做到的...' },
    author: 'TestPrepGuru',
    tags: [...TAGS.English, ...TAGS.School, 'Beginner Friendly', 'Low GPA', 'Test Prep', 'Chinese Content', 'Guide', 'Marketing'],
    imageUrl: 'https://picsum.photos/400/300?random=2',
    likes: 45,
  },
  {
    id: '3',
    title: { en: 'Building an AI Recommendation System from Scratch', zh: '如何从零开始做一个 AI 推荐系统独立项目' },
    content: { en: 'Detailed breakdown of collaborative filtering and deep learning model implementation...', zh: '本文详细拆解了推荐系统的协同过滤与深度学习模型实现...' },
    author: 'TechLead Jay',
    tags: [...TAGS.CS, ...TAGS.AI, 'Project', 'Portfolio', 'Advanced', 'Hardcore', 'Chinese Content', 'Tutorial', 'System Design', 'Backend'],
    imageUrl: 'https://picsum.photos/400/300?random=3',
    likes: 890,
  },
  {
    id: '4',
    title: { en: '2025 CC Transfer to UC System Guide (TAG Details)', zh: '2025年 CC 转学 UC 系统全攻略（含Tag协议细节）' },
    content: { en: 'Detailed interpretation of the latest transfer policies and how to use Assist.org correctly...', zh: '详细解读最新转学政策，Assist.org 的正确用法...' },
    author: 'TransferWiki',
    tags: [...TAGS.School, 'Policy', 'Tag Agreement', 'Serious', 'Guide', 'Must Read', 'Chinese Content', 'Timeline', 'Application'],
    imageUrl: 'https://picsum.photos/400/300?random=4',
    likes: 1200,
  },
  {
    id: '5',
    title: { en: 'What Undergraduate Research Do UCB Professors Like?', zh: 'UCB 教授最喜欢什么样的本科科研经历？' },
    content: { en: 'Interviewed EECS admissions officers, they value these three abilities...', zh: '采访了 EECS 系的招生官，他们看重这三点能力...' },
    author: 'BerkeleySenior',
    tags: [...TAGS.School, ...TAGS.CS, 'Research', 'Professor', 'Interview', 'Insider Info', 'Serious', 'Advanced', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=5',
    likes: 560,
  },
  {
    id: '6',
    title: { en: 'Transformer Architecture Explained with PyTorch', zh: 'Transformer 架构详解与 PyTorch 实现' },
    content: { en: 'Step-by-step guide to writing Attention mechanisms, suitable for beginners...', zh: '手把手教你写 Attention 机制，适合新手入门...' },
    author: 'AI_Study_Group',
    tags: [...TAGS.AI, ...TAGS.CS, 'Theory', 'Math Heavy', 'Code Implementation', 'Pytorch', 'Hardcore', 'Chinese Content', 'Academic'],
    imageUrl: 'https://picsum.photos/400/300?random=7',
    likes: 430,
  },
  {
    id: '7',
    title: { en: 'LeetCode Top 100 Solution Guide', zh: 'LeetCode 刷题清单：Top 100 题解' },
    content: { en: 'Summary of most frequent interview questions from Facebook and Google...', zh: 'Facebook, Google 面试出现频率最高的题目汇总...' },
    author: 'CodeMaster',
    tags: [...TAGS.CS, 'Interview Prep', 'FAANG', 'Algorithms', 'Data Structures', 'Practical', 'Grind', 'Chinese Content', 'Guide'],
    imageUrl: 'https://picsum.photos/400/300?random=101',
    likes: 900,
  },
  {
    id: '8',
    title: { en: 'Bay Area Renting: Avoid Daly City Houses Like This', zh: '湾区租房避雷指南：Daly City 这种房子千万别租' },
    content: { en: 'Lived there for three months, grew mushrooms from humidity, landlord kept deposit!', zh: '住了三个月潮湿到长蘑菇，房东还不退押金，气死我了！' },
    author: 'BayRentBot',
    tags: [...TAGS.Life, 'Renting', 'Scam Alert', 'Rant', 'Negative', 'Warning', 'Chinese Content', 'Money'],
    imageUrl: 'https://picsum.photos/400/300?random=8',
    likes: 230,
  },
  {
    id: '9',
    title: { en: 'Help! Roommate screams at games at 3AM', zh: '求助！奇葩舍友半夜三点还在打游戏大叫怎么办？' },
    content: { en: 'Talked multiple times, they promised to change but continued the next night...', zh: '已经沟通了好几次了，每次都说改，结果当晚继续...' },
    author: 'SleepDeprived',
    tags: [...TAGS.Life, 'Roommate', 'Conflict', 'Rant', 'Emotional', 'Help Needed', 'Chinese Content', 'Drama'],
    imageUrl: 'https://picsum.photos/400/300?random=9',
    likes: 55,
  },
  {
    id: '10',
    title: { en: 'Sublease 2b2b near Berkeley, Furnished', zh: 'Berkeley 附近 2b2b 转租，带家具拎包入住' },
    content: { en: '10 min walk to campus, graduating urgent sublease, price negotiable...', zh: '距离校园步行10分钟，因为毕业回国急转，价格好商量...' },
    author: 'MoveOutSale',
    tags: [...TAGS.Life, ...TAGS.School, 'Housing', 'Sublease', 'Marketplace', 'Practical', 'Urgent', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=10',
    likes: 12,
  },
  {
    id: '11',
    title: { en: 'San Jose Nightlife Guide: Best Clubs', zh: 'San Jose 最强夜店攻略，周末不醉不归' },
    content: { en: 'This new club has amazing music and great vibes...', zh: '这家新开的 Club 音乐超炸，而且美女帅哥特别多...' },
    author: 'NightOwl',
    tags: [...TAGS.Fun, ...TAGS.Life, 'Nightlife', 'Alcohol', 'Clubbing', 'Dating', 'Social', 'Chinese Content', 'Guide'],
    imageUrl: 'https://picsum.photos/400/300?random=11',
    likes: 800,
  },
  {
    id: '12',
    title: { en: 'Easy A Classes! Professors Never Take Attendance', zh: '这学期水课推荐！这几门课从来不点名' },
    content: { en: 'Great for GPA boosting, all homework is online...', zh: '适合想混学分的同学，教授给分巨高，作业全是网上的...' },
    author: 'GPADefender',
    tags: [...TAGS.School, 'Easy A', 'Slacker', 'Cheat Code', 'Lazy', 'Practical', 'Chinese Content', 'Course Review'],
    imageUrl: 'https://picsum.photos/400/300?random=6',
    likes: 210,
  },
  {
    id: '13',
    title: { en: 'LOL Wild Rift NA Rank Push, Need Support', zh: 'LOL 手游美服上分车队，缺个辅助' },
    content: { en: 'Grinding all night, need someone with good mental, no toxic players...', zh: '今晚通宵上分，来个心态好的，不要压力怪...' },
    author: 'EsportsBoy',
    tags: [...TAGS.Fun, 'Gaming', 'League of Legends', 'Team Up', 'Voice Chat', 'Chinese Content', 'Entertainment'],
    imageUrl: 'https://picsum.photos/400/300?random=13',
    likes: 30,
  },
  {
    id: '14',
    title: { en: 'That new dating show is so addictive!', zh: '最近很火的那个恋爱综艺太上头了！' },
    content: { en: 'Male #3 is such a player, I\'m so mad! Girls beware...', zh: '男三号简直是海王本王，气死我了，集美们快来避雷...' },
    author: 'DramaQueen',
    tags: [...TAGS.Fun, 'TV Show', 'Drama', 'Gossip', 'Relationships', 'Rant', 'Emotional', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=14',
    likes: 450,
  },
  {
    id: '15',
    title: { en: 'Sephora 20% Off! Niche Perfumes to Buy', zh: '丝芙兰八折大促！这些小众香水必入' },
    content: { en: 'Compiled a list of woody scents perfect for spring/summer...', zh: '给大家整理了适合春夏的木质调香水，高级感满满...' },
    author: 'BeautyIntel',
    tags: [...TAGS.Fun, ...TAGS.Life, 'Beauty', 'Shopping', 'Sale', 'Money', 'Esthetic', 'Chinese Content', 'Recommendation'],
    imageUrl: 'https://picsum.photos/400/300?random=15',
    likes: 660,
  },
  {
    id: '16',
    title: { en: 'SF Weekend Hike: Lands End Trail', zh: '旧金山周末好去处：Lands End 徒步路线' },
    content: { en: 'Beautiful views of Golden Gate, moderate difficulty, relaxing...', zh: '风景绝美，能看到金门大桥，难度适中，适合周末放松...' },
    author: 'BayAreaOutdoor',
    tags: [...TAGS.Life, 'Hiking', 'Outdoors', 'Nature', 'Photography', 'San Francisco', 'Relaxing', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=16',
    likes: 320,
  },
  {
    id: '17',
    title: { en: 'Why I Don\'t Recommend CS Students Return to China Immediately', zh: '为什么我不建议 CS 学生一毕业就回国？' },
    content: { en: 'Deep analysis of US vs China tech job markets and H1B reality...', zh: '深度分析中美大厂的就业环境差异，以及 H1B 现状...' },
    author: 'ValleyVeteran',
    tags: [...TAGS.CS, 'Career Advice', 'Visa/H1B', 'China vs US', 'Serious', 'Debate', 'Opinion', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=17',
    likes: 1100,
  },
  {
    id: '18',
    title: { en: 'Costco Deals: Tiramisu is Back!', zh: 'Costco 本周特价实拍，那个神仙提拉米苏回归了！' },
    content: { en: 'Dyson dryer $50 off too! Go get it...', zh: '还有戴森吹风机立减50刀，大家冲啊...' },
    author: 'DealHunter',
    tags: [...TAGS.Life, 'Shopping', 'Groceries', 'Deals', 'Money', 'Foodie', 'Practical', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=18',
    likes: 540,
  },
  {
    id: '19',
    title: { en: 'Finally Got Amazon SDE Intern Offer!', zh: '终于拿到了 Amazon 的 SDE Intern Offer！' },
    content: { en: 'Sharing my interview timeline and preparation materials...', zh: '分享一下我的面试时间线和主要复习资料...' },
    author: 'LuckyFish',
    tags: [...TAGS.CS, 'Internship', 'Success Story', 'Amazon', 'Interview Prep', 'Inspirational', 'Guide', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=19',
    likes: 1500,
  },
  {
    id: '20',
    title: { en: 'De Anza Math Prof Warning: Do Not Take Him', zh: 'De Anza College 选课避雷：这个数学教授千万别选' },
    content: { en: 'Heavy accent, impossible exams, completely unpredictable...', zh: '讲课口音极重，考试巨难，完全不按套路出牌...' },
    author: 'CCStudent',
    tags: [...TAGS.School, 'Professor Review', 'Math', 'Warning', 'Negative', 'Rant', 'Chinese Content', 'Community College'],
    imageUrl: 'https://picsum.photos/400/300?random=20',
    likes: 180,
  },
  {
    id: '21',
    title: { en: 'Warriors Game Tonight Was Lit! Curry MVP', zh: 'NBA 勇士队今天的比赛太燃了！库里yyds' },
    content: { en: 'That game winner made me cry...', zh: '绝杀那一球真的看哭了，这就是金州拉文...' },
    author: 'SportsFan',
    tags: [...TAGS.Fun, 'Sports', 'Basketball', 'Warriors', 'Fan', 'Emotional', 'Bay Area', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=21',
    likes: 880,
  },
  {
    id: '22',
    title: { en: 'How to Scrape Xiaohongshu with Python?', zh: '如何用 Python 爬取小红书数据？' },
    content: { en: 'For learning only, bypassing anti-scraping mechanisms...', zh: '仅供学习交流，教你如何绕过反爬机制...' },
    author: 'Scraper',
    tags: [...TAGS.CS, 'Python', 'Web Scraping', 'Tutorial', 'Intermediate', 'Grey Hat', 'Project', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=22',
    likes: 670,
  },
  {
    id: '23',
    title: { en: 'Where to find authentic Luosifen in Bay Area?', zh: '湾区哪里有正宗的螺蛳粉？想家了' },
    content: { en: 'Tried a few places, none are quite right. Recommendations?', zh: '试了好几家都差点意思，求推荐...' },
    author: 'FoodieCN',
    tags: [...TAGS.Life, 'Food', 'Homesick', 'Chinese Food', 'Question', 'Discussion', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=23',
    likes: 150,
  },
  {
    id: '24',
    title: { en: '3 Years Abroad Cured My Anxiety', zh: '留学三年，我治好了我的精神内耗' },
    content: { en: 'I used to compete with everyone, now I accept being ordinary...', zh: '以前总想着要比别人强，现在学会了接受平凡...' },
    author: 'Philosopher',
    tags: [...TAGS.Life, 'Mental Health', 'Personal Growth', 'Storytime', 'Emotional', 'Reflection', 'Chinese Content', 'Inspirational'],
    imageUrl: 'https://picsum.photos/400/300?random=24',
    likes: 2200,
  },
  {
    id: '25',
    title: { en: 'Used Car: Camry or Civic?', zh: '二手车避坑：买 Camry 还是 Civic？' },
    content: { en: 'Budget 15k, mainly for commuting to school...', zh: '预算 15k 左右，主要用来上学通勤，求老司机带带...' },
    author: 'CarNewbie',
    tags: [...TAGS.Life, 'Cars', 'Buying Guide', 'Money', 'Question', 'Practical', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=25',
    likes: 90,
  },
  {
    id: '26',
    title: { en: 'Advanced GitHub Copilot Tricks 2024', zh: '2024 GitHub Copilot 高级用法技巧' },
    content: { en: 'Don\'t just use it for completion, it can write tests and refactor...', zh: '别只用来补全代码，它还能帮你写测试、重构...' },
    author: 'DevTools',
    tags: [...TAGS.CS, ...TAGS.AI, 'Productivity', 'Tools', 'Tutorial', 'Coding', 'Guide', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=26',
    likes: 720,
  },
  {
    id: '27',
    title: { en: 'Bay Area Dating is just Coffee Chats', zh: '吐槽一下湾区的约会文化，全是 Coffee Chat' },
    content: { en: 'Can we be creative? It\'s always Philz Coffee talking about work...', zh: '能不能有点创意？每次都是去 Philz Coffee 聊工作...' },
    author: 'SingleDog',
    tags: [...TAGS.Life, 'Dating', 'Culture', 'Bay Area', 'Rant', 'Funny', 'Discussion', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=27',
    likes: 410,
  },
  {
    id: '28',
    title: { en: 'Is C++ really harder than Java?', zh: 'C++ 真的比 Java 难很多吗？' },
    content: { en: 'Taking Data Structures next semester, which language to pick?', zh: '下学期要上 Data Structure，在纠结选哪门语言...' },
    author: 'Freshman101',
    tags: [...TAGS.CS, ...TAGS.School, 'C++', 'Java', 'Question', 'Academic', 'Beginner Friendly', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=28',
    likes: 130,
  },
  {
    id: '29',
    title: { en: 'Affordable Student OOTD', zh: '适合学生党的平价 OOTD' },
    content: { en: 'Uniqlo can look high-end too. Sharing my daily fits...', zh: '优衣库也能穿出高级感，分享几套我的日常搭配...' },
    author: 'FashionBlogger',
    tags: [...TAGS.Fun, 'Fashion', 'Outfit', 'Budget', 'Student Life', 'Photos', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=29',
    likes: 560,
  },
  {
    id: '30',
    title: { en: 'What is the Next GenAI Trend?', zh: 'Generative AI 的下一个风口是什么？' },
    content: { en: 'From Text-to-Video to 3D generation, technology moves fast...', zh: '从 Text-to-Video 到 3D 生成，技术发展太快了...' },
    author: 'AI_Observer',
    tags: [...TAGS.AI, 'Trends', 'Tech Industry', 'Analysis', 'Serious', 'Future', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=30',
    likes: 980,
  },
  {
    id: '31',
    title: { en: 'Help! Ex won\'t stop stalking me', zh: '救命！被 ex 纠缠怎么办？' },
    content: { en: 'Broke up 6 months ago, keeps texting me recently...', zh: '已经分手半年了，最近又开始发短信骚扰我...' },
    author: 'Anonymous',
    tags: [...TAGS.Life, 'Relationship', 'Drama', 'Help Needed', 'Scary', 'Legal', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=31',
    likes: 88,
  },
  {
    id: '32',
    title: { en: 'Best Dim Sum in San Mateo', zh: 'San Mateo 最好吃的早茶推荐' },
    content: { en: 'Waited 2 hours but worth it! Har Gow was amazing...', zh: '排队两小时才吃到，但真的值得！虾饺皇绝了...' },
    author: 'FoodieSquad',
    tags: [...TAGS.Life, 'Food', 'Dim Sum', 'Restaurant Review', 'Bay Area', 'Photos', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=32',
    likes: 340,
  },
  {
    id: '33',
    title: { en: 'Want to switch to CS but bad at Math?', zh: '想转码，但是数学基础很差怎么办？' },
    content: { en: 'Liberal arts background, calculus scares me. Is there hope?', zh: '文科背景，看到微积分就头大，还有救吗？' },
    author: 'CareerChanger',
    tags: [...TAGS.CS, 'Career Change', 'Math', 'Anxiety', 'Question', 'Advice Needed', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=33',
    likes: 210,
  },
  {
    id: '34',
    title: { en: 'Study Vlog: Closing the Library', zh: '沉浸式学习 Vlog | 图书馆闭馆才走' },
    content: { en: 'Day 100 of studying with me, no procrastination...', zh: '和你一起学习的第100天，拒绝拖延症...' },
    author: 'StudyWithMe',
    tags: [...TAGS.School, 'Motivation', 'Vlog', 'Study', 'Productivity', 'Aesthetic', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=34',
    likes: 120,
  },
  {
    id: '35',
    title: { en: 'Bay Area Ski Carpool to Tahoe!', zh: '湾区滑雪拼车群，Tahoe 走起！' },
    content: { en: 'Have spots this weekend, split gas...', zh: '这周末有车位，来两个会滑的，AA油费...' },
    author: 'SkiLover',
    tags: [...TAGS.Life, 'Skiing', 'Tahoe', 'Carpool', 'Social', 'Outdoors', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=35',
    likes: 95,
  },
  {
    id: '36',
    title: { en: 'DeepSeek Review: Better than ChatGPT?', zh: 'DeepSeek 深度评测：比 ChatGPT 强在哪？' },
    content: { en: 'Tested code generation, results are shocking...', zh: '实测了代码生成能力，结果让人大吃一惊...' },
    author: 'TechReview',
    tags: [...TAGS.AI, ...TAGS.CS, 'Review', 'DeepSeek', 'Comparison', 'Tech News', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=36',
    likes: 1300,
  },
  {
    id: '37',
    title: { en: 'Is US Party Culture Boring?', zh: '有没有人觉得美国大学的 Party 文化很无聊？' },
    content: { en: 'Just drinking and dancing, can\'t fit in. Am I too traditional?', zh: '除了喝酒就是蹦迪，完全融入不进去，是我太土了吗...' },
    author: 'IntrovertLife',
    tags: [...TAGS.Life, ...TAGS.School, 'Culture Shock', 'Party', 'Introvert', 'Discussion', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=37',
    likes: 420,
  },
  {
    id: '38',
    title: { en: 'Kpop Random Dance at Union Square!', zh: 'Kpop 随机舞蹈活动，就在 Union Square！' },
    content: { en: 'Idol comeback, come dance with us...', zh: '喜欢的爱豆回归了，大家一起来跳舞啊...' },
    author: 'KpopFan',
    tags: [...TAGS.Fun, 'Dance', 'Kpop', 'San Francisco', 'Event', 'Social', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=38',
    likes: 180,
  },
  {
    id: '39',
    title: { en: 'SMC to UCLA Transfer Stats', zh: 'SMC 转学 UCLA 成功率分析' },
    content: { en: 'If not set on UCB, UCLA is a great choice...', zh: '如果你不是非 UCB 不去，UCLA 也是个很好的选择...' },
    author: 'TransferAdvisor',
    tags: [...TAGS.School, 'UCLA', 'Community College', 'Analysis', 'Data', 'Guide', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=39',
    likes: 600,
  },
  {
    id: '40',
    title: { en: 'Cat has diarrhea, Help!', zh: '猫咪拉肚子了怎么办？急！' },
    content: { en: 'Ate expired wet food, looking lethargic...', zh: '可能是偷吃了过期的罐头，精神有点萎靡...' },
    author: 'NewCatMom',
    tags: [...TAGS.Life, 'Pets', 'Cat', 'Veterinary', 'Help Needed', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=40',
    likes: 70,
  },
  {
    id: '41',
    title: { en: 'React 19 Preview: The Compiler is Here', zh: 'React 19 新特性前瞻：Compiler 来了' },
    content: { en: 'No more useMemo? Frontend is changing...', zh: '不再需要 useMemo 和 useCallback？前端要变天了...' },
    author: 'FrontendGuy',
    tags: [...TAGS.CS, 'React', 'Frontend', 'JavaScript', 'Tech News', 'Advanced', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=41',
    likes: 850,
  },
  {
    id: '42',
    title: { en: 'DIY Haircut Guide for Men', zh: '如何低成本自己剪头发？男生篇' },
    content: { en: 'Barbers are too expensive, do it yourself...', zh: '美国的理发店太贵了，买个推子自己动手...' },
    author: 'TonyTeacher',
    tags: [...TAGS.Life, 'Haircut', 'DIY', 'Money Saving', 'Tutorial', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=42',
    likes: 330,
  },
  {
    id: '43',
    title: { en: 'Met a creepy guy at the Gym today', zh: '今天在 Gym 遇到了个下头男' },
    content: { en: 'Tried to "correct" my squat form when he had bad form...', zh: '非要过来指导我深蹲姿势，明明自己练得也不咋样...' },
    author: 'GymGirl',
    tags: [...TAGS.Life, 'Gym', 'Rant', 'Harassment', 'Female Perspective', 'Storytime', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=43',
    likes: 510,
  },
  {
    id: '44',
    title: { en: 'Stanford Campus Tour Guide', zh: 'Stanford 校园一日游，除了塔还有什么好逛的？' },
    content: { en: 'Visiting with parents, need route and parking tips...', zh: '带父母来旅游，求推荐路线和停车攻略...' },
    author: 'Visitor123',
    tags: [...TAGS.Life, 'Travel', 'Stanford', 'Bay Area', 'Guide', 'Question', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=44',
    likes: 140,
  },
  {
    id: '45',
    title: { en: 'My Notion Template for GPA & Activities', zh: '我的 Notion 模版分享：管理 GPA 和课外活动' },
    content: { en: 'Time management is key to transfer success...', zh: '高效的时间管理是转学成功的关键...' },
    author: 'ProductivityGuru',
    tags: [...TAGS.School, 'Productivity', 'Notion', 'Tools', 'Study Tips', 'Template', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=45',
    likes: 770,
  },
  {
    id: '46',
    title: { en: 'Stock Market Crash: Buy NVDA Dip?', zh: '最近股市大跌，NVDA 还能抄底吗？' },
    content: { en: 'Technical analysis says support level is at...', zh: '技术面分析，感觉支撑位在...' },
    author: 'StockDiary',
    tags: [...TAGS.Life, 'Stocks', 'Investing', 'Nvidia', 'Money', 'Risk', 'Analysis', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=46',
    likes: 290,
  },
  {
    id: '47',
    title: { en: 'Highly Recommend this Underrated Show (Cancelled)', zh: '强烈推荐这部冷门美剧，虽然被砍了' },
    content: { en: 'Tight plot, great twists, sadly low ratings...', zh: '剧情紧凑，反转不断，可惜收视率不高...' },
    author: 'ShowSaver',
    tags: [...TAGS.Fun, 'TV Show', 'Recommendation', 'Underrated', 'Thriller', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=47',
    likes: 160,
  },
  {
    id: '48',
    title: { en: 'Thoughts on OpenAI Internal Conflict?', zh: '如何看待 OpenAI 现在的内斗？' },
    content: { en: 'What does Sam Altman\'s return mean...', zh: 'Sam Altman 的回归意味着什么...' },
    author: 'TechComment',
    tags: [...TAGS.AI, 'OpenAI', 'News', 'Drama', 'Tech Industry', 'Discussion', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=48',
    likes: 920,
  },
  {
    id: '49',
    title: { en: 'Dog Shelters in Bay Area?', zh: '湾区哪里有可以领养狗狗的 Shelter？' },
    content: { en: 'Want to adopt a Golden Retriever, need recommendations...', zh: '想养一只金毛，求推荐靠谱的机构...' },
    author: 'DogLover',
    tags: [...TAGS.Life, 'Pets', 'Dog', 'Adoption', 'Bay Area', 'Question', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=49',
    likes: 220,
  },
  {
    id: '50',
    title: { en: 'No Thesis Ideas? Try These AI Topics', zh: '毕业设计没思路？这几个 AI 方向容易发论文' },
    content: { en: 'Multimodal, RAG, Agents... What professors like...', zh: '多模态，RAG，Agent... 导师最喜欢的选题...' },
    author: 'AcademicTrash',
    tags: [...TAGS.School, ...TAGS.AI, 'Research', 'Thesis', 'Grad School', 'Advice', 'Academic', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=50',
    likes: 640,
  },
  {
    id: '51',
    title: { en: 'Freshmen: Do NOT Buy School Health Insurance!', zh: '新生必看：千万别买学校的医保 (Insurance Waiver)' },
    content: { en: 'School plan is $3000, outside is $800. How to waive...', zh: '学校医保一年要3000刀，买这个校外保险只要800，cover的项目还更多！手把手教你waive...' },
    author: 'MoneySaver',
    tags: [...TAGS.School, 'Insurance', 'Waiver', 'Freshman', 'Money Saving', 'Guide', 'Chinese Content', 'Must Read'],
    imageUrl: 'https://picsum.photos/400/300?random=51',
    likes: 890,
  },
  {
    id: '52',
    title: { en: 'Class of 2027 Group Chat! UCB/De Anza', zh: '2027 Fall 新生抱团组织！UCB/De Anza/Foothill' },
    content: { en: 'Finding friends? Drop your major to join the WeChat group...', zh: '还在找不到组织吗？备注你的专业，拉你进大群，不要做独行侠...' },
    author: 'BayAreaStudent',
    tags: [...TAGS.School, ...TAGS.Life, 'Freshman', 'Class of 2027', 'Social', 'WeChat Group', 'Networking', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=52',
    likes: 450,
  },
  {
    id: '53',
    title: { en: 'CSSA Recruitment! Join Us', zh: 'CSSA 招新啦！期待你的加入' },
    content: { en: 'Enrich your life and meet friends. Events department hiring...', zh: '想要丰富课余生活吗？想要认识更多志同道合的朋友吗？外联部、文艺部等你来...' },
    author: 'CSSA',
    tags: [...TAGS.School, ...TAGS.Fun, 'Club', 'Recruitment', 'Student Union', 'Social', 'Freshman', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=53',
    likes: 320,
  },
  {
    id: '54',
    title: { en: 'Don\'t Join Too Many Clubs! A Warning', zh: '学姐泪的教训：大一不要加太多社团！' },
    content: { en: 'Joined 5 clubs, failed midterms. Don\'t overcommit...', zh: '刚来美国太兴奋，一口气加了5个club，结果期中考试直接崩盘...' },
    author: 'JuniorSister',
    tags: [...TAGS.School, 'Advice', 'Warning', 'Freshman', 'Time Management', 'GPA', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=54',
    likes: 670,
  },
  {
    id: '55',
    title: { en: 'Drop Deadline Tomorrow! Should I Drop?', zh: '急！明天是 Drop Deadline，这门课要不要退？' },
    content: { en: 'Currently at C-, will a W hurt transfer chances?', zh: '目前的成绩只有C-，如果不退的话GPA就完了，但是退了会有一个W，对转学影响大吗？' },
    author: 'AnxiousStudent',
    tags: [...TAGS.School, 'Drop Class', 'Transcript', 'Academic Probation', 'Help Needed', 'Question', 'Strategy', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=55',
    likes: 120,
  },
  {
    id: '56',
    title: { en: 'How I Recovered My GPA from 2.3 to 3.8', zh: '我是如何把 GPA 从 2.3 拉回到 3.8 的' },
    content: { en: 'Failed freshman year, here is my comeback plan...', zh: '大一贪玩挂科了，后面两个学期我是怎么规划选课和复习的，干货满满...' },
    author: 'ComebackKid',
    tags: [...TAGS.School, 'GPA', 'Academic Comeback', 'Motivation', 'Guide', 'Study Tips', 'Inspirational', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=56',
    likes: 1100,
  },
  {
    id: '57',
    title: { en: 'CC Students Can Get Internships Too!', zh: '谁说 Community College 学生找不到实习？' },
    content: { en: 'Sharing my journey finding startups that hire CC students...', zh: '分享我的 CC 找工经历，虽然拿不到大厂，但是这些 Startup 真的很缺人...' },
    author: 'InternPro',
    tags: [...TAGS.CS, ...TAGS.School, 'Internship', 'Career', 'Resume', 'Community College', 'Success Story', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=57',
    likes: 780,
  },
  {
    id: '58',
    title: { en: 'First New Year Alone, So Homesick', zh: '第一次在国外过年，想家想到哭' },
    content: { en: 'Eating instant noodles while watching friends post feasts...', zh: '看到朋友圈都在发年夜饭，自己只能煮泡面，这种孤独感谁懂啊...' },
    author: 'LonelyStudent',
    tags: [...TAGS.Life, 'Homesick', 'Emotional', 'Mental Health', 'Holidays', 'Chinese Content', 'Relatable'],
    imageUrl: 'https://picsum.photos/400/300?random=58',
    likes: 2300,
  },
  {
    id: '59',
    title: { en: 'Avoid this CS61A Professor!', zh: '避雷！CS61A 的这个教授千万别选！' },
    content: { en: 'Monotone voice, impossible homework, never at office hours...', zh: '讲课像念经，作业巨难，Office Hour 还找不到人，快跑！' },
    author: 'FailedStudent',
    tags: [...TAGS.School, 'Professor Review', 'Warning', 'Negative', 'Computer Science', 'Rant', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=59',
    likes: 410,
  },
  {
    id: '60',
    title: { en: 'Brainstorming for UC PIQ Essays', zh: 'UC 文书 (PIQ) 写作思路头脑风暴' },
    content: { en: 'Stuck on the 4th essay? Try these angles...', zh: '还在为第四篇写什么发愁吗？这几个角度可以让招生官眼前一亮...' },
    author: 'EssayMentor',
    tags: [...TAGS.School, 'Transfer', 'Application', 'Essays', 'Writing', 'Guide', 'Advanced', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=60',
    likes: 550,
  },
  {
    id: '61',
    title: { en: 'Weee! vs 99 Ranch: Price Comparison', zh: 'Weee! 和 99 Ranch 哪个更划算？对比测评' },
    content: { en: 'Comparing veggies, meat, and snacks...', zh: '对比了蔬菜、肉类和零食的价格，发现这家在打折的时候简直白送...' },
    author: 'BudgetCook',
    tags: [...TAGS.Life, 'Groceries', 'Food', 'Money Saving', 'Comparison', 'Review', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=61',
    likes: 290,
  },
  {
    id: '62',
    title: { en: '2025 H1B Policy Update Analysis', zh: '2025 H1B 抽签新政解读，留学生太难了' },
    content: { en: 'One person one entry implementation. Will odds improve?', zh: '一人一抽正式实施，中签率会有所回升吗？深度分析...' },
    author: 'ImmigrationLawyer',
    tags: [...TAGS.CS, 'Visa', 'H1B', 'Career', 'News', 'Serious', 'Guide', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=62',
    likes: 950,
  },
  {
    id: '63',
    title: { en: 'Black Myth: Wukong Steam Unlock & Settings', zh: '《黑神话：悟空》Steam 解锁！配置要求及优化指南' },
    content: { en: 'Can 4060 run it? Best graphics settings...', zh: '4060 显卡能不能流畅运行？画面设置作业抄这里...' },
    author: 'HardcoreGamer',
    tags: [...TAGS.Fun, 'Gaming', 'Tech', 'Black Myth: Wukong', 'Guide', 'Chinese Content', 'Entertainment'],
    imageUrl: 'https://picsum.photos/400/300?random=63',
    likes: 1200,
  },
  // ... (IDs 64-130 remain unchanged, keeping for brevity) ...
  {
    id: '130',
    title: { en: 'Retiring at 35 (FIRE) Guide', zh: '35岁退休 (FIRE) 指南' },
    content: { en: 'Saved $2M, 4% withdrawal rule. Moving to Portugal.', zh: '存够了 2M，按 4% 提取，准备搬去葡萄牙躺平了。' },
    author: 'FireLife',
    tags: [...TAGS.Life, 'FIRE', 'Money', 'Retirement', 'Inspirational', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=130',
    likes: 3100,
  },

  // --- NEW: Safe Solution Inventory (No Anxiety Tags) ---
  {
    id: '131',
    title: { en: 'Day 1 CPT Guide: Legally Work While Studying', zh: 'Day 1 CPT 完全指南：如何在读书期间合法工作' },
    content: { en: 'List of accredited universities and how to apply. Stay legal.', zh: '整理了靠谱的挂靠学校名单和申请流程，确保身份合法合规。' },
    author: 'VisaHelper',
    tags: [...TAGS.CS, 'Visa', 'H1B', 'CPT', 'Legal', 'Guide', 'Strategy', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=131',
    likes: 800,
  },
  {
    id: '132',
    title: { en: 'O-1 Visa: You Might Be Qualified Already', zh: 'O-1 杰出人才签证：其实你可能已经符合条件了' },
    content: { en: 'Don\'t need Nobel prize. High salary and key role count.', zh: '不需要诺贝尔奖，高薪和关键职位也算。很多工程师忽略了这个选项。' },
    author: 'ImmigrationPro',
    tags: [...TAGS.CS, 'Visa', 'O-1', 'Career', 'Guide', 'Success Story', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=132',
    likes: 1200,
  },
  {
    id: '133',
    title: { en: 'Canada Express Entry (EE) Walkthrough', zh: '加拿大 EE 通道打分自测与申请流程' },
    content: { en: 'Plan B is important. How to get PR in Canada fast.', zh: 'Plan B 很重要。手把手教你如何快速拿到加拿大枫叶卡。' },
    author: 'MapleLeaf',
    tags: [...TAGS.Life, 'Immigration', 'Canada', 'Guide', 'Strategy', 'Plan B', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=133',
    likes: 950,
  },
  {
    id: '134',
    title: { en: 'EB2-NIW: National Interest Waiver Explained', zh: 'EB2-NIW 国家利益豁免详解：无需雇主也能拿绿卡' },
    content: { en: 'Great for PhDs and Researchers. Skip the PERM process.', zh: '适合博士和研究人员，跳过 PERM 流程，直接排期。' },
    author: 'GreenCardExpert',
    tags: [...TAGS.School, 'Visa', 'Green Card', 'Research', 'Guide', 'Legal', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=134',
    likes: 700,
  },
  {
    id: '135',
    title: { en: 'Tech Layout Survival Guide: Severance & COBRA', zh: '裁员生存指南：遣散费谈判与 COBRA 医保' },
    content: { en: 'What to sign, what to ask for. Protect your rights.', zh: '被裁了不要慌，先别急着签字。这些权益你必须知道。' },
    author: 'LegalAid',
    tags: [...TAGS.Life, 'Layoff', 'Legal', 'Money', 'Guide', 'Practical', 'Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=135',
    likes: 1500,
  }
];