import { Post } from './types';

// Export these tags so the LLM knows they exist!
export const PET_AND_ENT_TAGS = [
  // Core Pet Tags
  '🐱 Cat', '🐶 Dog', '🐾 Pets', '✨ Healing', '💤 Sleep', '☁️ Fluffy', 
  '🍑 Corgi', '🍊 Orange Cat', '🖼️ Meme', 
  
  // Entertainment Vibe Tags
  '🎬 Movies', '🌌 Sci-Fi', '🧙‍♂️ Fantasy', '🕹️ Switch', '🎮 Gaming',
  '🇺🇸 USA Culture', '✨ Nostalgia' 
];

// Filling the gap between 229 and 300 with "Chinese/Bay Area/Student" style content.
// Mix of Tech, Life, Food, and Schooling.

export const ADDITIONAL_POSTS_3: Post[] = [
  {
    id: '230',
    title: { en: 'Haidilao secret codes 2024', zh: '2024 海底捞最新暗号大全，亲测有效！' },
    content: { en: 'Get free toys and snacks. Don\'t tell the manager.', zh: '想要免费的仙女棒和小零食吗？对着服务员说这几句...' },
    author: 'HotpotLover',
    tags: ['🍱 Foodie', '🍱 Restaurant Review', '🔥 Hotpot', '🤫 Secret Hack', '💸 Money Saving', '🇨🇳 Chinese Content'],
    tagWeights: { '🍱 Foodie': 2.0, '🔥 Hotpot': 2.5, '🤫 Secret Hack': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=230',
    likes: 3400,
  },
  {
    id: '231',
    title: { en: 'Amazon PIP survival guide', zh: '亚马逊 PIP 幸存者指南' },
    content: { en: 'Got put on Focus, here is how I passed (or should you just leave?).', zh: '如果不幸进了 Focus，是该硬刚还是拿钱走人？分享我的经历...' },
    author: 'TechSurvivor',
    tags: ['💻 Computer Science', '🏢 Amazon', '⚠️ PIP', '💼 Career Advice', '😰 Anxiety', '🇨🇳 Chinese Content'],
    tagWeights: { '💻 Computer Science': 1.5, '🏢 Amazon': 2.0, '⚠️ PIP': 2.5, '💼 Career Advice': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=231',
    likes: 1200,
  },
  {
    id: '232',
    title: { en: 'Hiking Mission Peak at night?', zh: '有人夜爬过 Mission Peak 吗？' },
    content: { en: 'Is it safe? Want to see the sunrise.', zh: '想去看日出，但是停车场几点开？安全吗？' },
    author: 'OutdoorLife',
    tags: ['🌿 Nature', '🥾 Hiking', '🌉 Bay Area', '❓ Question', '📸 Photography', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=232',
    likes: 210,
  },
  {
    id: '233',
    title: { en: 'Buying a townhouse in Newark/Fremont', zh: 'Newark/Fremont 买房避坑指南' },
    content: { en: 'Why are the HOAs so high? Smell from the dump?', zh: 'HOA 怎么这么贵？还有那个垃圾场的味道现在还有吗？' },
    author: 'BayAreaHouse',
    tags: ['🏠 Renting', '🏡 Real Estate', '💸 Money', '🌉 Bay Area', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=233',
    likes: 890,
  },
  {
    id: '234',
    title: { en: 'Trader Joe\'s Kimbap vs Costco', zh: '缺德舅的紫菜包饭 vs Costco 的，哪个更好吃？' },
    content: { en: 'Did a blind taste test. The result is surprising.', zh: '做了一个盲测。Costco 的居然赢了？' },
    author: 'SnackReview',
    tags: ['🍱 Foodie', '🛒 Trader Joes', '🛒 Costco', '⚖️ Comparison', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=234',
    likes: 560,
  },
  {
    id: '235',
    title: { en: 'Dealing with heavy hair loss in US', zh: '来美国后狂脱发怎么办？' },
    content: { en: 'Is it the hard water? Need shampoo recommendations.', zh: '是水质太硬了吗？求推荐防脱洗发水！' },
    author: 'BaldStress',
    tags: ['💄 Beauty', '🏥 Health', '😰 Anxiety', '❓ Question', '🚿 Water Filter', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=235',
    likes: 1500,
  },
  {
    id: '236',
    title: { en: 'Any good gynecologists in South Bay?', zh: '南湾求推荐靠谱的女妇科医生' },
    content: { en: 'Prefer Mandarin speaking. Kaiser or Sutter?', zh: '希望能讲中文的。Kaiser 好还是 Sutter 好？' },
    author: 'HealthAsk',
    tags: ['🏥 Health', '👩 Female Perspective', '❓ Question', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=236',
    likes: 300,
  },
  {
    id: '237',
    title: { en: 'Making dumplings for Lunar New Year', zh: '过年了，教大家包三种颜色的饺子' },
    content: { en: 'Using spinach and carrot juice for the dough. So festive!', zh: '用菠菜汁和胡萝卜汁和面，过年氛围感拉满！' },
    author: 'ChefMom',
    tags: ['🍱 Foodie', '🍳 Cooking', '🧧 Lunar New Year', '🏠 Home', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=237',
    likes: 2200,
  },
  {
    id: '238',
    title: { en: 'LeetCode 150: Dynamic Programming is hard', zh: 'LeetCode 150题：动态规划真的太难了' },
    content: { en: 'Stuck on "House Robber". Can someone explain?', zh: '卡在 House Robber 好几天了。有没有通俗易懂的解释？' },
    author: 'CSNewbie',
    tags: ['💻 Computer Science', '🧮 Algorithms', '🆘 Help Needed', '📚 Study', '🇨🇳 Chinese Content'],
    tagWeights: { '💻 Computer Science': 1.5, '🧮 Algorithms': 2.0, '📚 Study': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=238',
    likes: 450,
  },
  {
    id: '239',
    title: { en: 'Ex-boyfriend wants to get back together', zh: '前男友求复合，该答应吗？' },
    content: { en: 'He cheated once but swears he changed.', zh: '虽然出轨过一次，但他发誓改了。真的很纠结。' },
    author: 'LoveTrouble',
    tags: ['💘 Dating', '💔 Heartbreak', '🚩 Red Flag', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=239',
    likes: 880,
  },
  {
    id: '240',
    title: { en: 'Review: 99 Ranch Hot Deli', zh: '大华熟食部避雷：这个菜千万别买' },
    content: { en: 'The spicy chicken was raw inside. Avoid.', zh: '辣子鸡里面居然是生的。避雷避雷。' },
    author: 'FoodSafety',
    tags: ['🍱 Foodie', '🛒 99 Ranch', '👎 Negative', '⚠️ Warning', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=240',
    likes: 670,
  },
  {
    id: '241',
    title: { en: 'How to negotiate rent renewal?', zh: '房租续约怎么砍价？' },
    content: { en: 'They want to raise it by 10%. Market is flat.', zh: '想涨我10%，但是周围房价明明没涨。求话术。' },
    author: 'RenterHelp',
    tags: ['🏠 Renting', '💸 Money', '🗣️ Negotiation', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=241',
    likes: 920,
  },
  {
    id: '242',
    title: { en: 'Anyone going to ADELE concert?', zh: '有去 Adele 拉斯维加斯演唱会的吗？' },
    content: { en: 'Looking for carpool from LA or hotel share.', zh: '求从 LA 拼车，或者拼房。女生。' },
    author: 'ConcertBuddy',
    tags: ['🎶 Music', '🚗 Carpool', '🤝 Team Up', '🎉 Event', '🇨🇳 Chinese Content'],
    tagWeights: { '🎶 Music': 2.0, '🎉 Event': 1.5, '🚗 Carpool': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=242',
    likes: 120,
  },
  {
    id: '243',
    title: { en: 'Tax return: TurboTax vs CPA', zh: '报税求助：TurboTax 还是找 CPA？' },
    content: { en: 'Have some stocks and crypto. Is TT enough?', zh: '有一些股票和加密货币。TurboTax 够用吗？' },
    author: 'TaxNoob',
    tags: ['💸 Money', '📝 Taxes', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=243',
    likes: 340,
  },
  {
    id: '244',
    title: { en: 'Best bubble tea in Berkeley? (Not Feng Cha)', zh: 'Berkeley 奶茶天花板是谁？（除了奉茶）' },
    content: { en: 'Looking for fresh milk tea, not powder.', zh: '想喝鲜奶做的，不要奶精粉。' },
    author: 'BobaQueen',
    tags: ['🍱 Foodie', '🧋 Boba', '🐻 UC Berkeley', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=244',
    likes: 550,
  },
  {
    id: '245',
    title: { en: 'H1B didn\'t get picked, Plan B?', zh: 'H1B 没抽中，Day 1 CPT 还是回国？' },
    content: { en: 'Really don\'t want to leave yet. Recommendations for CPT schools?', zh: '还不想回去。求推荐靠谱的 CPT 学校。' },
    author: 'VisaStress2',
    tags: ['🛂 Visa/H1B', '🎓 CPT', '😰 Anxiety', '❓ Question', '🇨🇳 Chinese Content'],
    tagWeights: { '🛂 Visa/H1B': 2.5, '🎓 CPT': 2.0, '😰 Anxiety': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=245',
    likes: 1800,
  },
  {
    id: '246',
    title: { en: 'My cat keeps scratching the sofa', zh: '猫咪老是抓沙发怎么办？' },
    content: { en: 'Bought scratchers but he ignores them.', zh: '买了猫抓板他根本不理。真皮沙发要烂了。' },
    author: 'CatOwner',
    tags: ['🐾 Pets', '🐱 Cat', '🆘 Help Needed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=246',
    likes: 230,
  },
  {
    id: '247',
    title: { en: 'Oppenheimer 70mm IMAX tickets', zh: '奥本海默 70mm IMAX 票真的难抢' },
    content: { en: 'Metreon SF is fully booked for weeks.', zh: '旧金山 Metreon 几周的票都没了。' },
    author: 'MovieFan',
    tags: ['🍿 Entertainment', '🎬 Movies', '🌉 San Francisco', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=247',
    likes: 410,
  },
  {
    id: '248',
    title: { en: 'Is Computer Science dead?', zh: 'CS 真的死了吗？24届毕业生一片哀嚎' },
    content: { en: 'Zero interviews after 500 applications. Should I switch to nursing?', zh: '投了500个还是0面试。我是不是该转行去读护理？' },
    author: 'DesperateGrad',
    tags: ['💻 Computer Science', '📉 Layoffs', '😰 Anxiety', '💼 Career', '🇨🇳 Chinese Content'],
    tagWeights: { '💻 Computer Science': 2.0, '📉 Layoffs': 2.0, '😰 Anxiety': 1.5, '💼 Career': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=248',
    likes: 2500,
  },
  {
    id: '249',
    title: { en: 'Costco Gold Bars', zh: 'Costco 的金条值得买吗？' },
    content: { en: 'They sell out in minutes. Is it a good investment?', zh: '几分钟就抢光了。保值吗？' },
    author: 'GoldDigger',
    tags: ['💰 Investing', '🛒 Costco', '💸 Money', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=249',
    likes: 890,
  },
  {
    id: '250',
    title: { en: 'Why is Stanford Shopping Center so nice?', zh: 'Stanford Shopping Center 真的太好逛了' },
    content: { en: 'The gardens and open air vibe are perfect.', zh: '花园式的设计，露天逛街太舒服了。' },
    author: 'Shopaholic',
    tags: ['🛍️ Shopping', '🌲 Stanford', '✨ Aesthetic', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=250',
    likes: 340,
  },
  {
    id: '251',
    title: { en: 'Car window smashed in Oakland', zh: '在 Oakland 吃饭车窗被砸了' },
    content: { en: 'Nothing was inside. Why?? Just cost me $300 deductible.', zh: '里面明明啥都没放。为什么要砸？白白损失300刀。' },
    author: 'OaklandVictim',
    tags: ['🚗 Cars', '😰 Scary', '😡 Rant', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=251',
    likes: 1200,
  },
  {
    id: '252',
    title: { en: 'Any badminton courts open late?', zh: '湾区有开到比较晚的羽毛球馆吗？' },
    content: { en: 'Want to play after work around 9pm.', zh: '想下班后9点左右去打球。' },
    author: 'SportsNight',
    tags: ['🏸 Badminton', '🌉 Bay Area', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=252',
    likes: 150,
  },
  {
    id: '253',
    title: { en: 'Best credit card for groceries?', zh: '买菜用哪张信用卡返现最高？' },
    content: { en: 'Amex Gold vs Citi Custom Cash?', zh: 'Amex Gold 还是 Citi Custom Cash？' },
    author: 'PointsHacker',
    tags: ['💸 Money', '💳 Credit Cards', '🥦 Groceries', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=253',
    likes: 560,
  },
  {
    id: '254',
    title: { en: 'Girl\'s trip to Napa Valley', zh: '周末和闺蜜去 Napa 喝酒拍照' },
    content: { en: 'Castello di Amorosa is beautiful but crowded.', zh: '城堡酒庄很美，但是人真的好多。' },
    author: 'WineLover',
    tags: ['🍷 Wine', '✈️ Travel', '📸 Photography', '✨ Aesthetic', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=254',
    likes: 780,
  },
  {
    id: '255',
    title: { en: 'Moving to New York from SF?', zh: '从湾区搬去纽约，值得吗？' },
    content: { en: 'Tired of the suburbs. Want city life.', zh: '受够了这里的大农村生活。想去真正的城市。' },
    author: 'CityDreamer',
    tags: ['✈️ Relocation', '🗽 NYC', '🌉 San Francisco', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=255',
    likes: 920,
  },
  {
    id: '256',
    title: { en: 'Learning French on Duolingo', zh: '在多邻国学法语的第50天' },
    content: { en: 'Is it actually useful for conversation?', zh: '感觉只会做题，这对话真的有用吗？' },
    author: 'LangStudent',
    tags: ['🎓 Learning', '🦉 Duolingo', '🇫🇷 French', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=256',
    likes: 210,
  },
  {
    id: '257',
    title: { en: 'My dog has separation anxiety', zh: '狗子有分离焦虑症怎么办？' },
    content: { en: 'Barks non-stop when I leave. Neighbors complained.', zh: '我一走就狂叫。邻居投诉了。' },
    author: 'DogMom',
    tags: ['🐾 Pets', '🐶 Dog', '🆘 Advice Needed', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=257',
    likes: 440,
  },
  {
    id: '258',
    title: { en: 'Good tailor for altering jeans?', zh: '求推荐改牛仔裤腰围的裁缝' },
    content: { en: 'Waist is too big, hips fit perfectly. South Bay area.', zh: '腰太大了，臀部刚好。南湾附近。' },
    author: 'FashionHelp',
    tags: ['💅 Fashion', '🛠️ Practical', '🌉 Bay Area', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=258',
    likes: 180,
  },
  {
    id: '259',
    title: { en: 'Who is watching "Blossoms Shanghai"?', zh: '有人在看《繁花》吗？王家卫太会拍了' },
    content: { en: 'The cinematography is top tier. Hu Ge is so handsome.', zh: '这光影，这运镜，绝了。胡歌好帅。' },
    author: 'DramaFan',
    tags: ['📺 TV Show', '🎬 Cinematography', '🇨🇳 Chinese Content', '👍 Recommendation'],
    imageUrl: 'https://picsum.photos/400/300?random=259',
    likes: 1500,
  },
  {
    id: '260',
    title: { en: 'Layoff package negotiation', zh: '裁员大礼包可以谈吗？' },
    content: { en: 'They offered 2 months. Can I ask for more?', zh: '只给了两个月。能多要点吗？' },
    author: 'LayoffHelp',
    tags: ['📉 Layoff', '🗣️ Negotiation', '💼 Career', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=260',
    likes: 670,
  },
  {
    id: '261',
    title: { en: 'Best place to buy furniture on budget?', zh: '预算有限，去哪里买家具？' },
    content: { en: 'IKEA is okay but want something unique. FB Marketplace?', zh: '宜家太大众了。Facebook Marketplace 靠谱吗？' },
    author: 'NewHome',
    tags: ['🏠 Renting', '🛒 Shopping', '💸 Money Saving', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=261',
    likes: 320,
  },
  {
    id: '262',
    title: { en: 'Dealing with aggressive homeless in BART', zh: 'BART 上遇到攻击性很强的流浪汉' },
    content: { en: 'He was screaming at everyone. I was terrified.', zh: '对着所有人大吼大叫。吓死我了。' },
    author: 'CommuterSafe',
    tags: ['🚄 Public Transit', '😰 Scary', '🌉 Bay Area', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=262',
    likes: 890,
  },
  {
    id: '263',
    title: { en: 'Any UX Designer jobs?', zh: '现在的市场还有 UX 设计师的坑吗？' },
    content: { en: 'Feels like everyone is hiring engineers only.', zh: '感觉都在招工程师，设计岗好少。' },
    author: 'UXDesign',
    tags: ['🎨 Design', '💼 Job Search', '😰 Anxiety', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=263',
    likes: 510,
  },
  {
    id: '264',
    title: { en: 'Making kimchi at home', zh: '第一次在家做泡菜，成功！' },
    content: { en: 'It\'s actually easier than I thought. Recipe below.', zh: '比想象中简单多了。方子放在评论区。' },
    author: 'HomeCook',
    tags: ['🍱 Foodie', '🍳 Cooking', '🥬 Kimchi', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=264',
    likes: 420,
  },
  {
    id: '265',
    title: { en: 'Is Youtube Premium worth it?', zh: 'Youtube Premium 值得开吗？' },
    content: { en: 'Ads are getting out of control. 30 seconds unskippable?', zh: '广告越来越多了。30秒不可跳过？' },
    author: 'AdHater',
    tags: ['📺 Youtube', '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=265',
    likes: 770,
  },
  {
    id: '266',
    title: { en: 'My roommate steals my milk', zh: '室友偷喝我的牛奶' },
    content: { en: 'I marked the level with a pen. It dropped.', zh: '我在瓶子上做了记号。明显少了。' },
    author: 'RoommateProb',
    tags: ['👯 Roommate', '😡 Rant', '👿 Petty', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=266',
    likes: 330,
  },
  {
    id: '267',
    title: { en: 'Best Korean BBQ in K-town (LA)', zh: 'LA K-town 最好吃的烤肉是哪家？' },
    content: { en: 'Kang Ho Dong vs Quarters?', zh: '姜虎东还是 Quarters？' },
    author: 'KBBQLover',
    tags: ['🍱 Foodie', '🥓 KBBQ', '🌴 Los Angeles', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=267',
    likes: 560,
  },
  {
    id: '268',
    title: { en: 'How to make friends in Seattle Freeze?', zh: '西雅图 Freeze 是真的，怎么交朋友？' },
    content: { en: 'People are polite but cold. Hard to break into circles.', zh: '大家都很有礼貌但是很冷淡。很难融入圈子。' },
    author: 'SeattleNew',
    tags: ['🥂 Social', '🌲 Seattle', '😰 Anxiety', '🆘 Advice', '🇨🇳 Chinese Content'],
    tagWeights: { '🥂 Social': 2.5, '🌲 Seattle': 2.0, '🆘 Advice': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=268',
    likes: 410,
  },
  {
    id: '269',
    title: { en: 'Dating app profile review', zh: '帮我看下这个 Tinder Profile 哪里有问题？' },
    content: { en: 'Zero matches in a week. Be honest.', zh: '一周了0匹配。求狠批。' },
    author: 'SingleGuy',
    tags: ['💘 Dating', '📱 Tinder', '❓ Question', '🆘 Help', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=269',
    likes: 180,
  },
  {
    id: '270',
    title: { en: 'Any good dim sum in East Bay?', zh: '东湾有好吃的早茶吗？' },
    content: { en: 'Don\'t want to cross the bridge to SF.', zh: '不想过桥去三番。' },
    author: 'EastBayFood',
    tags: ['🍱 Foodie', '🥟 Dim Sum', '🌉 East Bay', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=270',
    likes: 290,
  },
  {
    id: '271',
    title: { en: 'Got rejected by USC', zh: '被 USC 拒了，心碎' },
    content: { en: 'My dream school. Stats: 3.8 GPA. What went wrong?', zh: '那是我的梦校啊。GPA 3.8。哪里出问题了？' },
    author: 'CollegeReject',
    tags: ['🏫 College', '💔 Heartbreak', '✌️ USC', '📝 Application', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=271',
    likes: 670,
  },
  {
    id: '272',
    title: { en: 'Visiting Yosemite in winter', zh: '冬天去优胜美地需要装雪链吗？' },
    content: { en: 'Is it dangerous to drive? We have a sedan.', zh: '开车危险吗？我们是轿车。' },
    author: 'YosemiteTrip',
    tags: ['🌲 Outdoors', '⛰️ Yosemite', '🚗 Driving', '❄️ Snow', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=272',
    likes: 340,
  },
  {
    id: '273',
    title: { en: 'Buying a used piano', zh: '想买个二手钢琴，怎么验琴？' },
    content: { en: 'Found a Yamaha U1 on Craigslist. Good price.', zh: '在 Craigslist 看到个雅马哈 U1。价格不错。' },
    author: 'PianoMom',
    tags: ['🎹 Music', '🛒 Shopping', '❓ Question', '🛠️ Practical', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=273',
    likes: 120,
  },
  {
    id: '274',
    title: { en: 'Renewing passport in SF consulate', zh: '旧金山领事馆换护照攻略' },
    content: { en: 'Timeline and photo requirements.', zh: '时间线和照片要求分享。' },
    author: 'PassportHelp',
    tags: ['🛂 Visa', '🇨🇳 China', '📘 Guide', '🛠️ Practical', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=274',
    likes: 890,
  },
  {
    id: '275',
    title: { en: 'Any tennis coach recommendations?', zh: '求推荐靠谱的网球教练' },
    content: { en: 'Beginner level. Sunnyvale area.', zh: '零基础。Sunnyvale 附近。' },
    author: 'TennisFan',
    tags: ['🎾 Tennis', '🏃 Fitness', '🌉 Bay Area', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=275',
    likes: 90,
  },
  {
    id: '276',
    title: { en: 'Why is DMV so slow?', zh: 'DMV 效率还能再低点吗？' },
    content: { en: 'Waited 4 hours even with appointment.', zh: '有预约还等了4个小时。' },
    author: 'DmvHater',
    tags: ['😡 Rant', '🚗 DMV', '⏳ Waiting', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=276',
    likes: 1100,
  },
  {
    id: '277',
    title: { en: 'Best matcha latte in SF?', zh: 'SF 哪家抹茶拿铁最正宗？' },
    content: { en: 'Stonemill Matcha is good but line is crazy.', zh: 'Stonemill 不错但是排队太长了。' },
    author: 'MatchaLover',
    tags: ['🍵 Matcha', '☕ Coffee Shop', '🌉 San Francisco', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=277',
    likes: 330,
  },
  {
    id: '278',
    title: { en: 'Costco tire center experience', zh: 'Costco 换轮胎体验' },
    content: { en: 'Good price but appointment system is messy.', zh: '价格是好，但是预约系统太乱了。' },
    author: 'CarMaint',
    tags: ['🚗 Cars', '🛒 Costco', '📝 Review', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=278',
    likes: 210,
  },
  {
    id: '279',
    title: { en: 'Learning golf, need advice', zh: '刚开始学高尔夫，求建议' },
    content: { en: 'Should I buy a full set of clubs or rent?', zh: '该直接买一套杆还是先租？' },
    author: 'GolfNewbie',
    tags: ['⛳ Golf', '🏃 Fitness', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=279',
    likes: 150,
  },
  {
    id: '280',
    title: { en: 'Is it safe to walk in downtown LA?', zh: 'LA Downtown 晚上走路安全吗？' },
    content: { en: 'Going to a concert at Crypto.com arena.', zh: '要去 Crypto.com 体育馆看演唱会。' },
    author: 'SafetyCheck',
    tags: ['🌴 Los Angeles', '🛡️ Safety', '❓ Question', '😰 Scary', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=280',
    likes: 450,
  },
  {
    id: '281',
    title: { en: 'Best Japanese supermarket?', zh: 'Mitsuwa, Nijiya, Tokyo Central 哪家强？' },
    content: { en: 'Looking for best sushi grade fish.', zh: '想买刺身级别的鱼。' },
    author: 'Jfoodie',
    tags: ['🍱 Foodie', '🛒 Groceries', '🇯🇵 Japanese Food', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=281',
    likes: 320,
  },
  {
    id: '282',
    title: { en: 'Applying for SSN as international student', zh: '留学生申请 SSN 全流程' },
    content: { en: 'Got a campus job. How long does card take?', zh: '找到了校内工作。卡多久能寄到？' },
    author: 'NewSSN',
    tags: ['🏫 College', '🛠️ Practical', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=282',
    likes: 670,
  },
  {
    id: '283',
    title: { en: 'My landlord entered without notice', zh: '房东没通知就直接进我房间' },
    content: { en: 'Is this illegal? I feel violated.', zh: '这是违法的吧？感觉被冒犯了。' },
    author: 'PrivacyRenter',
    tags: ['🏠 Renting', '⚖️ Legal', '😡 Rant', '🆘 Help', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=283',
    likes: 1200,
  },
  {
    id: '284',
    title: { en: 'Best hiking trails with ocean view?', zh: '求推荐海景无敌的徒步路线' },
    content: { en: 'Mori Point is great but crowded.', zh: 'Mori Point 很美但是人多。' },
    author: 'OceanHike',
    tags: ['🥾 Hiking', '🌊 Ocean', '🌿 Nature', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=284',
    likes: 560,
  },
  {
    id: '285',
    title: { en: 'How much to tip movers?', zh: '搬家公司一般给多少小费？' },
    content: { en: '20%? They worked 4 hours.', zh: '20%？他们干了4个小时。' },
    author: 'MovingTip',
    tags: ['💸 Money', '📦 Moving', '🧾 Tipping', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=285',
    likes: 230,
  },
  {
    id: '286',
    title: { en: 'Where to buy cute stationary?', zh: '湾区哪里有卖好看的文具？' },
    content: { en: 'Maido is good but expensive.', zh: 'Maido 不错但是贵。' },
    author: 'StationaryLover',
    tags: ['🛍️ Shopping', '✏️ Stationary', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=286',
    likes: 180,
  },
  {
    id: '287',
    title: { en: 'Is 85C bakery overrated?', zh: '85度C 是不是过誉了？' },
    content: { en: 'The bread is so airy, not filling.', zh: '面包全是空气，吃不饱。' },
    author: 'BreadCritic',
    tags: ['🍱 Foodie', '🍞 Bakery', '👎 Negative', '💬 Discussion', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=287',
    likes: 410,
  },
  {
    id: '288',
    title: { en: 'Watching "The Eras Tour" movie', zh: '去看霉霉大电影啦！' },
    content: { en: 'Everyone was singing along. Great atmosphere.', zh: '全场大合唱。氛围太好了。' },
    author: 'SwiftieCN',
    tags: ['🎶 Music', '🎤 Taylor Swift', '🎉 Event', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=288',
    likes: 900,
  },
  {
    id: '289',
    title: { en: 'Applying for global entry conditionally approved', zh: 'Global Entry 过了 Conditionally Approved' },
    content: { en: 'Waiting for interview. Any tips on walk-in?', zh: '等面试。Walk-in 有什么技巧吗？' },
    author: 'GlobalEntry',
    tags: ['✈️ Travel', '🛂 Visa', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=289',
    likes: 330,
  },
  {
    id: '290',
    title: { en: 'Best place to sell used car?', zh: '卖二手车去哪里价格最好？' },
    content: { en: 'Carmax vs Carvana vs Private party?', zh: 'Carmax, Carvana 还是私人卖？' },
    author: 'CarSeller',
    tags: ['🚗 Cars', '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=290',
    likes: 550,
  },
  {
    id: '291',
    title: { en: 'Is it worth upgrading to M3 Macbook?', zh: 'M3 Macbook 值得升级吗？' },
    content: { en: 'Currently using M1. Is the speed difference noticeable?', zh: '现在用 M1。速度差别大吗？' },
    author: 'AppleUser',
    tags: ['💻 Tech', '🍎 Apple', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=291',
    likes: 280,
  },
  {
    id: '292',
    title: { en: 'Found a cockroach in my apartment', zh: '公寓里发现蟑螂了，崩溃' },
    content: { en: 'German cockroach. How to get rid of them?', zh: '是德国小蠊。怎么根除？' },
    author: 'PestControl',
    tags: ['🏠 Renting', '🪳 Pests', '😰 Scary', '🆘 Help', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=292',
    likes: 120,
  },
  {
    id: '293',
    title: { en: 'Best hot springs near Bay Area?', zh: '湾区周边最好的温泉？' },
    content: { en: 'Wilbur vs Orr? Need a relaxing weekend.', zh: 'Wilbur 还是 Orr？想过个放松的周末。' },
    author: 'RelaxMode',
    tags: ['🌿 Nature', '🛀 Hot Springs', '💆‍♀️ Self Care', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=293',
    likes: 450,
  },
  {
    id: '294',
    title: { en: 'Using ChatGPT to write cover letters', zh: '用 ChatGPT 写 Cover Letter 真香' },
    content: { en: 'Just edit it a bit. Saved me hours.', zh: '稍微改改就行。省了好多时间。' },
    author: 'JobHack',
    tags: ['💼 Career', '🤖 ChatGPT', '🛠️ Tools', '💡 Tips', '🇨🇳 Chinese Content'],
    tagWeights: { '🤖 ChatGPT': 2.0, '💼 Career': 1.5, '🛠️ Tools': 1.0 },
    imageUrl: 'https://picsum.photos/400/300?random=294',
    likes: 1300,
  },
  {
    id: '295',
    title: { en: 'My manager is a micromanager', zh: '遇到个微管理狂魔经理' },
    content: { en: 'Checks my status every hour. I can\'t breathe.', zh: '每小时查岗。我要窒息了。' },
    author: 'WorkStress',
    tags: ['💼 Career', '😡 Rant', '😰 Anxiety', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=295',
    likes: 890,
  },
  {
    id: '296',
    title: { en: 'Best place to see bioluminescence?', zh: '哪里能看到蓝眼泪荧光海？' },
    content: { en: 'Tomales Bay? When is the best season?', zh: 'Tomales Bay 吗？什么季节最好？' },
    author: 'NatureLover2',
    tags: ['🌿 Nature', '🌊 Ocean', '✨ Aesthetic', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=296',
    likes: 670,
  },
  {
    id: '297',
    title: { en: 'Getting a cat: Boy or Girl?', zh: '养猫选公的还是母的？' },
    content: { en: 'Which one is more affectionate?', zh: '哪个更粘人？' },
    author: 'NewCat',
    tags: ['🐾 Pets', '🐱 Cat', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=297',
    likes: 310,
  },
  {
    id: '298',
    title: { en: 'Is ClassPass worth it?', zh: 'ClassPass 值得办吗？' },
    content: { en: 'Credits system is confusing. Can I save money?', zh: '点数系统好晕。真的能省钱吗？' },
    author: 'FitnessGirl',
    tags: ['🏃 Fitness', '💸 Money', '❓ Question', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=298',
    likes: 240,
  },
  {
    id: '299',
    title: { en: 'I feel lonely in America', zh: '在美国感觉好孤独' },
    content: { en: 'Missing family and food. Holidays are the hardest.', zh: '想家，想好吃的。过节最难熬。' },
    author: 'Homesick',
    tags: ['🏠 Homesick', '🧘 Loneliness', '🎭 Emotional', '🇨🇳 Chinese Content'],
    imageUrl: 'https://picsum.photos/400/300?random=299',
    likes: 1500,
  },
  
  // --- NEW ENTERTAINMENT & PET POSTS (400-414) ---
  {
    id: '400',
    title: { en: 'My cat\'s reaction to durian', zh: '我家猫闻到榴莲的反应，笑死我了' },
    content: { en: 'He tried to bury it like poop. The disrespect.', zh: '他闻了一下居然想把它埋了。太不给面子了。' },
    author: 'CatSlave101',
    tags: ['🐱 Cat', '🐾 Pets', '🤣 Funny', '✨ Healing', '🇨🇳 Chinese Content'],
    tagWeights: { '🐱 Cat': 2.5, '🤣 Funny': 2.0, '✨ Healing': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=400',
    likes: 8800,
  },
  {
    id: '401',
    title: { en: 'Golden Retriever puppy first swim', zh: '金毛幼犬第一次游泳' },
    content: { en: 'Look at those little paws! He was so brave.', zh: '看那小爪子扑腾的！他太勇敢了。' },
    author: 'GoldieMom',
    tags: ['🐶 Dog', '🐾 Pets', '✨ Healing', '🌊 Ocean', '🇨🇳 Chinese Content'],
    tagWeights: { '🐶 Dog': 2.5, '✨ Healing': 2.0, '🐾 Pets': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=401',
    likes: 12000,
  },
  {
    id: '402',
    title: { en: 'Watching "Friends" for the 10th time', zh: '第十遍重刷《老友记》' },
    content: { en: 'It never gets old. Joey is my spirit animal.', zh: '永远看不腻。Joey 简直是我的精神图腾。' },
    author: 'SitcomFan',
    tags: ['📺 TV Show', '🍿 Entertainment', '✨ Nostalgia', '🇺🇸 USA Culture', '🇨🇳 Chinese Content'],
    tagWeights: { '📺 TV Show': 2.5, '🍿 Entertainment': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=402',
    likes: 5600,
  },
  {
    id: '403',
    title: { en: 'My husky is so dramatic', zh: '哈士奇这种生物真的太戏精了' },
    content: { en: 'Screaming because I wouldn\'t give him a second treat.', zh: '因为我不给第二块零食，他在地上打滚嚎叫。' },
    author: 'HuskyDad',
    tags: ['🐶 Dog', '🐾 Pets', '🤣 Funny', '🎭 Drama', '🇨🇳 Chinese Content'],
    tagWeights: { '🐶 Dog': 2.5, '🤣 Funny': 2.0, '🎭 Drama': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=403',
    likes: 9200,
  },
  {
    id: '404',
    title: { en: 'Top 5 relaxing switch games', zh: '除了动森，还有哪些治愈系 Switch 游戏？' },
    content: { en: 'Stardew Valley, Spiritfarer... need recommendations.', zh: '星露谷，灵魂摆渡人... 求推荐不肝的。' },
    author: 'GamerGirl',
    tags: ['🎮 Gaming', '✨ Healing', '🍿 Entertainment', '🕹️ Switch', '🇨🇳 Chinese Content'],
    tagWeights: { '🎮 Gaming': 2.5, '✨ Healing': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=404',
    likes: 3400,
  },
  {
    id: '405',
    title: { en: 'Corgi butts drive me crazy', zh: '柯基的屁股为什么这么好捏？' },
    content: { en: 'It\'s like a loaf of bread. I can\'t stop poking it.', zh: '像刚出炉的面包。完全停不下来。' },
    author: 'CorgiLover',
    tags: ['🐶 Dog', '🐾 Pets', '✨ Healing', '🍑 Corgi', '🇨🇳 Chinese Content'],
    tagWeights: { '🐶 Dog': 2.5, '✨ Healing': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=405',
    likes: 15000,
  },
  {
    id: '406',
    title: { en: 'Just watched "Dune 2", mind blown', zh: '看完《沙丘2》，彻底震撼了' },
    content: { en: 'The visuals, the sound. IMAX is a must.', zh: '这画面，这音效。必须看 IMAX。' },
    author: 'MovieBuff2',
    tags: ['🎬 Movies', '🍿 Entertainment', '🌌 Sci-Fi', '👍 Recommendation', '🇨🇳 Chinese Content'],
    tagWeights: { '🎬 Movies': 2.5, '🍿 Entertainment': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=406',
    likes: 7800,
  },
  {
    id: '407',
    title: { en: 'Cat sleeping positions explained', zh: '猫咪奇葩睡姿大赏' },
    content: { en: 'Why does he sleep like a pretzel? Is he broken?', zh: '为什么要扭成麻花睡？他是没有骨头吗？' },
    author: 'MeowMeow',
    tags: ['🐱 Cat', '🐾 Pets', '🤣 Funny', '💤 Sleep', '🇨🇳 Chinese Content'],
    tagWeights: { '🐱 Cat': 2.5, '🤣 Funny': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=407',
    likes: 4500,
  },
  {
    id: '408',
    title: { en: 'Samoyed: The smiling angel', zh: '萨摩耶：行走的蒲公英' },
    content: { en: 'So cute but so much shedding. Worth it.', zh: '太可爱了，但是掉毛真的恐怖。不过值了。' },
    author: 'CloudDog',
    tags: ['🐶 Dog', '🐾 Pets', '✨ Healing', '☁️ Fluffy', '🇨🇳 Chinese Content'],
    tagWeights: { '🐶 Dog': 2.5, '✨ Healing': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=408',
    likes: 11000,
  },
  {
    id: '409',
    title: { en: 'Cyberpunk 2077 Phantom Liberty', zh: '赛博朋克2077往日之影，好玩吗？' },
    content: { en: 'Is the DLC story good? Thinking of buying.', zh: 'DLC 剧情好吗？在犹豫要不要买。' },
    author: 'CyberPlayer',
    tags: ['🎮 Gaming', '🍿 Entertainment', '🤖 Sci-Fi', '❓ Question', '🇨🇳 Chinese Content'],
    tagWeights: { '🎮 Gaming': 2.5, '🍿 Entertainment': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=409',
    likes: 2100,
  },
  {
    id: '410',
    title: { en: 'Orange cat behavior is real', zh: '大橘为重，十橘九胖' },
    content: { en: 'He ate my dinner while I went to the bathroom.', zh: '我就去个厕所，他把我的晚饭吃了。' },
    author: 'FatCatOwner',
    tags: ['🐱 Cat', '🐾 Pets', '🤣 Funny', '🍊 Orange Cat', '🇨🇳 Chinese Content'],
    tagWeights: { '🐱 Cat': 2.5, '🤣 Funny': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=410',
    likes: 6700,
  },
  {
    id: '411',
    title: { en: 'Concert makeup ideas', zh: '演唱会妆容分享，辣妹必看' },
    content: { en: 'Going to see Blackpink. Need glitter inspiration.', zh: '要去看 Blackpink。求亮片妆灵感。' },
    author: 'KpopFan2',
    tags: ['🎶 Music', '💅 Fashion', '💄 Beauty', '✨ Aesthetic', '🇨🇳 Chinese Content'],
    tagWeights: { '🎶 Music': 2.0, '💅 Fashion': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=411',
    likes: 3200,
  },
  {
    id: '412',
    title: { en: 'Dog side eye meme', zh: '狗狗嫌弃的眼神（表情包自取）' },
    content: { en: 'When you pretend to throw the ball but don\'t.', zh: '当你假装扔球但是没扔的时候。' },
    author: 'DogMemes',
    tags: ['🐶 Dog', '🐾 Pets', '🤣 Funny', '🖼️ Meme', '🇨🇳 Chinese Content'],
    tagWeights: { '🐶 Dog': 2.5, '🤣 Funny': 2.0 },
    imageUrl: 'https://picsum.photos/400/300?random=412',
    likes: 5400,
  },
  {
    id: '413',
    title: { en: 'Kitten kneading biscuits', zh: '沉浸式看小奶猫踩奶' },
    content: { en: 'The purring sound is so therapeutic.', zh: '这呼噜声简直是助眠神器。' },
    author: 'SleepyCat',
    tags: ['🐱 Cat', '🐾 Pets', '✨ Healing', '💤 Sleep', '🇨🇳 Chinese Content'],
    tagWeights: { '🐱 Cat': 2.5, '✨ Healing': 2.5 },
    imageUrl: 'https://picsum.photos/400/300?random=413',
    likes: 9900,
  },
  {
    id: '414',
    title: { en: 'Board game night gone wrong', zh: '桌游局友尽现场' },
    content: { en: 'Uno Draw 4 card ruined a 10 year friendship.', zh: '一张 Uno +4 牌毁了十年的友谊。' },
    author: 'UnoPlayer',
    tags: ['🎮 Gaming', '🤣 Funny', '🎲 Board Games', '🍿 Entertainment', '🇨🇳 Chinese Content'],
    tagWeights: { '🎮 Gaming': 1.5, '🤣 Funny': 2.5, '🍿 Entertainment': 1.5 },
    imageUrl: 'https://picsum.photos/400/300?random=414',
    likes: 4100,
  }
];