import { Post } from './types';

export const NEW_TAGS = [
  // ESL / Language Learning
  '🗣️ Speaking Club', '📖 Reading Comprehension', '🎙️ Pronunciation', '📝 TOEFL', '📝 IELTS',
  // Health / Pre-med
  '🏥 Pre-Med', '💊 Pharmacy', '🩺 Nursing', '🧬 Biology', '🔬 Lab Work', '🏃 Fitness',
  // Arts / Humanities
  '🎨 Fine Arts', '🎭 Drama', '📷 Photography', '🎬 Film Studies', '📚 Literature', '✏️ Creative Writing',
  '🎵 Band', '🥁 Drums', '🎻 Orchestra', '🎤 Karaoke',
  // Campus Community
  '🏳️‍🌈 LGBTQ+', '⛪ Faith', '🤝 Volunteering', '📣 Activism', '♿ Accessibility',
  // Financial Aid
  '🎓 Scholarships', '💰 FAFSA', '📋 Work-Study', '🏦 Student Loans',
  // Non-Bay Area / broader US campus
  '🏈 College Football', '🍻 Greek Life', '❄️ Snow Belt', '🌴 SoCal', '🤠 Texas',
  // Kpop / Music subcultures
  '🇰🇷 Kpop Fandom', '🎸 Indie Music', '🎧 DJ', '🎶 Concert',
  // Misc lifestyle
  '🧵 Thrifting', '💇 Hair', '💄 Skincare', '🪴 Plants', '🧘 Yoga', '☕ Coffee',
  '📦 Amazon', '🛒 Target', '🏋️ Gym', '🚴 Cycling', '🏕️ Camping',
];

export const ADDITIONAL_POSTS_5: Post[] = [
  // ===== ESL / TOEFL / Language Learning (10) =====
  {
    id: '600',
    title: { en: 'TOEFL Speaking Section: I froze and said nothing', zh: '托福口语考试：我大脑一片空白一个字没说出来' },
    content: { en: 'The beep went off and my mind went blank. 15 seconds of silence on the recording. How do I recover from this?', zh: '提示音响了我脑子一片空白。录音里15秒纯静音。我该怎么补救？' },
    author: 'FrozenInExam',
    tags: ['📝 TOEFL', '🗣️ TOEFL/IELTS', '🇺🇸 English Learning', '😰 Anxiety', '😭 Crying', '🎙️ Pronunciation', '🏫 Student Problems'],
    likes: 2340,
    imageUrl: 'https://picsum.photos/400/300?random=600',
  },
  {
    id: '601',
    title: { en: 'Free speaking partner: campus conversation club every Thursday', zh: '免费口语搭子：每周四校园对话俱乐部' },
    content: { en: 'No judgment zone. Native speakers volunteer to just chat with you about anything. Library Room 204.', zh: '零压力环境。母语者志愿者跟你聊天，话题随意。图书馆204室。' },
    author: 'ESLClubPres',
    tags: ['🗣️ Speaking Club', '🇺🇸 English Learning', '💬 ESL', '🚧 Language Barrier', '🏫 Campus Life', '🤝 Volunteering', '🟢 Green Flag'],
    likes: 890,
    imageUrl: 'https://picsum.photos/400/300?random=601',
  },
  {
    id: '602',
    title: { en: 'IELTS vs TOEFL: Which one is actually easier?', zh: 'IELTS 和 TOEFL 到底哪个更容易？过来人实测对比' },
    content: { en: 'Took both. IELTS speaking felt more natural but the writing grading is brutal. TOEFL reading is faster-paced. Depends on your strengths.', zh: '两个都考了。雅思口语更自然但写作评分残酷。托福阅读节奏更快。看你擅长什么。' },
    author: 'DualTestTaker',
    tags: ['📝 TOEFL', '📝 IELTS', '🗣️ TOEFL/IELTS', '🇺🇸 English Learning', '✍️ Writing', '💬 Discussion', '📘 Guide'],
    likes: 4500,
    imageUrl: 'https://picsum.photos/400/300?random=602',
  },
  {
    id: '603',
    title: { en: 'Professor talks too fast — I understand maybe 40%', zh: '教授语速太快了——我大概只听懂40%' },
    content: { en: 'Office hours help but I feel bad asking them to repeat everything. Anyone else record lectures?', zh: 'Office hours有帮助但我不好意思让他们什么都重复一遍。有人录课吗？' },
    author: 'ListeningStruggle',
    tags: ['🚧 Language Barrier', '💬 ESL', '🇺🇸 English Learning', '📖 Reading Comprehension', '🆘 Help', '😰 Anxiety', '🏫 Campus Life', '🌏 International Students'],
    likes: 3200,
    imageUrl: 'https://picsum.photos/400/300?random=603',
  },
  {
    id: '604',
    title: { en: 'How I went from TOEFL 79 to 108 in 3 months', zh: '三个月托福79到108，我的备考方法分享' },
    content: { en: 'Shadowing podcasts for speaking. Reading NYT editorials daily. Writing practice with Grammarly feedback. Consistency > cramming.', zh: '跟读播客练口语。每天读纽约时报社论。用Grammarly改作文。坚持 > 突击。' },
    author: 'TOEFLSurvivor',
    tags: ['📝 TOEFL', '🗣️ TOEFL/IELTS', '🇺🇸 English Learning', '📘 Guide', '✨ Inspirational', '🏆 Success Story', '💡 Study Tips'],
    likes: 6700,
    imageUrl: 'https://picsum.photos/400/300?random=604',
  },
  {
    id: '605',
    title: { en: 'Accent discrimination is real and nobody talks about it', zh: '口音歧视真的存在而且没人说' },
    content: { en: 'Got laughed at in a group project for mispronouncing "entrepreneur." These are the same people who can\'t say "你好" correctly.', zh: '小组作业里因为把entrepreneur念错被笑了。这些人连"你好"都说不标准。' },
    author: 'AccentAndProud',
    tags: ['🎙️ Pronunciation', '🚧 Language Barrier', '😡 Rant', '🌏 International Students', '🗣️ Real Talk', '🇺🇸 USA Culture'],
    likes: 8100,
    imageUrl: 'https://picsum.photos/400/300?random=605',
  },
  {
    id: '606',
    title: { en: 'Best YouTube channels for academic English', zh: '学术英语最好的YouTube频道推荐' },
    content: { en: 'English with Lucy for pronunciation. Jade for IELTS. Magoosh for TOEFL. Academic English Now for essay structure.', zh: 'English with Lucy练发音。Jade讲雅思。Magoosh搞托福。Academic English Now学论文结构。' },
    author: 'YTScholar',
    tags: ['🇺🇸 English Learning', '📖 Reading Comprehension', '💡 Study Tips', '📘 Guide', '🛠️ Tools', '🎙️ Pronunciation'],
    likes: 1560,
    imageUrl: 'https://picsum.photos/400/300?random=606',
  },
  {
    id: '607',
    title: { en: 'Writing center appointment saved my essay grade', zh: '写作中心预约救了我的论文成绩' },
    content: { en: 'The tutor didn\'t rewrite it for me but pointed out all my Chinglish patterns. Went from C+ to B+.', zh: '导师没帮我重写但指出了所有中式英语痕迹。从C+到B+。' },
    author: 'WritingCenterFan',
    tags: ['✍️ Writing', '💬 ESL', '🇺🇸 English Learning', '📄 Essay', '🏫 Campus Life', '🟢 Green Flag', '💡 Study Tips'],
    likes: 940,
    imageUrl: 'https://picsum.photos/400/300?random=607',
  },
  {
    id: '608',
    title: { en: 'Thinking in English vs translating in your head', zh: '用英文思考 vs 在脑子里翻译' },
    content: { en: 'The moment I stopped mentally translating from Chinese, my speaking fluency jumped. It took about 6 months of forcing myself.', zh: '当我不再在脑子里从中文翻译的那一刻，口语流利度飞跃了。花了大概6个月强迫自己。' },
    author: 'ThinkInEnglish',
    tags: ['🇺🇸 English Learning', '🗣️ Speaking Club', '🎙️ Pronunciation', '💬 ESL', '🤯 Mind Blown', '📖 Storytime'],
    likes: 5200,
    imageUrl: 'https://picsum.photos/400/300?random=608',
  },
  {
    id: '609',
    title: { en: 'Duolingo streak: 500 days and I still can\'t order coffee', zh: 'Duolingo打卡500天了我还是不会点咖啡' },
    content: { en: 'This owl has taught me nothing useful. "The bear drinks wine" won\'t help me at Starbucks.', zh: '这只猫头鹰什么有用的都没教我。"熊喝红酒"在星巴克根本用不上。' },
    author: 'DuolingoVictim',
    tags: ['🇺🇸 English Learning', '💬 ESL', '🤡 Clown World', '💀 Dead', '☕ Coffee', '😭 Crying'],
    likes: 12000,
    imageUrl: 'https://picsum.photos/400/300?random=609',
  },

  // ===== Pre-Med / Health / Nursing (10) =====
  {
    id: '610',
    title: { en: 'Pre-med at a community college: Is it even possible?', zh: '社区大学Pre-med：到底可不可行？' },
    content: { en: 'Yes, but you need to network harder. Find research opportunities early and ace organic chem.', zh: '可以，但你需要更努力地社交。尽早找研究机会，有机化学一定要考好。' },
    author: 'CCPreMed',
    tags: ['🏥 Pre-Med', '🏫 Community College', '🔬 Research', '🧬 Biology', '📘 Guide', '🔄 UC Transfer', '💡 Study Tips'],
    likes: 3400,
    imageUrl: 'https://picsum.photos/400/300?random=610',
  },
  {
    id: '611',
    title: { en: 'Organic Chemistry destroyed my GPA and my will to live', zh: '有机化学毁了我的GPA和我的求生欲' },
    content: { en: 'I studied 40 hours for the midterm and got a 52. The curve saved me to a C. How is this class legal.', zh: '期中考试学了40个小时拿了52分。curve救我到C。这课合法吗。' },
    author: 'OrgoSurvivor',
    tags: ['🏥 Pre-Med', '🧬 Biology', '📚 Academic', '😡 Rant', '😰 Anxiety', '🧪 Science', '📝 GPA'],
    likes: 7800,
    imageUrl: 'https://picsum.photos/400/300?random=611',
  },
  {
    id: '612',
    title: { en: 'Clinical volunteering hours: where to start?', zh: '临床志愿者时长：从哪里开始？' },
    content: { en: 'Local hospital volunteer programs fill up fast. Apply in January for summer spots. Red Cross is always accepting.', zh: '本地医院志愿者名额很快满。一月份申请暑期名额。红十字会一直在招。' },
    author: 'FutureMD',
    tags: ['🏥 Pre-Med', '🤝 Volunteering', '🩺 Nursing', '📘 Guide', '💼 Career Advice', '🏫 Campus Life'],
    likes: 2100,
    imageUrl: 'https://picsum.photos/400/300?random=612',
  },
  {
    id: '613',
    title: { en: 'Nursing program waitlist is 2 years long???', zh: '护理项目等待名单要两年？？？' },
    content: { en: 'Applied to three programs. All 18-24 month waitlists. I\'ll be 30 before I even start clinicals.', zh: '申了三个项目。全部等18-24个月。我开始临床的时候都30了。' },
    author: 'WaitlistNurse',
    tags: ['🩺 Nursing', '🏥 Pre-Med', '😡 Rant', '🏫 Community College', '😰 Anxiety', '📋 Work-Study'],
    likes: 4300,
    imageUrl: 'https://picsum.photos/400/300?random=613',
  },
  {
    id: '614',
    title: { en: 'MCAT study plan: 6 months is not enough', zh: 'MCAT备考计划：6个月根本不够' },
    content: { en: 'Started with Kaplan, switched to Anki + UWorld. The CARS section is where international students suffer most.', zh: '从Kaplan开始，后来换成Anki + UWorld。CARS部分是留学生最痛苦的。' },
    author: 'MCATWarrior',
    tags: ['🏥 Pre-Med', '📚 Academic', '💡 Study Tips', '🛠️ Tools', '🇺🇸 English Learning', '📖 Reading Comprehension', '🧠 Advanced'],
    likes: 5600,
    imageUrl: 'https://picsum.photos/400/300?random=614',
  },
  {
    id: '615',
    title: { en: 'Anatomy lab: yes you will touch a real cadaver', zh: '解剖课：是的你会摸到真的尸体' },
    content: { en: 'First day was intense. The formaldehyde smell stays in your clothes. Bring a change of outfit.', zh: '第一天很震撼。甲醛味道会留在衣服上。带一套换的衣服。' },
    author: 'LabRat',
    tags: ['🏥 Pre-Med', '🔬 Lab Work', '🧬 Biology', '🧪 Science', '🤯 Mind Blown', '📖 Storytime', '🏫 Campus Life'],
    likes: 3900,
    imageUrl: 'https://picsum.photos/400/300?random=615',
  },
  {
    id: '616',
    title: { en: 'Pharmacy tech job while in school: worth it?', zh: '上学期间做药房技术员：值得吗？' },
    content: { en: 'Pay is decent ($18/hr), hours are flexible, and you learn drug names without trying. Great for pre-pharm students.', zh: '工资不错（$18/时），时间灵活，不知不觉就记住了药名。适合pre-pharm学生。' },
    author: 'PharmTech',
    tags: ['💊 Pharmacy', '📋 Work-Study', '💸 Student Discount', '🛠️ Practical', '💼 Career Advice', '🏫 Campus Life'],
    likes: 1200,
    imageUrl: 'https://picsum.photos/400/300?random=616',
  },
  {
    id: '617',
    title: { en: 'Mental health crisis on campus: where to get help', zh: '校园心理危机：去哪里寻求帮助' },
    content: { en: 'Counseling center offers 6 free sessions per semester. Crisis text line: text HOME to 741741. You are not alone.', zh: '咨询中心每学期提供6次免费咨询。危机短信热线：发HOME到741741。你不是一个人。' },
    author: 'CampusCares',
    tags: ['🧘 Mental Health', '😰 Anxiety', '🆘 Help', '🏫 Campus Life', '🟢 Green Flag', '🩺 Nursing', '♿ Accessibility'],
    likes: 9400,
    imageUrl: 'https://picsum.photos/400/300?random=617',
  },
  {
    id: '618',
    title: { en: 'Gym at 6am: the pre-med power move', zh: '早上6点去健身房：pre-med的power move' },
    content: { en: 'Started going before orgo lectures. My focus doubled. Also it\'s empty at 6am — no waiting for squat rack.', zh: '开始在有机化学课前去。注意力翻倍了。而且早上6点没人——不用等深蹲架。' },
    author: 'PreMedLifts',
    tags: ['🏋️ Gym', '🏃 Fitness', '🏥 Pre-Med', '⚡ Productivity', '🏫 Campus Life', '✨ Vibe'],
    likes: 2800,
    imageUrl: 'https://picsum.photos/400/300?random=618',
  },
  {
    id: '619',
    title: { en: 'DO vs MD: what\'s the actual difference?', zh: 'DO和MD到底有什么区别？' },
    content: { en: 'Both are fully licensed physicians. DO schools are generally easier to get into but you learn OMM on top of everything else.', zh: '都是正式执照医生。DO学校一般更容易进但除了所有内容还要学OMM。' },
    author: 'PreMedAdvisor',
    tags: ['🏥 Pre-Med', '❓ Question', '💬 Discussion', '📘 Guide', '💼 Career Advice', '🧬 Biology'],
    likes: 4100,
    imageUrl: 'https://picsum.photos/400/300?random=619',
  },

  // ===== Arts / Humanities / Creative (10) =====
  {
    id: '620',
    title: { en: 'Art history midterm: memorize 200 paintings in 3 days', zh: '艺术史期中：3天背200幅画' },
    content: { en: 'Quizlet saved me. Also, actually going to the museum helps more than staring at slides.', zh: 'Quizlet救了我。而且去博物馆看原作比盯幻灯片有用得多。' },
    author: 'ArtHistoryMajor',
    tags: ['🎨 Fine Arts', '🎨 Art', '📚 Academic', '💡 Study Tips', '🛠️ Tools', '😰 Anxiety'],
    likes: 1800,
    imageUrl: 'https://picsum.photos/400/300?random=620',
  },
  {
    id: '621',
    title: { en: 'Theater auditions: I got cast as a tree', zh: '话剧试镜：我被选为一棵树' },
    content: { en: 'Freshman year they put me in the background as literal foliage. But hey, it\'s a start.', zh: '大一他们把我放在背景里当植物。但至少是个开始。' },
    author: 'TreeActor',
    tags: ['🎭 Drama', '🎭 Theater', '📖 Storytime', '🤡 Clown World', '🏫 Campus Life', '✨ Vibe'],
    likes: 5600,
    imageUrl: 'https://picsum.photos/400/300?random=621',
  },
  {
    id: '622',
    title: { en: 'Photography class: my phone is not good enough?', zh: '摄影课：手机不够用？' },
    content: { en: 'Professor said iPhone is fine for the intro course. Don\'t buy a DSLR until you know you love it. Lightroom Mobile is free for students.', zh: '教授说入门课用iPhone就行。在确定自己真的喜欢之前别买单反。Lightroom手机版对学生免费。' },
    author: 'LensNewbie',
    tags: ['📷 Photography', '🎨 Fine Arts', '🛠️ Tools', '📘 Guide', '🏫 Campus Life', '💸 Student Discount', '💡 Study Tips'],
    likes: 2300,
    imageUrl: 'https://picsum.photos/400/300?random=622',
  },
  {
    id: '623',
    title: { en: 'Creative writing workshop: someone cried over my feedback', zh: '创意写作工作坊：有人因为我的反馈哭了' },
    content: { en: 'I said the dialogue felt unnatural. They took it personally. Is this workshop or therapy?', zh: '我说对话不太自然。他们当成人身攻击了。这是写作坊还是心理诊所？' },
    author: 'HonestCritic',
    tags: ['✏️ Creative Writing', '✍️ Writing', '📖 Storytime', '🤬 AITA', '😡 Rant', '🏫 Campus Life', '🎭 Emotional'],
    likes: 7200,
    imageUrl: 'https://picsum.photos/400/300?random=623',
  },
  {
    id: '624',
    title: { en: 'Film studies: we watched 4 hours of French cinema today', zh: '电影研究课：今天看了4小时法国电影' },
    content: { en: 'No subtitles. Black and white. Someone smokes for 20 minutes straight. Professor says it\'s "pure cinema." I fell asleep.', zh: '没字幕。黑白的。有人连抽了20分钟烟。教授说这是"纯电影"。我睡着了。' },
    author: 'NotCinephile',
    tags: ['🎬 Film Studies', '🎬 Movies', '📖 Storytime', '💀 Dead', '😐 Serious', '🏫 Campus Life', '📚 Academic'],
    likes: 4400,
    imageUrl: 'https://picsum.photos/400/300?random=624',
  },
  {
    id: '625',
    title: { en: 'Joined the jazz band — I can barely play', zh: '加入了爵士乐队——我几乎不会弹' },
    content: { en: 'They needed a bassist and I said I played bass. I played bass once. In Guitar Hero. Rehearsal is Thursday help.', zh: '他们缺一个贝斯手我说我会。我弹过一次贝斯。在Guitar Hero里。周四排练求救。' },
    author: 'FakeBassist',
    tags: ['🎵 Band', '🎶 Music', '📖 Storytime', '🤡 Clown World', '💀 Dead', '🏫 Campus Life', '🎸 Guitar'],
    likes: 9800,
    imageUrl: 'https://picsum.photos/400/300?random=625',
  },
  {
    id: '626',
    title: { en: 'Pottery class is the best elective I\'ve ever taken', zh: '陶艺课是我选过最好的选修课' },
    content: { en: 'Zero screens. Just clay and your hands. The 2 hours fly by and I leave feeling like a different person.', zh: '零屏幕。只有粘土和你的手。两小时一晃就过，出来感觉像换了个人。' },
    author: 'ClayTherapy',
    tags: ['🎨 Fine Arts', '🎨 Art', '🧘 Mental Health', '✨ Vibe', '🟢 Green Flag', '🏫 Campus Life', '🛠️ Practical'],
    likes: 6300,
    imageUrl: 'https://picsum.photos/400/300?random=626',
  },
  {
    id: '627',
    title: { en: 'English Literature major: "So what job will you get?"', zh: '英语文学专业："所以你能找什么工作？"' },
    content: { en: 'Every Thanksgiving. Every single one. I write better than all of you, Uncle Bob.', zh: '每个感恩节。每一个。我写得比你们所有人都好，Bob叔叔。' },
    author: 'LitMajorRage',
    tags: ['📚 Literature', '😡 Rant', '💼 Career Advice', '🏫 Campus Life', '🗣️ Real Talk', '🇺🇸 USA Culture'],
    likes: 11000,
    imageUrl: 'https://picsum.photos/400/300?random=627',
  },
  {
    id: '628',
    title: { en: 'Campus orchestra concert this Friday: free entry', zh: '校园管弦乐团本周五音乐会：免费入场' },
    content: { en: 'Performing Dvorak\'s New World Symphony. Yes, the meme one. It\'s actually beautiful live. Bring your student ID.', zh: '演奏德沃夏克新世界交响曲。对，那个meme的。现场听真的很美。带上学生证。' },
    author: 'OrchestraPR',
    tags: ['🎻 Orchestra', '🎶 Music', '🎶 Concert', '🏫 Campus Life', '💸 Student Discount', '✨ Vibe'],
    likes: 780,
    imageUrl: 'https://picsum.photos/400/300?random=628',
  },
  {
    id: '629',
    title: { en: 'KTV night: rented a room for $15/person', zh: 'KTV之夜：人均$15包了个房间' },
    content: { en: 'Screamed Jay Chou for 3 hours. My throat is gone but my soul is healed. Best stress relief before finals.', zh: '吼了三个小时周杰伦。嗓子没了但灵魂治愈了。期末前最好的减压方式。' },
    author: 'KTVKing',
    tags: ['🎤 Karaoke', '🎶 Music', '🥂 Social Life', '🏫 Campus Life', '✨ Vibe', '🇨🇳 Chinese Content', '💸 Student Discount'],
    likes: 3400,
    imageUrl: 'https://picsum.photos/400/300?random=629',
  },

  // ===== Scholarships / Financial Aid (8) =====
  {
    id: '630',
    title: { en: 'FAFSA deadline is approaching — don\'t miss free money', zh: 'FAFSA截止日期快到了——别错过白给的钱' },
    content: { en: 'Even if you think you won\'t qualify, APPLY. Many students leave money on the table. Takes 30 minutes.', zh: '就算你觉得自己不符合条件也要申请。很多学生白白放弃了这笔钱。只需30分钟。' },
    author: 'FinAidOffice',
    tags: ['💰 FAFSA', '🎓 Scholarships', '💸 Student Discount', '📘 Guide', '🆘 Help', '🏫 Campus Life'],
    likes: 4200,
    imageUrl: 'https://picsum.photos/400/300?random=630',
  },
  {
    id: '631',
    title: { en: 'Got a $5000 scholarship by writing about my cat', zh: '写了篇关于我家猫的文章拿了$5000奖学金' },
    content: { en: 'Niche scholarships are where it\'s at. "Pet owners pursuing STEM" — yes that\'s a real scholarship.', zh: '小众奖学金才是真的。"养宠物的STEM学生"——对这是真实存在的奖学金。' },
    author: 'ScholarshipHunter',
    tags: ['🎓 Scholarships', '📖 Storytime', '💸 Money', '🐱 Cat', '✨ Inspirational', '💡 Study Tips', '🤯 Mind Blown'],
    likes: 8900,
    imageUrl: 'https://picsum.photos/400/300?random=631',
  },
  {
    id: '632',
    title: { en: 'Work-study in the library: easiest job on campus', zh: '图书馆勤工俭学：全校最轻松的工作' },
    content: { en: 'You literally sit at the desk and do homework. Occasionally someone asks where the printer is. $15/hr.', zh: '你就坐在前台写作业。偶尔有人问打印机在哪。$15/时。' },
    author: 'LibraryWorker',
    tags: ['📋 Work-Study', '💸 Student Discount', '💸 Money', '🏫 Campus Life', '🟢 Green Flag', '📘 Guide'],
    likes: 5600,
    imageUrl: 'https://picsum.photos/400/300?random=632',
  },
  {
    id: '633',
    title: { en: 'Student loan interest is criminal', zh: '学生贷款利息简直犯罪' },
    content: { en: 'I owe $45K for a degree that pays $40K/year. At 6.8% interest, I\'ll be paying this off until I\'m 45.', zh: '一个年薪4万的学位让我欠了4.5万。6.8%的利率，我要还到45岁。' },
    author: 'DebtTrap',
    tags: ['🏦 Student Loans', '💸 Cost of Living', '😡 Rant', '💬 Discussion', '🇺🇸 USA Culture', '🔥 Hot Take'],
    likes: 12400,
    imageUrl: 'https://picsum.photos/400/300?random=633',
  },
  {
    id: '634',
    title: { en: 'International students can\'t get FAFSA but here are alternatives', zh: '留学生拿不了FAFSA但这些是替代方案' },
    content: { en: 'CSS Profile, institutional aid, private scholarships for F-1 students. List of 20 that don\'t require citizenship.', zh: 'CSS Profile、校内资助、F-1学生可申请的私人奖学金。20个不要求公民身份的名单。' },
    author: 'IntlFinAid',
    tags: ['🎓 Scholarships', '💰 FAFSA', '🌏 International Students', '📘 Guide', '💸 Money', '🆘 Help'],
    likes: 6700,
    imageUrl: 'https://picsum.photos/400/300?random=634',
  },
  {
    id: '635',
    title: { en: 'Textbook hack: don\'t buy them until week 2', zh: '教科书省钱攻略：第二周之前别买' },
    content: { en: 'Half the time professors don\'t actually use the "required" textbook. Library has 2-hour reserves. LibGen exists.', zh: '一半的时候教授根本不用"必需"的教科书。图书馆有2小时借阅。LibGen存在。' },
    author: 'TextbookRealist',
    tags: ['💸 Student Discount', '💸 Money Saving', '📘 Guide', '🏫 Campus Life', '💡 Study Tips', '🛠️ Practical'],
    likes: 7800,
    imageUrl: 'https://picsum.photos/400/300?random=635',
  },
  {
    id: '636',
    title: { en: 'Campus food pantry: no shame in using it', zh: '校园食品银行：用它不丢人' },
    content: { en: 'Free groceries every Tuesday. No income verification needed. I\'ve been going all semester and it saves me $200/month.', zh: '每周二免费领食物。不需要收入证明。我去了一学期每月省$200。' },
    author: 'FoodPantryUser',
    tags: ['💸 Money Saving', '🍱 Foodie', '🏫 Campus Life', '🆘 Help', '🟢 Green Flag', '🤝 Volunteering'],
    likes: 3400,
    imageUrl: 'https://picsum.photos/400/300?random=636',
  },
  {
    id: '637',
    title: { en: 'BOG waiver covered my entire tuition at CC', zh: 'BOG减免覆盖了我在社区大学的全部学费' },
    content: { en: 'If your family income is below the threshold, California CC is literally free. Apply through the financial aid office.', zh: '如果家庭收入低于门槛，加州社区大学是真的免费。通过财务援助办公室申请。' },
    author: 'FreeTuition',
    tags: ['💰 FAFSA', '🎓 Scholarships', '🏫 Community College', '💸 Money Saving', '📘 Guide', '🌉 Bay Area'],
    likes: 5100,
    imageUrl: 'https://picsum.photos/400/300?random=637',
  },

  // ===== Campus Community / Identity / Orgs (10) =====
  {
    id: '638',
    title: { en: 'LGBTQ+ center on campus changed my life', zh: '校园LGBTQ+中心改变了我的人生' },
    content: { en: 'Found my first real friend group there. Weekly movie nights, study sessions, and free snacks. Safe space is real.', zh: '在那里找到了第一个真正的朋友圈。每周电影之夜、学习小组和免费零食。安全空间是真的。' },
    author: 'ProudAndStudying',
    tags: ['🏳️‍🌈 LGBTQ+', '🏫 Campus Life', '🥂 Social Life', '🟢 Green Flag', '📖 Storytime', '🧘 Mental Health'],
    likes: 6200,
    imageUrl: 'https://picsum.photos/400/300?random=638',
  },
  {
    id: '639',
    title: { en: 'Chinese Student Association lunar new year gala was incredible', zh: '中国学生会春晚太精彩了' },
    content: { en: 'Traditional dance, stand-up comedy in Chinglish, and 500 dumplings made by volunteers. Felt like home.', zh: '传统舞蹈、中英混搭脱口秀、还有志愿者包的500个饺子。像回家一样。' },
    author: 'CSAMember',
    tags: ['🏫 Campus Life', '🥂 Social Life', '🇨🇳 Chinese Content', '🤝 Volunteering', '🍱 Foodie', '✨ Vibe', '📖 Storytime'],
    likes: 4800,
    imageUrl: 'https://picsum.photos/400/300?random=639',
  },
  {
    id: '640',
    title: { en: 'Started a club with 3 members. Now we have 80.', zh: '创建社团时只有3个人。现在有80个了。' },
    content: { en: 'Board game club. All it took was a poster in the student union and free pizza at the first meeting.', zh: '桌游社团。只需要在学生会贴个海报、第一次活动准备免费披萨。' },
    author: 'ClubFounder',
    tags: ['🏫 Campus Life', '🎮 Gaming', '🥂 Social Life', '✨ Inspirational', '📖 Storytime', '🤝 Volunteering'],
    likes: 7400,
    imageUrl: 'https://picsum.photos/400/300?random=640',
  },
  {
    id: '641',
    title: { en: 'Disability services got me extra time on exams', zh: '残疾学生服务让我考试有了额外时间' },
    content: { en: 'ADHD diagnosis + documentation = 1.5x time. It\'s not cheating, it\'s equity. Don\'t be afraid to register.', zh: 'ADHD诊断+文件 = 1.5倍时间。这不是作弊，是公平。别害怕注册。' },
    author: 'ADHDStudent',
    tags: ['♿ Accessibility', '🏫 Campus Life', '🧘 Mental Health', '📘 Guide', '🆘 Help', '💡 Study Tips'],
    likes: 5300,
    imageUrl: 'https://picsum.photos/400/300?random=641',
  },
  {
    id: '642',
    title: { en: 'Volunteered at Habitat for Humanity — built an actual wall', zh: '在仁人家园做志愿者——真的砌了一面墙' },
    content: { en: 'My first time using a power drill. The wall is slightly crooked but the homeowner hugged us. Worth it.', zh: '第一次用电钻。墙有点歪但房主拥抱了我们。值了。' },
    author: 'HabitatVolunteer',
    tags: ['🤝 Volunteering', '🏫 Campus Life', '📖 Storytime', '🟢 Green Flag', '🛠️ Practical', '✨ Vibe'],
    likes: 3100,
    imageUrl: 'https://picsum.photos/400/300?random=642',
  },
  {
    id: '643',
    title: { en: 'Campus interfaith dinner: ate food from 12 cultures', zh: '校园跨宗教晚餐：吃到了12种文化的食物' },
    content: { en: 'Muslim students made biryani, Jewish students brought challah, Sikh community served langar. My stomach and heart are full.', zh: '穆斯林同学做了biryani，犹太同学带了哈拉面包，锡克教社区提供了langar。我的胃和心都满了。' },
    author: 'InterfaithFoodie',
    tags: ['⛪ Faith', '🍱 Foodie', '🏫 Campus Life', '🥂 Social Life', '🌏 International Students', '🤝 Volunteering', '✨ Vibe'],
    likes: 4600,
    imageUrl: 'https://picsum.photos/400/300?random=643',
  },
  {
    id: '644',
    title: { en: 'Student government is 90% resume padding', zh: '学生会90%都是为了简历好看' },
    content: { en: 'They debated for 2 hours about changing the font on the newsletter. Real change happens in mutual aid groups.', zh: '他们花了两小时讨论改通讯的字体。真正的改变在互助小组里。' },
    author: 'DisillusionedSenator',
    tags: ['📣 Activism', '🏫 Campus Life', '😡 Rant', '🔥 Hot Take', '💬 Discussion', '🤷‍♂️ Unpopular Opinion'],
    likes: 8700,
    imageUrl: 'https://picsum.photos/400/300?random=644',
  },
  {
    id: '645',
    title: { en: 'Environmental club beach cleanup: found a shopping cart', zh: '环保社团海滩清洁：捡到了一个购物车' },
    content: { en: 'Also: 47 cigarette butts, a traffic cone, and someone\'s entire set of dentures. Nature is healing.', zh: '还有：47个烟蒂、一个交通锥和某人的一整副假牙。大自然在恢复。' },
    author: 'GreenClub',
    tags: ['📣 Activism', '🤝 Volunteering', '🏫 Campus Life', '📖 Storytime', '🤡 Clown World', '💀 Dead'],
    likes: 6100,
    imageUrl: 'https://picsum.photos/400/300?random=645',
  },
  {
    id: '646',
    title: { en: 'First-gen student orientation made me cry', zh: '第一代大学生迎新让我哭了' },
    content: { en: 'A room full of people who also have no idea what "office hours" means. Finally felt like I belong somewhere.', zh: '一屋子和我一样不知道"office hours"是什么的人。终于感觉自己属于某个地方了。' },
    author: 'FirstGenAndProud',
    tags: ['🏫 Campus Life', '📖 Storytime', '🎭 Emotional', '✨ Inspirational', '🟢 Green Flag', '🧘 Mental Health'],
    likes: 10200,
    imageUrl: 'https://picsum.photos/400/300?random=646',
  },
  {
    id: '647',
    title: { en: 'Protest on campus: students block admin building', zh: '校园抗议：学生封堵行政楼' },
    content: { en: 'Tuition increase of 8% while the president gets a $200K raise. Make it make sense.', zh: '学费涨8%而校长加薪20万。讲讲道理。' },
    author: 'CampusVoice',
    tags: ['📣 Activism', '🏫 Campus Life', '😡 Rant', '💸 Cost of Living', '🔥 Hot Take', '💬 Discussion'],
    likes: 13500,
    imageUrl: 'https://picsum.photos/400/300?random=647',
  },

  // ===== Non-Bay Area / Broader US Campus (10) =====
  {
    id: '648',
    title: { en: 'College football Saturday: campus is a different planet', zh: '大学橄榄球周六：校园变成了另一个星球' },
    content: { en: 'Tailgating starts at 7am. Face paint. 100K people in the stadium. If you haven\'t experienced this you\'re missing out.', zh: '尾门派对早上7点开始。脸上涂颜料。体育场10万人。没经历过的人真的亏了。' },
    author: 'CollegeFootballFan',
    tags: ['🏈 College Football', '🏀 Sports', '🥂 Social Life', '🇺🇸 USA Culture', '✨ Vibe', '📖 Storytime'],
    likes: 7800,
    imageUrl: 'https://picsum.photos/400/300?random=648',
  },
  {
    id: '649',
    title: { en: 'Greek life rush week: what they don\'t tell you', zh: '兄弟会/姐妹会rush周：他们不会告诉你的事' },
    content: { en: 'The networking is real. So are the dues ($3000/semester). And the hazing "that definitely doesn\'t happen."', zh: '人脉是真的。会费也是（$3000/学期）。还有"绝对不存在"的入会仪式。' },
    author: 'GreekLifeInsider',
    tags: ['🍻 Greek Life', '🥂 Social Life', '🏫 Campus Life', '📖 Storytime', '💸 Cost of Living', '🇺🇸 USA Culture', '🚩 Red Flag'],
    likes: 9200,
    imageUrl: 'https://picsum.photos/400/300?random=649',
  },
  {
    id: '650',
    title: { en: 'Moving from California to Michigan for college: culture shock', zh: '从加州搬到密歇根上大学：文化冲击' },
    content: { en: 'It was -20°F in January. People here call it "a bit chilly." My California blood cannot handle this.', zh: '一月份零下29度。这里的人说"有点冷"。我的加州血液承受不了。' },
    author: 'FrozenCalifornian',
    tags: ['❄️ Snow Belt', '✈️ Travel', '📖 Storytime', '🇺🇸 USA Culture', '🏫 Campus Life', '😭 Crying'],
    likes: 6500,
    imageUrl: 'https://picsum.photos/400/300?random=650',
  },
  {
    id: '651',
    title: { en: 'SoCal campus life: beach after class is real', zh: '南加校园生活：下课去海边是真的' },
    content: { en: 'UCSB students literally surf between classes. Meanwhile I\'m at a landlocked school staring at corn.', zh: 'UCSB学生真的课间去冲浪。而我在一个内陆学校盯着玉米。' },
    author: 'BeachEnvy',
    tags: ['🌴 SoCal', '🏫 Campus Life', '✨ Vibe', '🇺🇸 USA Culture', '😭 Crying', '💬 Discussion'],
    likes: 8400,
    imageUrl: 'https://picsum.photos/400/300?random=651',
  },
  {
    id: '652',
    title: { en: 'Texas A&M traditions are a whole religion', zh: '德州农工大学的传统简直是一种宗教' },
    content: { en: 'Midnight Yell Practice. The 12th Man. Ring Dip. Silver Taps. If you know, you know. Gig \'em.', zh: '午夜喊叫练习。第12人。戒指蘸酱。银色安魂曲。懂的人懂。Gig \'em。' },
    author: 'AggieForLife',
    tags: ['🤠 Texas', '🏈 College Football', '🏫 Campus Life', '🇺🇸 USA Culture', '✨ Vibe', '📖 Storytime'],
    likes: 5600,
    imageUrl: 'https://picsum.photos/400/300?random=652',
  },
  {
    id: '653',
    title: { en: 'Small town college: the one bar closes at 11pm', zh: '小镇大学：唯一的酒吧11点关门' },
    content: { en: 'Entertainment options: Walmart, the bar, or staring at the stars. Honestly the stars part isn\'t bad.', zh: '娱乐选项：沃尔玛、酒吧、或者看星星。说实话看星星那部分还不错。' },
    author: 'SmallTownStudent',
    tags: ['🏫 Campus Life', '🌙 Nightlife', '📖 Storytime', '🇺🇸 USA Culture', '😐 Serious', '✨ Vibe'],
    likes: 4200,
    imageUrl: 'https://picsum.photos/400/300?random=653',
  },
  {
    id: '654',
    title: { en: 'Dorm food at a Big Ten school: surprisingly decent', zh: '大十联盟学校的食堂：出乎意料的不错' },
    content: { en: 'Sushi bar, stir-fry station, unlimited cereal. My high school cafeteria could never. Freshman 15 is real though.', zh: '寿司吧、炒菜档口、无限量麦片。我高中食堂根本比不了。新生胖15磅是真的。' },
    author: 'DiningHallCritic',
    tags: ['🍱 Foodie', '🏫 Campus Life', '🇺🇸 USA Culture', '🟢 Green Flag', '💬 Discussion', '🏃 Fitness'],
    likes: 3800,
    imageUrl: 'https://picsum.photos/400/300?random=654',
  },
  {
    id: '655',
    title: { en: 'Out-of-state tuition is highway robbery', zh: '州外学费简直是抢劫' },
    content: { en: '$52K/year vs $15K for in-state. Same classes, same professors, same parking nightmare. Just different zip codes.', zh: '$52K/年 vs 州内$15K。同样的课、同样的教授、同样的停车噩梦。只是邮编不同。' },
    author: 'OutOfStateBroke',
    tags: ['💸 Cost of Living', '🏦 Student Loans', '😡 Rant', '🏫 Campus Life', '🇺🇸 USA Culture', '🔥 Hot Take'],
    likes: 11000,
    imageUrl: 'https://picsum.photos/400/300?random=655',
  },
  {
    id: '656',
    title: { en: 'Snow day means class is still on (via Zoom)', zh: '雪天意味着照常上课（通过Zoom）' },
    content: { en: 'In the old days, snow = no school. Now the professor just says "I\'ll put the Zoom link in Canvas." Thanks technology.', zh: '以前下雪=不上课。现在教授只会说"我把Zoom链接放Canvas上了。"谢谢科技。' },
    author: 'SnowDayRIP',
    tags: ['❄️ Snow Belt', '🏫 Campus Life', '😡 Rant', '🤡 Clown World', '💬 Discussion', '🇺🇸 USA Culture'],
    likes: 7600,
    imageUrl: 'https://picsum.photos/400/300?random=656',
  },
  {
    id: '657',
    title: { en: 'Visited 5 campuses last summer — here\'s my ranking', zh: '去年夏天参观了5个校园——这是我的排名' },
    content: { en: '1. UW Madison (vibes) 2. UT Austin (food) 3. UCLA (weather) 4. UMich (academics) 5. NYU (no campus lol).', zh: '1. 威斯康星麦迪逊（氛围）2. 德州奥斯汀（美食）3. UCLA（天气）4. 密歇根（学术）5. NYU（没校园lol）。' },
    author: 'CampusTourist',
    tags: ['🏫 Campus Life', '✈️ Travel', '📘 Guide', '🇺🇸 USA Culture', '💬 Discussion', '🏈 College Football'],
    likes: 5400,
    imageUrl: 'https://picsum.photos/400/300?random=657',
  },

  // ===== Kpop / Music Subcultures (8) =====
  {
    id: '658',
    title: { en: 'BTS concert tickets: I spent my rent money', zh: 'BTS演唱会门票：我花了房租钱' },
    content: { en: 'Section 300, nosebleed seats, $380 after fees. But when Jimin looked in my general direction, it was worth it.', zh: '300区，山顶位，加上手续费$380。但当Jimin朝我大概的方向看了一眼，值了。' },
    author: 'BTSArmy',
    tags: ['🇰🇷 Kpop Fandom', '🎵 Kpop', '🎶 Concert', '🎶 Music', '💸 Money', '📖 Storytime', '💀 Dead'],
    likes: 14000,
    imageUrl: 'https://picsum.photos/400/300?random=658',
  },
  {
    id: '659',
    title: { en: 'Started learning guitar at 22 — am I too old?', zh: '22岁开始学吉他——我是不是太老了？' },
    content: { en: 'Fingers hurt. Can\'t do bar chords. But I played a full Em to G transition today and it felt like magic.', zh: '手指疼。封闭和弦按不了。但今天完整弹了一个Em到G的转换，感觉像魔法。' },
    author: 'LateStartGuitar',
    tags: ['🎸 Guitar', '🎸 Indie Music', '🎵 Instrument', '🎶 Music', '📖 Storytime', '✨ Vibe', '❓ Question'],
    likes: 7200,
    imageUrl: 'https://picsum.photos/400/300?random=659',
  },
  {
    id: '660',
    title: { en: 'Campus DJ gig: I mixed in the wrong song and nobody noticed', zh: '校园DJ演出：我放错歌了但没人发现' },
    content: { en: 'Accidentally dropped a Kidz Bop version of a Doja Cat song. The crowd vibed harder. I\'m confused.', zh: '不小心放了Doja Cat的Kidz Bop版本。人群嗨得更厉害了。我很困惑。' },
    author: 'AccidentalDJ',
    tags: ['🎧 DJ', '🎶 Music', '🏫 Campus Life', '📖 Storytime', '🤡 Clown World', '💀 Dead', '🎉 Party'],
    likes: 9300,
    imageUrl: 'https://picsum.photos/400/300?random=660',
  },
  {
    id: '661',
    title: { en: 'NewJeans vs aespa: the debate that splits my friend group', zh: 'NewJeans vs aespa：让我朋友圈分裂的辩论' },
    content: { en: 'One side says "Hype Boy" is the song of the generation. The other says "Supernova" changed the game. I just want peace.', zh: '一边说"Hype Boy"是世代之歌。另一边说"Supernova"改变了游戏。我只想要和平。' },
    author: 'KpopMediator',
    tags: ['🇰🇷 Kpop Fandom', '🎵 Kpop', '🎶 Music', '💬 Discussion', '🔥 Hot Take', '🗣️ Real Talk'],
    likes: 11000,
    imageUrl: 'https://picsum.photos/400/300?random=661',
  },
  {
    id: '662',
    title: { en: 'Local indie band played in a parking lot — best show ever', zh: '本地独立乐队在停车场演出——有史以来最好的演出' },
    content: { en: '30 people, no stage, amp powered by a car battery. Raw energy that a stadium show can\'t replicate.', zh: '30个人，没有舞台，音箱用汽车电池供电。体育场演出复制不了的原始能量。' },
    author: 'IndieFan',
    tags: ['🎸 Indie Music', '🎤 Live Music', '🎶 Concert', '🎶 Music', '📖 Storytime', '✨ Vibe', '🟢 Green Flag'],
    likes: 4500,
    imageUrl: 'https://picsum.photos/400/300?random=662',
  },
  {
    id: '663',
    title: { en: 'Spotify Wrapped exposed me to my roommate', zh: 'Spotify年度回顾在室友面前暴露了我' },
    content: { en: 'Top artist: Taylor Swift. 47,000 minutes. My roommate (a metalhead) won\'t look me in the eye anymore.', zh: '最常听艺术家：Taylor Swift。47000分钟。我室友（金属党）不再正眼看我了。' },
    author: 'SwiftieExposed',
    tags: ['🎧 Spotify', '🎶 Music', '🎤 Taylor Swift', '📖 Storytime', '💀 Dead', '👯 Roommate', '😭 Crying'],
    likes: 16000,
    imageUrl: 'https://picsum.photos/400/300?random=663',
  },
  {
    id: '664',
    title: { en: 'Kpop dance cover group: we need a 5th member ASAP', zh: 'Kpop翻跳舞团：急招第5名成员' },
    content: { en: 'Competition is in 3 weeks. Must know SEVENTEEN choreography. Ability to smile while dying inside is a plus.', zh: '比赛还有3周。必须会SEVENTEEN的编舞。能在内心崩溃时保持微笑加分。' },
    author: 'KpopDanceCrew',
    tags: ['🇰🇷 Kpop Fandom', '🎵 Kpop', '💃 Clubbing', '🏫 Campus Life', '🆘 Help', '🏃 Fitness'],
    likes: 2800,
    imageUrl: 'https://picsum.photos/400/300?random=664',
  },
  {
    id: '665',
    title: { en: 'Vinyl collecting on a student budget: possible or delusional?', zh: '学生预算玩黑胶唱片：可行还是做梦？' },
    content: { en: 'Thrift stores have $1 bins. Most of it is Christmas albums but sometimes you find gold. Got a mint Fleetwood Mac for $3.', zh: '二手店有$1区。大部分是圣诞专辑但偶尔能淘到宝。花$3买到一张全新的Fleetwood Mac。' },
    author: 'VinylHunter',
    tags: ['🎶 Music', '🧵 Thrifting', '💸 Money Saving', '📖 Storytime', '✨ Vibe', '💸 Student Discount'],
    likes: 3600,
    imageUrl: 'https://picsum.photos/400/300?random=665',
  },

  // ===== Lifestyle / Fashion / Wellness (12) =====
  {
    id: '666',
    title: { en: 'Skincare routine that actually works for broke students', zh: '真正适合穷学生的护肤流程' },
    content: { en: 'CeraVe cleanser ($12), Neutrogena SPF ($10), The Ordinary niacinamide ($6). Skip the $80 serums.', zh: 'CeraVe洁面($12)，Neutrogena防晒($10)，The Ordinary烟酰胺($6)。跳过$80的精华。' },
    author: 'BudgetSkincare',
    tags: ['💄 Skincare', '💅 Fashion', '💸 Money Saving', '📘 Guide', '💸 Student Discount', '🛠️ Practical'],
    likes: 8900,
    imageUrl: 'https://picsum.photos/400/300?random=666',
  },
  {
    id: '667',
    title: { en: 'Thrift store haul: entire outfit for $12', zh: '二手店战利品：全套搭配$12' },
    content: { en: 'Levi\'s jeans ($4), oversized flannel ($3), vintage Nike tee ($5). Looking expensive is a skill, not a budget.', zh: 'Levi\'s牛仔裤($4)，大号法兰绒衬衫($3)，复古Nike T恤($5)。看起来贵是技术，不是预算。' },
    author: 'ThriftQueen',
    tags: ['🧵 Thrifting', '💅 Fashion', '💸 Money Saving', '📖 Storytime', '✨ Vibe', '💸 Student Discount'],
    likes: 7200,
    imageUrl: 'https://picsum.photos/400/300?random=667',
  },
  {
    id: '668',
    title: { en: 'Cut my own hair. It went... okay?', zh: '自己剪了头发。效果...还行？' },
    content: { en: 'Watched a 10-minute YouTube tutorial. Left side is slightly shorter. Nobody has mentioned it. Yet.', zh: '看了10分钟的YouTube教程。左边比右边短了一点。还没人提。暂时。' },
    author: 'DIYBarber',
    tags: ['💇 Hair', '💅 Fashion', '💸 Money Saving', '📖 Storytime', '🤡 Clown World', '🛠️ Practical'],
    likes: 5500,
    imageUrl: 'https://picsum.photos/400/300?random=668',
  },
  {
    id: '669',
    title: { en: 'My plant collection is my entire personality now', zh: '我的植物收藏现在就是我的全部性格' },
    content: { en: 'Started with one succulent. Now I have 23 plants and I talk to them. My monstera is named Kevin.', zh: '从一棵多肉开始。现在有23棵植物而且我跟它们说话。我的龟背竹叫Kevin。' },
    author: 'PlantParent',
    tags: ['🪴 Plants', '📖 Storytime', '✨ Vibe', '🏠 Renting', '🧘 Mental Health', '💀 Dead'],
    likes: 6800,
    imageUrl: 'https://picsum.photos/400/300?random=669',
  },
  {
    id: '670',
    title: { en: 'Morning yoga before 8am class: life changing', zh: '8点课前晨练瑜伽：改变人生' },
    content: { en: '15 minutes of sun salutations. I went from "I want to die" to "I mildly want to live" every morning. Progress.', zh: '15分钟拜日式。每天早上从"我想死"变成"我有点想活"。进步了。' },
    author: 'YogaNewbie',
    tags: ['🧘 Yoga', '🏃 Fitness', '🧘 Mental Health', '🏫 Campus Life', '✨ Vibe', '🟢 Green Flag'],
    likes: 4100,
    imageUrl: 'https://picsum.photos/400/300?random=670',
  },
  {
    id: '671',
    title: { en: 'Campus coffee shop tier list (brutally honest)', zh: '校园咖啡店排名（残酷诚实）' },
    content: { en: 'S: Library cafe (quiet). A: Student union Starbucks (fast). B: Art building espresso cart (overpriced). F: Vending machine (criminal).', zh: 'S: 图书馆咖啡厅（安静）。A: 学生会星巴克（快）。B: 艺术楼浓缩咖啡车（贵）。F: 自动贩卖机（犯罪）。' },
    author: 'CoffeeCritic',
    tags: ['☕ Coffee', '🍱 Foodie', '🏫 Campus Life', '📘 Guide', '🔥 Hot Take', '💬 Discussion'],
    likes: 5900,
    imageUrl: 'https://picsum.photos/400/300?random=671',
  },
  {
    id: '672',
    title: { en: 'Amazon Prime Student is the best deal in existence', zh: 'Amazon Prime学生版是世界上最划算的东西' },
    content: { en: '$7.49/month. Free shipping, Prime Video, Prime Music. I order everything from textbooks to toilet paper.', zh: '$7.49/月。免费配送、Prime Video、Prime Music。从教科书到卫生纸我什么都在上面买。' },
    author: 'PrimeAddict',
    tags: ['📦 Amazon', '💸 Student Discount', '💸 Money Saving', '📘 Guide', '🛠️ Practical', '🛒 Costco'],
    likes: 4300,
    imageUrl: 'https://picsum.photos/400/300?random=672',
  },
  {
    id: '673',
    title: { en: 'Target run at midnight: a spiritual experience', zh: '午夜Target购物：一种精神体验' },
    content: { en: 'Went in for toothpaste. Left with a lamp, 3 candles, a rug, and zero toothpaste. The Target effect is real.', zh: '进去买牙膏。出来了一盏灯、3个蜡烛、一块地毯，和零牙膏。Target效应是真的。' },
    author: 'TargetVictim',
    tags: ['🛒 Target', '💸 Money', '📖 Storytime', '🤡 Clown World', '💀 Dead', '🇺🇸 USA Culture'],
    likes: 10500,
    imageUrl: 'https://picsum.photos/400/300?random=673',
  },
  {
    id: '674',
    title: { en: 'Campus gym etiquette: please wipe your machines', zh: '校园健身房礼仪：请擦你的器材' },
    content: { en: 'Found a puddle of sweat on the bench press today. There are paper towels RIGHT THERE. Animals.', zh: '今天在卧推凳上发现一滩汗。纸巾就在旁边。禽兽。' },
    author: 'GymRanter',
    tags: ['🏋️ Gym', '🏃 Fitness', '😡 Rant', '🏫 Campus Life', '🤬 AITA', '😡 Rant'],
    likes: 6700,
    imageUrl: 'https://picsum.photos/400/300?random=674',
  },
  {
    id: '675',
    title: { en: 'Cycling to campus: saves money, builds legs, dodges death', zh: '骑车上学：省钱、练腿、躲死' },
    content: { en: 'Car drivers don\'t see you. Pedestrians don\'t hear you. But $0 parking and quads of steel.', zh: '开车的看不见你。走路的听不见你。但停车$0而且腿变钢铁。' },
    author: 'BikeCommuter',
    tags: ['🚴 Cycling', '🏃 Fitness', '💸 Money Saving', '🚌 Transport', '🏫 Campus Life', '🛠️ Practical'],
    likes: 3800,
    imageUrl: 'https://picsum.photos/400/300?random=675',
  },
  {
    id: '676',
    title: { en: 'Weekend camping trip: $30 total for 3 days of peace', zh: '周末露营：$30换来3天平静' },
    content: { en: 'National forest = free camping. Brought rice, canned beans, and a hammock. Best mental reset of the semester.', zh: '国家森林=免费露营。带了米、罐头豆子和吊床。这学期最好的精神重启。' },
    author: 'BudgetCamper',
    tags: ['🏕️ Camping', '✈️ Travel', '💸 Money Saving', '🧘 Mental Health', '✨ Vibe', '🟢 Green Flag'],
    likes: 5200,
    imageUrl: 'https://picsum.photos/400/300?random=676',
  },
  {
    id: '677',
    title: { en: 'Meal prep Sunday: 5 days of food in 2 hours', zh: '周日meal prep：2小时搞定5天的饭' },
    content: { en: 'Chicken thighs + rice + broccoli. Boring? Yes. Cheap? Yes. Effective? My wallet says yes.', zh: '鸡腿+米饭+西兰花。无聊？是。便宜？是。有效？我的钱包说是。' },
    author: 'MealPrepKing',
    tags: ['🍱 Foodie', '💸 Money Saving', '🏃 Fitness', '📘 Guide', '🛠️ Practical', '🏫 Campus Life'],
    likes: 6100,
    imageUrl: 'https://picsum.photos/400/300?random=677',
  },

  // ===== Positive Tech Career / Mentorship (8) =====
  {
    id: '678',
    title: { en: 'My manager is actually great — green flags to look for', zh: '我的经理真的很好——寻找这些绿旗' },
    content: { en: '1:1s every week. Pushes back on unrealistic deadlines. Encouraged me to take PTO. They exist.', zh: '每周1:1。拒绝不合理的deadline。鼓励我休假。这样的人是存在的。' },
    author: 'LuckyDev',
    tags: ['💼 Tech Career', '🟢 Green Flag', '💼 Career Advice', '🏢 Corporate Life', '✨ Inspirational', '💬 Discussion'],
    likes: 8400,
    imageUrl: 'https://picsum.photos/400/300?random=678',
  },
  {
    id: '679',
    title: { en: 'Non-FAANG career path: $150K without selling your soul', zh: '非FAANG职业路径：不出卖灵魂年薪$150K' },
    content: { en: 'Fintech, health tech, dev tools startups. Better WLB, still great pay. Stop obsessing over Google.', zh: '金融科技、健康科技、开发工具创业公司。更好的WLB，薪资依然不错。别再迷恋Google了。' },
    author: 'NonFAANGDev',
    tags: ['💼 Tech Career', '💼 Career Advice', '💸 Money', '🔥 Hot Take', '🤷‍♂️ Unpopular Opinion', '💬 Discussion'],
    likes: 7600,
    imageUrl: 'https://picsum.photos/400/300?random=679',
  },
  {
    id: '680',
    title: { en: 'Found a mentor on LinkedIn: here\'s exactly how', zh: '在LinkedIn上找到导师：具体方法' },
    content: { en: 'Don\'t say "Can you be my mentor?" Say "I read your post on X, and I have a specific question." Be genuine. Follow up.', zh: '别说"你能当我的导师吗？"说"我看了你关于X的帖子，我有一个具体问题。"真诚。跟进。' },
    author: 'MentorshipGuru',
    tags: ['💼 Career Advice', '💼 Tech Career', '📘 Guide', '🛠️ Practical', '💡 Study Tips', '✨ Inspirational'],
    likes: 5900,
    imageUrl: 'https://picsum.photos/400/300?random=680',
  },
  {
    id: '681',
    title: { en: 'Leveling up as a junior dev: what actually matters', zh: '初级开发者晋升：什么真正重要' },
    content: { en: 'Not LeetCode. Not side projects. Communication, ownership, and asking good questions. That\'s 80% of it.', zh: '不是LeetCode。不是副业项目。沟通、主动性和问好问题。这是80%。' },
    author: 'SeniorDevAdvice',
    tags: ['💼 Tech Career', '⌨️ Coding', '💼 Career Advice', '📘 Guide', '🧠 Advanced', '🗣️ Real Talk'],
    likes: 9200,
    imageUrl: 'https://picsum.photos/400/300?random=681',
  },
  {
    id: '682',
    title: { en: 'Bootcamp grad to $120K job: timeline and what I learned', zh: 'Bootcamp毕业到$120K工作：时间线和我学到的' },
    content: { en: '6-month bootcamp -> 3 months job search -> startup offer. The bootcamp taught me 20%, the job taught me 80%.', zh: '6个月bootcamp -> 3个月找工作 -> 创业公司offer。Bootcamp教了我20%，工作教了我80%。' },
    author: 'BootcampSuccess',
    tags: ['💼 Tech Career', '⌨️ Coding', '🏆 Success Story', '📖 Storytime', '💸 Money', '✨ Inspirational'],
    likes: 6800,
    imageUrl: 'https://picsum.photos/400/300?random=682',
  },
  {
    id: '683',
    title: { en: 'Open source contribution got me an interview at GitHub', zh: '开源贡献让我获得了GitHub的面试' },
    content: { en: 'Fixed a typo in docs -> reviewed a PR -> maintained a small feature. 6 months later, a recruiter DM\'d me.', zh: '修了文档错别字 -> review了一个PR -> 维护了一个小功能。6个月后招聘官给我发了私信。' },
    author: 'OpenSourcePath',
    tags: ['⌨️ Coding', '💼 Tech Career', '📖 Storytime', '💼 Career Advice', '🛠️ Tools', '✨ Inspirational', '🐍 Python'],
    likes: 7100,
    imageUrl: 'https://picsum.photos/400/300?random=683',
  },
  {
    id: '684',
    title: { en: 'Imposter syndrome 3 years in: when does it stop?', zh: '入行三年的冒充者综合征：什么时候能停？' },
    content: { en: 'Senior devs tell me they still feel it. Great. At least we\'re all pretending together.', zh: '高级开发者告诉我他们也有。很好。至少我们一起装。' },
    author: 'ImposterForever',
    tags: ['💼 Tech Career', '🧘 Mental Health', '😰 Anxiety', '🗣️ Real Talk', '💬 Discussion', '🏢 Corporate Life'],
    likes: 12500,
    imageUrl: 'https://picsum.photos/400/300?random=684',
  },
  {
    id: '685',
    title: { en: 'Remote work from a cafe: productivity hack or delusion?', zh: '咖啡店远程办公：效率神器还是自欺欺人？' },
    content: { en: 'The wifi is unreliable, the chair hurts, and I spent $7 on oat milk lattes. But I wrote 200 lines of code. Worth it?', zh: 'WiFi不稳定，椅子不舒服，花了$7买燕麦奶拿铁。但我写了200行代码。值吗？' },
    author: 'CafeCoder',
    tags: ['☕ Coffee', '💼 Tech Career', '⌨️ Coding', '💬 Discussion', '✨ Vibe', '⚡ Productivity'],
    likes: 5400,
    imageUrl: 'https://picsum.photos/400/300?random=685',
  },

  // ===== International Student Life Beyond Visa (8) =====
  {
    id: '686',
    title: { en: 'First Thanksgiving in America: my host family fed me 5 types of pie', zh: '在美国过的第一个感恩节：寄宿家庭给我吃了5种派' },
    content: { en: 'Pumpkin, pecan, apple, sweet potato, and something called "chess pie" from the South. I rolled home.', zh: '南瓜、山核桃、苹果、红薯，还有一种南方叫"chess pie"的。我滚回家的。' },
    author: 'FirstThanksgiving',
    tags: ['🌏 International Students', '🍱 Foodie', '📖 Storytime', '🇺🇸 USA Culture', '✨ Vibe', '🟢 Green Flag'],
    likes: 7800,
    imageUrl: 'https://picsum.photos/400/300?random=686',
  },
  {
    id: '687',
    title: { en: 'ISO International Night was the highlight of my year', zh: 'ISO国际之夜是我今年的高光' },
    content: { en: 'Students from 30 countries performed. I did a Chinese calligraphy demo. A girl from Brazil taught everyone samba.', zh: '30个国家的学生表演。我展示了中国书法。一个巴西女孩教大家跳桑巴。' },
    author: 'ISOPresident',
    tags: ['🌏 International Students', '🏫 Campus Life', '🥂 Social Life', '📖 Storytime', '✨ Vibe', '🎭 Theater'],
    likes: 4600,
    imageUrl: 'https://picsum.photos/400/300?random=687',
  },
  {
    id: '688',
    title: { en: 'Reverse culture shock: going home feels weird now', zh: '逆向文化冲击：回家感觉怪怪的' },
    content: { en: 'I automatically say "sorry" and "excuse me" in Chinese supermarkets. People look at me like I\'m an alien.', zh: '我在中国超市不自觉地说"sorry"和"excuse me"。别人看我像外星人。' },
    author: 'CultureShocked',
    tags: ['🌏 International Students', '🇨🇳 Chinese Content', '📖 Storytime', '🤡 Clown World', '🚧 Language Barrier', '✈️ Travel'],
    likes: 9500,
    imageUrl: 'https://picsum.photos/400/300?random=688',
  },
  {
    id: '689',
    title: { en: 'Making American friends as an international student: real talk', zh: '留学生交美国朋友：说点实话' },
    content: { en: 'Join clubs, not just your country\'s student association. Say yes to everything in the first month. It gets easier.', zh: '加入社团，不只是你国家的学生会。第一个月什么都说好。会越来越容易的。' },
    author: 'IntlFriendshipGuide',
    tags: ['🌏 International Students', '🥂 Social Life', '📘 Guide', '🗣️ Real Talk', '💡 Study Tips', '🏫 Campus Life'],
    likes: 6200,
    imageUrl: 'https://picsum.photos/400/300?random=689',
  },
  {
    id: '690',
    title: { en: 'Cooking Chinese food in the dorm: smoke alarm went off', zh: '在宿舍做中餐：烟雾报警器响了' },
    content: { en: 'Just stir-fried some vegetables. The entire floor evacuated. Now I\'m the "fire hazard international student."', zh: '就炒了个菜。整层楼疏散了。现在我是"火灾隐患留学生"。' },
    author: 'DormChef',
    tags: ['🍱 Foodie', '🍜 Chinese Food', '🌏 International Students', '📖 Storytime', '🤡 Clown World', '💀 Dead', '🏫 Dorm Life'],
    likes: 13000,
    imageUrl: 'https://picsum.photos/400/300?random=690',
  },
  {
    id: '691',
    title: { en: 'Applied to jobs in my home country: they want US experience', zh: '在祖国投了简历：他们要美国经验' },
    content: { en: 'US companies want US experience. Home country companies also want US experience. I have... classroom experience.', zh: '美国公司要美国经验。国内公司也要美国经验。我有...课堂经验。' },
    author: 'JobSearchLoop',
    tags: ['🌏 International Students', '💼 Job Search', '💼 Career Advice', '😡 Rant', '😰 Anxiety', '🗣️ Real Talk'],
    likes: 8400,
    imageUrl: 'https://picsum.photos/400/300?random=691',
  },
  {
    id: '692',
    title: { en: 'American measurement system: I still can\'t feel Fahrenheit', zh: '美国度量衡：我到现在还感受不了华氏度' },
    content: { en: 'Is 75°F hot or cold? What\'s a "cup" of flour? Why are there 12 inches in a foot? This country chose violence.', zh: '75°F是热还是冷？一"杯"面粉是多少？为什么一英尺有12英寸？这个国家选择了暴力。' },
    author: 'MetricPerson',
    tags: ['🌏 International Students', '🇺🇸 USA Culture', '🤡 Clown World', '💀 Dead', '😡 Rant', '💬 Discussion'],
    likes: 11000,
    imageUrl: 'https://picsum.photos/400/300?random=692',
  },
  {
    id: '693',
    title: { en: 'CPT internship: working legally while studying', zh: 'CPT实习：合法边学边工作' },
    content: { en: 'Must be related to your major. Apply through your international office BEFORE starting. Don\'t risk your visa status.', zh: '必须和你的专业相关。开始之前通过国际办公室申请。不要拿签证身份冒险。' },
    author: 'CPTExpert',
    tags: ['🌏 International Students', '💼 Career Advice', '🎓 Internship', '📘 Guide', '⚠️ Warning', '💼 Tech Career'],
    likes: 4500,
    imageUrl: 'https://picsum.photos/400/300?random=693',
  },

  // ===== Misc Fun / Viral Style (6) =====
  {
    id: '694',
    title: { en: 'Ranking every bathroom on campus (yes I\'m that person)', zh: '给校园每个厕所排名（对我就是那种人）' },
    content: { en: 'S tier: 3rd floor library (clean, quiet, heated seat). F tier: Engineering building basement (war zone).', zh: 'S级：图书馆3楼（干净、安静、加热坐垫）。F级：工程楼地下室（战区）。' },
    author: 'BathroomCritic',
    tags: ['🚽 Hidden Gems', '🏫 Campus Life', '📘 Guide', '🔥 Hot Take', '💬 Discussion', '🤡 Clown World'],
    likes: 15000,
    imageUrl: 'https://picsum.photos/400/300?random=694',
  },
  {
    id: '695',
    title: { en: 'My professor uses memes in lecture slides unironically', zh: '我教授在课件里非讽刺地用表情包' },
    content: { en: 'Today he put a Surprised Pikachu face after a calculus proof. Entire class lost it. Best professor ever.', zh: '今天他在一个微积分证明后面放了惊讶皮卡丘。全班都笑疯了。最好的教授。' },
    author: 'MemeProfFan',
    tags: ['🏫 Campus Life', '🖼️ Meme', '📖 Storytime', '💀 Dead', '✨ Vibe', '🟢 Green Flag', '📚 Academic'],
    likes: 18000,
    imageUrl: 'https://picsum.photos/400/300?random=695',
  },
  {
    id: '696',
    title: { en: 'Finals week: the library becomes a homeless shelter', zh: '期末周：图书馆变成了收容所' },
    content: { en: 'People sleeping on the floor. Someone brought a rice cooker. There\'s a guy in a sleeping bag under the desk. We\'re all surviving.', zh: '有人睡在地板上。有人带了电饭锅。桌子底下有个人在睡袋里。我们都在求生。' },
    author: 'FinalsSurvivor',
    tags: ['🏫 Campus Life', '📚 Academic', '😰 Anxiety', '📖 Storytime', '💀 Dead', '😭 Crying', '🍱 Foodie'],
    likes: 20000,
    imageUrl: 'https://picsum.photos/400/300?random=696',
  },
  {
    id: '697',
    title: { en: 'Lost my AirPods in the campus bus AGAIN', zh: '又在校园巴士上丢了AirPods' },
    content: { en: 'This is the third pair. Find My says they\'re on the Route 7 bus heading to the stadium. I\'m in chemistry class.', zh: '这是第三副了。查找我的说它们在开往体育场的7路车上。我在化学课。' },
    author: 'AirPodsLoser',
    tags: ['🚌 Transport', '🏫 Campus Life', '📖 Storytime', '🤡 Clown World', '💀 Dead', '😭 Crying'],
    likes: 9800,
    imageUrl: 'https://picsum.photos/400/300?random=697',
  },
  {
    id: '698',
    title: { en: 'Rate My Professor review that made me cry laughing', zh: 'Rate My Professor上让我笑哭的评论' },
    content: { en: '"If you enjoy confusion, self-doubt, and existential dread, this class is for you. Textbook optional because it won\'t help anyway."', zh: '"如果你喜欢困惑、自我怀疑和存在主义恐惧，这门课适合你。教科书可选因为反正也没用。"' },
    author: 'RMPScrolling',
    tags: ['🏫 Campus Life', '📚 Academic', '📖 Storytime', '💀 Dead', '🤡 Clown World', '😭 Crying', '📝 Course Review'],
    likes: 22000,
    imageUrl: 'https://picsum.photos/400/300?random=698',
  },
  {
    id: '699',
    title: { en: 'Graduation is in 2 weeks and I have no plan', zh: '还有两周就毕业了但我没有计划' },
    content: { en: 'Everyone else has a job or grad school lined up. I have a degree, $40K in debt, and a cat who depends on me. Adulting is terrifying.', zh: '其他人都有工作或研究生院了。我有一个学位、$4万债务和一只依赖我的猫。成年人好可怕。' },
    author: 'AlmostGrad',
    tags: ['🎓 New Grads', '😰 Anxiety', '💼 Job Search', '🏦 Student Loans', '📖 Storytime', '🗣️ Real Talk', '🐱 Cat'],
    likes: 16000,
    imageUrl: 'https://picsum.photos/400/300?random=699',
  },
];
